// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCommentRepository creates a new instance of CommentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepository {
	mock := &CommentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CommentRepository is an autogenerated mock type for the CommentRepository type
type CommentRepository struct {
	mock.Mock
}

type CommentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CommentRepository) EXPECT() *CommentRepository_Expecter {
	return &CommentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type CommentRepository
func (_mock *CommentRepository) Create(ctx context.Context, comment *domain.Comment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Comment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CommentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CommentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *domain.Comment
func (_e *CommentRepository_Expecter) Create(ctx interface{}, comment interface{}) *CommentRepository_Create_Call {
	return &CommentRepository_Create_Call{Call: _e.mock.On("Create", ctx, comment)}
}

func (_c *CommentRepository_Create_Call) Run(run func(ctx context.Context, comment *domain.Comment)) *CommentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Comment
		if args[1] != nil {
			arg1 = args[1].(*domain.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_Create_Call) Return(err error) *CommentRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CommentRepository_Create_Call) RunAndReturn(run func(ctx context.Context, comment *domain.Comment) error) *CommentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CommentRepository
func (_mock *CommentRepository) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CommentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CommentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CommentRepository_Expecter) Delete(ctx interface{}, id interface{}) *CommentRepository_Delete_Call {
	return &CommentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CommentRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *CommentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_Delete_Call) Return(err error) *CommentRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CommentRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *CommentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type CommentRepository
func (_mock *CommentRepository) GetByID(ctx context.Context, id int64) (*domain.Comment, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.Comment, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.Comment); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CommentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CommentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CommentRepository_GetByID_Call {
	return &CommentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CommentRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *CommentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_GetByID_Call) Return(comment *domain.Comment, err error) *CommentRepository_GetByID_Call {
	_c.Call.Return(comment, err)
	return _c
}

func (_c *CommentRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.Comment, error)) *CommentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPostID provides a mock function for the type CommentRepository
func (_mock *CommentRepository) GetByPostID(ctx context.Context, postID int64, cursor int64, limit int) ([]domain.Comment, error) {
	ret := _mock.Called(ctx, postID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetByPostID")
	}

	var r0 []domain.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int) ([]domain.Comment, error)); ok {
		return returnFunc(ctx, postID, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int) []domain.Comment); ok {
		r0 = returnFunc(ctx, postID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, int) error); ok {
		r1 = returnFunc(ctx, postID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_GetByPostID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPostID'
type CommentRepository_GetByPostID_Call struct {
	*mock.Call
}

// GetByPostID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - cursor int64
//   - limit int
func (_e *CommentRepository_Expecter) GetByPostID(ctx interface{}, postID interface{}, cursor interface{}, limit interface{}) *CommentRepository_GetByPostID_Call {
	return &CommentRepository_GetByPostID_Call{Call: _e.mock.On("GetByPostID", ctx, postID, cursor, limit)}
}

func (_c *CommentRepository_GetByPostID_Call) Run(run func(ctx context.Context, postID int64, cursor int64, limit int)) *CommentRepository_GetByPostID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CommentRepository_GetByPostID_Call) Return(comments []domain.Comment, err error) *CommentRepository_GetByPostID_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *CommentRepository_GetByPostID_Call) RunAndReturn(run func(ctx context.Context, postID int64, cursor int64, limit int) ([]domain.Comment, error)) *CommentRepository_GetByPostID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplies provides a mock function for the type CommentRepository
func (_mock *CommentRepository) GetReplies(ctx context.Context, parentID int64, cursor int64, limit int) ([]domain.Comment, error) {
	ret := _mock.Called(ctx, parentID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetReplies")
	}

	var r0 []domain.Comment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int) ([]domain.Comment, error)); ok {
		return returnFunc(ctx, parentID, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64, int) []domain.Comment); ok {
		r0 = returnFunc(ctx, parentID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Comment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64, int) error); ok {
		r1 = returnFunc(ctx, parentID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommentRepository_GetReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplies'
type CommentRepository_GetReplies_Call struct {
	*mock.Call
}

// GetReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
//   - cursor int64
//   - limit int
func (_e *CommentRepository_Expecter) GetReplies(ctx interface{}, parentID interface{}, cursor interface{}, limit interface{}) *CommentRepository_GetReplies_Call {
	return &CommentRepository_GetReplies_Call{Call: _e.mock.On("GetReplies", ctx, parentID, cursor, limit)}
}

func (_c *CommentRepository_GetReplies_Call) Run(run func(ctx context.Context, parentID int64, cursor int64, limit int)) *CommentRepository_GetReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CommentRepository_GetReplies_Call) Return(comments []domain.Comment, err error) *CommentRepository_GetReplies_Call {
	_c.Call.Return(comments, err)
	return _c
}

func (_c *CommentRepository_GetReplies_Call) RunAndReturn(run func(ctx context.Context, parentID int64, cursor int64, limit int) ([]domain.Comment, error)) *CommentRepository_GetReplies_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CommentRepository
func (_mock *CommentRepository) Update(ctx context.Context, comment *domain.Comment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Comment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CommentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CommentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - comment *domain.Comment
func (_e *CommentRepository_Expecter) Update(ctx interface{}, comment interface{}) *CommentRepository_Update_Call {
	return &CommentRepository_Update_Call{Call: _e.mock.On("Update", ctx, comment)}
}

func (_c *CommentRepository_Update_Call) Run(run func(ctx context.Context, comment *domain.Comment)) *CommentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Comment
		if args[1] != nil {
			arg1 = args[1].(*domain.Comment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CommentRepository_Update_Call) Return(err error) *CommentRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CommentRepository_Update_Call) RunAndReturn(run func(ctx context.Context, comment *domain.Comment) error) *CommentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
