// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewEmailSender creates a new instance of EmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailSender {
	mock := &EmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

type EmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailSender) EXPECT() *EmailSender_Expecter {
	return &EmailSender_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type EmailSender
func (_mock *EmailSender) Send(data *domain.EmailEnvelope) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.EmailEnvelope) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type EmailSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - data *domain.EmailEnvelope
func (_e *EmailSender_Expecter) Send(data interface{}) *EmailSender_Send_Call {
	return &EmailSender_Send_Call{Call: _e.mock.On("Send", data)}
}

func (_c *EmailSender_Send_Call) Run(run func(data *domain.EmailEnvelope)) *EmailSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.EmailEnvelope
		if args[0] != nil {
			arg0 = args[0].(*domain.EmailEnvelope)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EmailSender_Send_Call) Return(err error) *EmailSender_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailSender_Send_Call) RunAndReturn(run func(data *domain.EmailEnvelope) error) *EmailSender_Send_Call {
	_c.Call.Return(run)
	return _c
}
