// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewFollowService creates a new instance of FollowService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFollowService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FollowService {
	mock := &FollowService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FollowService is an autogenerated mock type for the FollowService type
type FollowService struct {
	mock.Mock
}

type FollowService_Expecter struct {
	mock *mock.Mock
}

func (_m *FollowService) EXPECT() *FollowService_Expecter {
	return &FollowService_Expecter{mock: &_m.Mock}
}

// Follow provides a mock function for the type FollowService
func (_mock *FollowService) Follow(ctx context.Context, followerID int64, followeeID int64) error {
	ret := _mock.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FollowService_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type FollowService_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID int64
//   - followeeID int64
func (_e *FollowService_Expecter) Follow(ctx interface{}, followerID interface{}, followeeID interface{}) *FollowService_Follow_Call {
	return &FollowService_Follow_Call{Call: _e.mock.On("Follow", ctx, followerID, followeeID)}
}

func (_c *FollowService_Follow_Call) Run(run func(ctx context.Context, followerID int64, followeeID int64)) *FollowService_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FollowService_Follow_Call) Return(err error) *FollowService_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FollowService_Follow_Call) RunAndReturn(run func(ctx context.Context, followerID int64, followeeID int64) error) *FollowService_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowers provides a mock function for the type FollowService
func (_mock *FollowService) GetFollowers(ctx context.Context, params domain.FollowParams) (domain.PaginatedResult[domain.SocialUser], error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowers")
	}

	var r0 domain.PaginatedResult[domain.SocialUser]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FollowParams) (domain.PaginatedResult[domain.SocialUser], error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FollowParams) domain.PaginatedResult[domain.SocialUser]); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(domain.PaginatedResult[domain.SocialUser])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FollowParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FollowService_GetFollowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowers'
type FollowService_GetFollowers_Call struct {
	*mock.Call
}

// GetFollowers is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.FollowParams
func (_e *FollowService_Expecter) GetFollowers(ctx interface{}, params interface{}) *FollowService_GetFollowers_Call {
	return &FollowService_GetFollowers_Call{Call: _e.mock.On("GetFollowers", ctx, params)}
}

func (_c *FollowService_GetFollowers_Call) Run(run func(ctx context.Context, params domain.FollowParams)) *FollowService_GetFollowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FollowParams
		if args[1] != nil {
			arg1 = args[1].(domain.FollowParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FollowService_GetFollowers_Call) Return(paginatedResult domain.PaginatedResult[domain.SocialUser], err error) *FollowService_GetFollowers_Call {
	_c.Call.Return(paginatedResult, err)
	return _c
}

func (_c *FollowService_GetFollowers_Call) RunAndReturn(run func(ctx context.Context, params domain.FollowParams) (domain.PaginatedResult[domain.SocialUser], error)) *FollowService_GetFollowers_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowings provides a mock function for the type FollowService
func (_mock *FollowService) GetFollowings(ctx context.Context, params domain.FollowParams) (domain.PaginatedResult[domain.SocialUser], error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowings")
	}

	var r0 domain.PaginatedResult[domain.SocialUser]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FollowParams) (domain.PaginatedResult[domain.SocialUser], error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.FollowParams) domain.PaginatedResult[domain.SocialUser]); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(domain.PaginatedResult[domain.SocialUser])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.FollowParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FollowService_GetFollowings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowings'
type FollowService_GetFollowings_Call struct {
	*mock.Call
}

// GetFollowings is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.FollowParams
func (_e *FollowService_Expecter) GetFollowings(ctx interface{}, params interface{}) *FollowService_GetFollowings_Call {
	return &FollowService_GetFollowings_Call{Call: _e.mock.On("GetFollowings", ctx, params)}
}

func (_c *FollowService_GetFollowings_Call) Run(run func(ctx context.Context, params domain.FollowParams)) *FollowService_GetFollowings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.FollowParams
		if args[1] != nil {
			arg1 = args[1].(domain.FollowParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FollowService_GetFollowings_Call) Return(paginatedResult domain.PaginatedResult[domain.SocialUser], err error) *FollowService_GetFollowings_Call {
	_c.Call.Return(paginatedResult, err)
	return _c
}

func (_c *FollowService_GetFollowings_Call) RunAndReturn(run func(ctx context.Context, params domain.FollowParams) (domain.PaginatedResult[domain.SocialUser], error)) *FollowService_GetFollowings_Call {
	_c.Call.Return(run)
	return _c
}

// Unfollow provides a mock function for the type FollowService
func (_mock *FollowService) Unfollow(ctx context.Context, followerID int64, followeeID int64) error {
	ret := _mock.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for Unfollow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FollowService_Unfollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfollow'
type FollowService_Unfollow_Call struct {
	*mock.Call
}

// Unfollow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID int64
//   - followeeID int64
func (_e *FollowService_Expecter) Unfollow(ctx interface{}, followerID interface{}, followeeID interface{}) *FollowService_Unfollow_Call {
	return &FollowService_Unfollow_Call{Call: _e.mock.On("Unfollow", ctx, followerID, followeeID)}
}

func (_c *FollowService_Unfollow_Call) Run(run func(ctx context.Context, followerID int64, followeeID int64)) *FollowService_Unfollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FollowService_Unfollow_Call) Return(err error) *FollowService_Unfollow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FollowService_Unfollow_Call) RunAndReturn(run func(ctx context.Context, followerID int64, followeeID int64) error) *FollowService_Unfollow_Call {
	_c.Call.Return(run)
	return _c
}
