// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewHealthRedis creates a new instance of HealthRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthRedis {
	mock := &HealthRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthRedis is an autogenerated mock type for the HealthRedis type
type HealthRedis struct {
	mock.Mock
}

type HealthRedis_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthRedis) EXPECT() *HealthRedis_Expecter {
	return &HealthRedis_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type HealthRedis
func (_mock *HealthRedis) Ping(ctx context.Context) *redis.StatusCmd {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *redis.StatusCmd
	if returnFunc, ok := ret.Get(0).(func(context.Context) *redis.StatusCmd); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}
	return r0
}

// HealthRedis_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type HealthRedis_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HealthRedis_Expecter) Ping(ctx interface{}) *HealthRedis_Ping_Call {
	return &HealthRedis_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *HealthRedis_Ping_Call) Run(run func(ctx context.Context)) *HealthRedis_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HealthRedis_Ping_Call) Return(statusCmd *redis.StatusCmd) *HealthRedis_Ping_Call {
	_c.Call.Return(statusCmd)
	return _c
}

func (_c *HealthRedis_Ping_Call) RunAndReturn(run func(ctx context.Context) *redis.StatusCmd) *HealthRedis_Ping_Call {
	_c.Call.Return(run)
	return _c
}
