// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMediaService creates a new instance of MediaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMediaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MediaService {
	mock := &MediaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MediaService is an autogenerated mock type for the MediaService type
type MediaService struct {
	mock.Mock
}

type MediaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MediaService) EXPECT() *MediaService_Expecter {
	return &MediaService_Expecter{mock: &_m.Mock}
}

// ConfirmUpload provides a mock function for the type MediaService
func (_mock *MediaService) ConfirmUpload(ctx context.Context, input []domain.ConfirmFileParams) ([]string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUpload")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ConfirmFileParams) ([]string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ConfirmFileParams) []string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.ConfirmFileParams) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MediaService_ConfirmUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUpload'
type MediaService_ConfirmUpload_Call struct {
	*mock.Call
}

// ConfirmUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - input []domain.ConfirmFileParams
func (_e *MediaService_Expecter) ConfirmUpload(ctx interface{}, input interface{}) *MediaService_ConfirmUpload_Call {
	return &MediaService_ConfirmUpload_Call{Call: _e.mock.On("ConfirmUpload", ctx, input)}
}

func (_c *MediaService_ConfirmUpload_Call) Run(run func(ctx context.Context, input []domain.ConfirmFileParams)) *MediaService_ConfirmUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.ConfirmFileParams
		if args[1] != nil {
			arg1 = args[1].([]domain.ConfirmFileParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaService_ConfirmUpload_Call) Return(strings []string, err error) *MediaService_ConfirmUpload_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MediaService_ConfirmUpload_Call) RunAndReturn(run func(ctx context.Context, input []domain.ConfirmFileParams) ([]string, error)) *MediaService_ConfirmUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MediaService
func (_mock *MediaService) DeleteFile(ctx context.Context, objectKeys []string) error {
	ret := _mock.Called(ctx, objectKeys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, objectKeys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MediaService_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MediaService_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKeys []string
func (_e *MediaService_Expecter) DeleteFile(ctx interface{}, objectKeys interface{}) *MediaService_DeleteFile_Call {
	return &MediaService_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, objectKeys)}
}

func (_c *MediaService_DeleteFile_Call) Run(run func(ctx context.Context, objectKeys []string)) *MediaService_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaService_DeleteFile_Call) Return(err error) *MediaService_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MediaService_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, objectKeys []string) error) *MediaService_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function for the type MediaService
func (_mock *MediaService) GetPresignedURL(ctx context.Context, input []domain.PresignedFileParams) ([]domain.PresignedFile, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 []domain.PresignedFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PresignedFileParams) ([]domain.PresignedFile, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.PresignedFileParams) []domain.PresignedFile); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PresignedFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []domain.PresignedFileParams) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MediaService_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type MediaService_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - input []domain.PresignedFileParams
func (_e *MediaService_Expecter) GetPresignedURL(ctx interface{}, input interface{}) *MediaService_GetPresignedURL_Call {
	return &MediaService_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", ctx, input)}
}

func (_c *MediaService_GetPresignedURL_Call) Run(run func(ctx context.Context, input []domain.PresignedFileParams)) *MediaService_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.PresignedFileParams
		if args[1] != nil {
			arg1 = args[1].([]domain.PresignedFileParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaService_GetPresignedURL_Call) Return(presignedFiles []domain.PresignedFile, err error) *MediaService_GetPresignedURL_Call {
	_c.Call.Return(presignedFiles, err)
	return _c
}

func (_c *MediaService_GetPresignedURL_Call) RunAndReturn(run func(ctx context.Context, input []domain.PresignedFileParams) ([]domain.PresignedFile, error)) *MediaService_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyMedia provides a mock function for the type MediaService
func (_mock *MediaService) VerifyMedia(ctx context.Context, objectKeys []string) error {
	ret := _mock.Called(ctx, objectKeys)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, objectKeys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MediaService_VerifyMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMedia'
type MediaService_VerifyMedia_Call struct {
	*mock.Call
}

// VerifyMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKeys []string
func (_e *MediaService_Expecter) VerifyMedia(ctx interface{}, objectKeys interface{}) *MediaService_VerifyMedia_Call {
	return &MediaService_VerifyMedia_Call{Call: _e.mock.On("VerifyMedia", ctx, objectKeys)}
}

func (_c *MediaService_VerifyMedia_Call) Run(run func(ctx context.Context, objectKeys []string)) *MediaService_VerifyMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MediaService_VerifyMedia_Call) Return(err error) *MediaService_VerifyMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MediaService_VerifyMedia_Call) RunAndReturn(run func(ctx context.Context, objectKeys []string) error) *MediaService_VerifyMedia_Call {
	_c.Call.Return(run)
	return _c
}
