// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain"
	"context"

	"github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenService creates a new instance of TokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenService {
	mock := &TokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenService is an autogenerated mock type for the TokenService type
type TokenService struct {
	mock.Mock
}

type TokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenService) EXPECT() *TokenService_Expecter {
	return &TokenService_Expecter{mock: &_m.Mock}
}

// CleanupDatabase provides a mock function for the type TokenService
func (_mock *TokenService) CleanupDatabase(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanupDatabase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenService_CleanupDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupDatabase'
type TokenService_CleanupDatabase_Call struct {
	*mock.Call
}

// CleanupDatabase is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TokenService_Expecter) CleanupDatabase(ctx interface{}) *TokenService_CleanupDatabase_Call {
	return &TokenService_CleanupDatabase_Call{Call: _e.mock.On("CleanupDatabase", ctx)}
}

func (_c *TokenService_CleanupDatabase_Call) Run(run func(ctx context.Context)) *TokenService_CleanupDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenService_CleanupDatabase_Call) Return(err error) *TokenService_CleanupDatabase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenService_CleanupDatabase_Call) RunAndReturn(run func(ctx context.Context) error) *TokenService_CleanupDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type TokenService
func (_mock *TokenService) CreateSession(ctx context.Context, userID int64, deviceID string) (domain.TokenInfo, error) {
	ret := _mock.Called(ctx, userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 domain.TokenInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (domain.TokenInfo, error)); ok {
		return returnFunc(ctx, userID, deviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) domain.TokenInfo); ok {
		r0 = returnFunc(ctx, userID, deviceID)
	} else {
		r0 = ret.Get(0).(domain.TokenInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, deviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type TokenService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - deviceID string
func (_e *TokenService_Expecter) CreateSession(ctx interface{}, userID interface{}, deviceID interface{}) *TokenService_CreateSession_Call {
	return &TokenService_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, userID, deviceID)}
}

func (_c *TokenService_CreateSession_Call) Run(run func(ctx context.Context, userID int64, deviceID string)) *TokenService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenService_CreateSession_Call) Return(tokenInfo domain.TokenInfo, err error) *TokenService_CreateSession_Call {
	_c.Call.Return(tokenInfo, err)
	return _c
}

func (_c *TokenService_CreateSession_Call) RunAndReturn(run func(ctx context.Context, userID int64, deviceID string) (domain.TokenInfo, error)) *TokenService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type TokenService
func (_mock *TokenService) Refresh(ctx context.Context, refreshToken string) (domain.TokenInfo, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 domain.TokenInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.TokenInfo, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.TokenInfo); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(domain.TokenInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type TokenService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *TokenService_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *TokenService_Refresh_Call {
	return &TokenService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *TokenService_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *TokenService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenService_Refresh_Call) Return(tokenInfo domain.TokenInfo, err error) *TokenService_Refresh_Call {
	_c.Call.Return(tokenInfo, err)
	return _c
}

func (_c *TokenService_Refresh_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (domain.TokenInfo, error)) *TokenService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserSessions provides a mock function for the type TokenService
func (_mock *TokenService) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserSessions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenService_RevokeAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserSessions'
type TokenService_RevokeAllUserSessions_Call struct {
	*mock.Call
}

// RevokeAllUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *TokenService_Expecter) RevokeAllUserSessions(ctx interface{}, userID interface{}) *TokenService_RevokeAllUserSessions_Call {
	return &TokenService_RevokeAllUserSessions_Call{Call: _e.mock.On("RevokeAllUserSessions", ctx, userID)}
}

func (_c *TokenService_RevokeAllUserSessions_Call) Run(run func(ctx context.Context, userID int64)) *TokenService_RevokeAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenService_RevokeAllUserSessions_Call) Return(err error) *TokenService_RevokeAllUserSessions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenService_RevokeAllUserSessions_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *TokenService_RevokeAllUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeDeviceSession provides a mock function for the type TokenService
func (_mock *TokenService) RevokeDeviceSession(ctx context.Context, userID int64, deviceID string) error {
	ret := _mock.Called(ctx, userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeDeviceSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, userID, deviceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenService_RevokeDeviceSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeDeviceSession'
type TokenService_RevokeDeviceSession_Call struct {
	*mock.Call
}

// RevokeDeviceSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - deviceID string
func (_e *TokenService_Expecter) RevokeDeviceSession(ctx interface{}, userID interface{}, deviceID interface{}) *TokenService_RevokeDeviceSession_Call {
	return &TokenService_RevokeDeviceSession_Call{Call: _e.mock.On("RevokeDeviceSession", ctx, userID, deviceID)}
}

func (_c *TokenService_RevokeDeviceSession_Call) Run(run func(ctx context.Context, userID int64, deviceID string)) *TokenService_RevokeDeviceSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenService_RevokeDeviceSession_Call) Return(err error) *TokenService_RevokeDeviceSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenService_RevokeDeviceSession_Call) RunAndReturn(run func(ctx context.Context, userID int64, deviceID string) error) *TokenService_RevokeDeviceSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSingle provides a mock function for the type TokenService
func (_mock *TokenService) RevokeSingle(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSingle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenService_RevokeSingle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSingle'
type TokenService_RevokeSingle_Call struct {
	*mock.Call
}

// RevokeSingle is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *TokenService_Expecter) RevokeSingle(ctx interface{}, refreshToken interface{}) *TokenService_RevokeSingle_Call {
	return &TokenService_RevokeSingle_Call{Call: _e.mock.On("RevokeSingle", ctx, refreshToken)}
}

func (_c *TokenService_RevokeSingle_Call) Run(run func(ctx context.Context, refreshToken string)) *TokenService_RevokeSingle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TokenService_RevokeSingle_Call) Return(err error) *TokenService_RevokeSingle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenService_RevokeSingle_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *TokenService_RevokeSingle_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type TokenService
func (_mock *TokenService) Validate(accessToken string) (*jwt.Token, error) {
	ret := _mock.Called(accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *jwt.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*jwt.Token, error)); ok {
		return returnFunc(accessToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *jwt.Token); ok {
		r0 = returnFunc(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(accessToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type TokenService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - accessToken string
func (_e *TokenService_Expecter) Validate(accessToken interface{}) *TokenService_Validate_Call {
	return &TokenService_Validate_Call{Call: _e.mock.On("Validate", accessToken)}
}

func (_c *TokenService_Validate_Call) Run(run func(accessToken string)) *TokenService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenService_Validate_Call) Return(token *jwt.Token, err error) *TokenService_Validate_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *TokenService_Validate_Call) RunAndReturn(run func(accessToken string) (*jwt.Token, error)) *TokenService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
