// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type UserService
func (_mock *UserService) ChangePassword(ctx context.Context, input domain.ChangePasswordParams) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ChangePasswordParams) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type UserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.ChangePasswordParams
func (_e *UserService_Expecter) ChangePassword(ctx interface{}, input interface{}) *UserService_ChangePassword_Call {
	return &UserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, input)}
}

func (_c *UserService_ChangePassword_Call) Run(run func(ctx context.Context, input domain.ChangePasswordParams)) *UserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ChangePasswordParams
		if args[1] != nil {
			arg1 = args[1].(domain.ChangePasswordParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_ChangePassword_Call) Return(err error) *UserService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, input domain.ChangePasswordParams) error) *UserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmImageUpload provides a mock function for the type UserService
func (_mock *UserService) ConfirmImageUpload(ctx context.Context, input domain.ConfirmFileParams) (string, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmImageUpload")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConfirmFileParams) (string, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ConfirmFileParams) string); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ConfirmFileParams) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_ConfirmImageUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmImageUpload'
type UserService_ConfirmImageUpload_Call struct {
	*mock.Call
}

// ConfirmImageUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.ConfirmFileParams
func (_e *UserService_Expecter) ConfirmImageUpload(ctx interface{}, input interface{}) *UserService_ConfirmImageUpload_Call {
	return &UserService_ConfirmImageUpload_Call{Call: _e.mock.On("ConfirmImageUpload", ctx, input)}
}

func (_c *UserService_ConfirmImageUpload_Call) Run(run func(ctx context.Context, input domain.ConfirmFileParams)) *UserService_ConfirmImageUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ConfirmFileParams
		if args[1] != nil {
			arg1 = args[1].(domain.ConfirmFileParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_ConfirmImageUpload_Call) Return(s string, err error) *UserService_ConfirmImageUpload_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserService_ConfirmImageUpload_Call) RunAndReturn(run func(ctx context.Context, input domain.ConfirmFileParams) (string, error)) *UserService_ConfirmImageUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type UserService
func (_mock *UserService) CreateUser(ctx context.Context, input domain.CreateUserParams) (domain.UserResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateUserParams) (domain.UserResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateUserParams) domain.UserResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.CreateUserParams
func (_e *UserService_Expecter) CreateUser(ctx interface{}, input interface{}) *UserService_CreateUser_Call {
	return &UserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, input)}
}

func (_c *UserService_CreateUser_Call) Run(run func(ctx context.Context, input domain.CreateUserParams)) *UserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(domain.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_CreateUser_Call) Return(userResponse domain.UserResponse, err error) *UserService_CreateUser_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *UserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, input domain.CreateUserParams) (domain.UserResponse, error)) *UserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type UserService
func (_mock *UserService) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserService_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserService_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserService_GetByEmail_Call {
	return &UserService_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserService_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserService_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_GetByEmail_Call) Return(user *domain.User, err error) *UserService_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *UserService_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type UserService
func (_mock *UserService) GetByID(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserService_Expecter) GetByID(ctx interface{}, id interface{}) *UserService_GetByID_Call {
	return &UserService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserService_GetByID_Call) Run(run func(ctx context.Context, id int64)) *UserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_GetByID_Call) Return(user *domain.User, err error) *UserService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *UserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type UserService
func (_mock *UserService) GetProfile(ctx context.Context, id int64) (domain.UserResponse, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 domain.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (domain.UserResponse, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) domain.UserResponse); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type UserService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserService_Expecter) GetProfile(ctx interface{}, id interface{}) *UserService_GetProfile_Call {
	return &UserService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, id)}
}

func (_c *UserService_GetProfile_Call) Run(run func(ctx context.Context, id int64)) *UserService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_GetProfile_Call) Return(userResponse domain.UserResponse, err error) *UserService_GetProfile_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *UserService_GetProfile_Call) RunAndReturn(run func(ctx context.Context, id int64) (domain.UserResponse, error)) *UserService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveMediaURLs provides a mock function for the type UserService
func (_mock *UserService) ResolveMediaURLs(res *domain.UserResponse) {
	_mock.Called(res)
	return
}

// UserService_ResolveMediaURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveMediaURLs'
type UserService_ResolveMediaURLs_Call struct {
	*mock.Call
}

// ResolveMediaURLs is a helper method to define mock.On call
//   - res *domain.UserResponse
func (_e *UserService_Expecter) ResolveMediaURLs(res interface{}) *UserService_ResolveMediaURLs_Call {
	return &UserService_ResolveMediaURLs_Call{Call: _e.mock.On("ResolveMediaURLs", res)}
}

func (_c *UserService_ResolveMediaURLs_Call) Run(run func(res *domain.UserResponse)) *UserService_ResolveMediaURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.UserResponse
		if args[0] != nil {
			arg0 = args[0].(*domain.UserResponse)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserService_ResolveMediaURLs_Call) Return() *UserService_ResolveMediaURLs_Call {
	_c.Call.Return()
	return _c
}

func (_c *UserService_ResolveMediaURLs_Call) RunAndReturn(run func(res *domain.UserResponse)) *UserService_ResolveMediaURLs_Call {
	_c.Run(run)
	return _c
}

// UpdatePassword provides a mock function for the type UserService
func (_mock *UserService) UpdatePassword(ctx context.Context, email string, passwordHashed string) error {
	ret := _mock.Called(ctx, email, passwordHashed)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, email, passwordHashed)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserService_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type UserService_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHashed string
func (_e *UserService_Expecter) UpdatePassword(ctx interface{}, email interface{}, passwordHashed interface{}) *UserService_UpdatePassword_Call {
	return &UserService_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, email, passwordHashed)}
}

func (_c *UserService_UpdatePassword_Call) Run(run func(ctx context.Context, email string, passwordHashed string)) *UserService_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserService_UpdatePassword_Call) Return(err error) *UserService_UpdatePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserService_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, email string, passwordHashed string) error) *UserService_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type UserService
func (_mock *UserService) UpdateProfile(ctx context.Context, input domain.UpdateProfileParams) (domain.UserResponse, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 domain.UserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UpdateProfileParams) (domain.UserResponse, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UpdateProfileParams) domain.UserResponse); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.UserResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UpdateProfileParams) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - input domain.UpdateProfileParams
func (_e *UserService_Expecter) UpdateProfile(ctx interface{}, input interface{}) *UserService_UpdateProfile_Call {
	return &UserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, input)}
}

func (_c *UserService_UpdateProfile_Call) Run(run func(ctx context.Context, input domain.UpdateProfileParams)) *UserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UpdateProfileParams
		if args[1] != nil {
			arg1 = args[1].(domain.UpdateProfileParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_UpdateProfile_Call) Return(userResponse domain.UserResponse, err error) *UserService_UpdateProfile_Call {
	_c.Call.Return(userResponse, err)
	return _c
}

func (_c *UserService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, input domain.UpdateProfileParams) (domain.UserResponse, error)) *UserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type UserService
func (_mock *UserService) VerifyEmail(ctx context.Context, email string) error {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserService_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type UserService_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserService_Expecter) VerifyEmail(ctx interface{}, email interface{}) *UserService_VerifyEmail_Call {
	return &UserService_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, email)}
}

func (_c *UserService_VerifyEmail_Call) Run(run func(ctx context.Context, email string)) *UserService_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserService_VerifyEmail_Call) Return(err error) *UserService_VerifyEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserService_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, email string) error) *UserService_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}
