// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUserSummaryFetcher creates a new instance of UserSummaryFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSummaryFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSummaryFetcher {
	mock := &UserSummaryFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserSummaryFetcher is an autogenerated mock type for the UserSummaryFetcher type
type UserSummaryFetcher struct {
	mock.Mock
}

type UserSummaryFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSummaryFetcher) EXPECT() *UserSummaryFetcher_Expecter {
	return &UserSummaryFetcher_Expecter{mock: &_m.Mock}
}

// GetSummary provides a mock function for the type UserSummaryFetcher
func (_mock *UserSummaryFetcher) GetSummary(ctx context.Context, id int64) (*domain.UserSummary, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *domain.UserSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.UserSummary, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.UserSummary); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserSummaryFetcher_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type UserSummaryFetcher_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserSummaryFetcher_Expecter) GetSummary(ctx interface{}, id interface{}) *UserSummaryFetcher_GetSummary_Call {
	return &UserSummaryFetcher_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, id)}
}

func (_c *UserSummaryFetcher_GetSummary_Call) Run(run func(ctx context.Context, id int64)) *UserSummaryFetcher_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSummaryFetcher_GetSummary_Call) Return(userSummary *domain.UserSummary, err error) *UserSummaryFetcher_GetSummary_Call {
	_c.Call.Return(userSummary, err)
	return _c
}

func (_c *UserSummaryFetcher_GetSummary_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.UserSummary, error)) *UserSummaryFetcher_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}
