// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFollowFetcher is an autogenerated mock type for the FollowFetcher type
type MockFollowFetcher struct {
	mock.Mock
}

type MockFollowFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFollowFetcher) EXPECT() *MockFollowFetcher_Expecter {
	return &MockFollowFetcher_Expecter{mock: &_m.Mock}
}

// GetFollowerIDs provides a mock function with given fields: ctx, userID
func (_m *MockFollowFetcher) GetFollowerIDs(ctx context.Context, userID int64) ([]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowerIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFollowFetcher_GetFollowerIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowerIDs'
type MockFollowFetcher_GetFollowerIDs_Call struct {
	*mock.Call
}

// GetFollowerIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockFollowFetcher_Expecter) GetFollowerIDs(ctx interface{}, userID interface{}) *MockFollowFetcher_GetFollowerIDs_Call {
	return &MockFollowFetcher_GetFollowerIDs_Call{Call: _e.mock.On("GetFollowerIDs", ctx, userID)}
}

func (_c *MockFollowFetcher_GetFollowerIDs_Call) Run(run func(ctx context.Context, userID int64)) *MockFollowFetcher_GetFollowerIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockFollowFetcher_GetFollowerIDs_Call) Return(_a0 []int64, _a1 error) *MockFollowFetcher_GetFollowerIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFollowFetcher_GetFollowerIDs_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *MockFollowFetcher_GetFollowerIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFollowFetcher creates a new instance of MockFollowFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFollowFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFollowFetcher {
	mock := &MockFollowFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
