// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	comment "air-social/internal/domain/comment"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Create(ctx context.Context, _a1 *comment.Comment) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *comment.Comment) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *comment.Comment
func (_e *MockRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, _a1 *comment.Comment)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*comment.Comment))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *comment.Comment) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) GetByID(ctx context.Context, id int64) (*comment.Comment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *comment.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*comment.Comment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *comment.Comment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*comment.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *comment.Comment, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*comment.Comment, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function with given fields: ctx, postID, params
func (_m *MockRepository) GetComments(ctx context.Context, postID int64, params comment.GetCursorParams) ([]comment.Comment, error) {
	ret := _m.Called(ctx, postID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []comment.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) ([]comment.Comment, error)); ok {
		return rf(ctx, postID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) []comment.Comment); ok {
		r0 = rf(ctx, postID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]comment.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, comment.GetCursorParams) error); ok {
		r1 = rf(ctx, postID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - params comment.GetCursorParams
func (_e *MockRepository_Expecter) GetComments(ctx interface{}, postID interface{}, params interface{}) *MockRepository_GetComments_Call {
	return &MockRepository_GetComments_Call{Call: _e.mock.On("GetComments", ctx, postID, params)}
}

func (_c *MockRepository_GetComments_Call) Run(run func(ctx context.Context, postID int64, params comment.GetCursorParams)) *MockRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(comment.GetCursorParams))
	})
	return _c
}

func (_c *MockRepository_GetComments_Call) Return(_a0 []comment.Comment, _a1 error) *MockRepository_GetComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetComments_Call) RunAndReturn(run func(context.Context, int64, comment.GetCursorParams) ([]comment.Comment, error)) *MockRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplies provides a mock function with given fields: ctx, parentID, params
func (_m *MockRepository) GetReplies(ctx context.Context, parentID int64, params comment.GetCursorParams) ([]comment.Comment, error) {
	ret := _m.Called(ctx, parentID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetReplies")
	}

	var r0 []comment.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) ([]comment.Comment, error)); ok {
		return rf(ctx, parentID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) []comment.Comment); ok {
		r0 = rf(ctx, parentID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]comment.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, comment.GetCursorParams) error); ok {
		r1 = rf(ctx, parentID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplies'
type MockRepository_GetReplies_Call struct {
	*mock.Call
}

// GetReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
//   - params comment.GetCursorParams
func (_e *MockRepository_Expecter) GetReplies(ctx interface{}, parentID interface{}, params interface{}) *MockRepository_GetReplies_Call {
	return &MockRepository_GetReplies_Call{Call: _e.mock.On("GetReplies", ctx, parentID, params)}
}

func (_c *MockRepository_GetReplies_Call) Run(run func(ctx context.Context, parentID int64, params comment.GetCursorParams)) *MockRepository_GetReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(comment.GetCursorParams))
	})
	return _c
}

func (_c *MockRepository_GetReplies_Call) Return(_a0 []comment.Comment, _a1 error) *MockRepository_GetReplies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetReplies_Call) RunAndReturn(run func(context.Context, int64, comment.GetCursorParams) ([]comment.Comment, error)) *MockRepository_GetReplies_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Update(ctx context.Context, _a1 *comment.Comment) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *comment.Comment) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *comment.Comment
func (_e *MockRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, _a1 *comment.Comment)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*comment.Comment))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, *comment.Comment) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
