// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	comment "air-social/internal/domain/comment"
	common "air-social/internal/domain/common"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CreateComment provides a mock function with given fields: ctx, params
func (_m *MockUseCase) CreateComment(ctx context.Context, params comment.CreateParams) (*comment.Comment, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 *comment.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, comment.CreateParams) (*comment.Comment, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, comment.CreateParams) *comment.Comment); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*comment.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, comment.CreateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockUseCase_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - params comment.CreateParams
func (_e *MockUseCase_Expecter) CreateComment(ctx interface{}, params interface{}) *MockUseCase_CreateComment_Call {
	return &MockUseCase_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, params)}
}

func (_c *MockUseCase_CreateComment_Call) Run(run func(ctx context.Context, params comment.CreateParams)) *MockUseCase_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(comment.CreateParams))
	})
	return _c
}

func (_c *MockUseCase_CreateComment_Call) Return(_a0 *comment.Comment, _a1 error) *MockUseCase_CreateComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_CreateComment_Call) RunAndReturn(run func(context.Context, comment.CreateParams) (*comment.Comment, error)) *MockUseCase_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function with given fields: ctx, commentID, userID
func (_m *MockUseCase) DeleteComment(ctx context.Context, commentID int64, userID int64) error {
	ret := _m.Called(ctx, commentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, commentID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUseCase_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockUseCase_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID int64
//   - userID int64
func (_e *MockUseCase_Expecter) DeleteComment(ctx interface{}, commentID interface{}, userID interface{}) *MockUseCase_DeleteComment_Call {
	return &MockUseCase_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, commentID, userID)}
}

func (_c *MockUseCase_DeleteComment_Call) Run(run func(ctx context.Context, commentID int64, userID int64)) *MockUseCase_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockUseCase_DeleteComment_Call) Return(_a0 error) *MockUseCase_DeleteComment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUseCase_DeleteComment_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockUseCase_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function with given fields: ctx, postID, params
func (_m *MockUseCase) GetComments(ctx context.Context, postID int64, params comment.GetCursorParams) (common.CursorPaginatedResult[comment.Comment, int64], error) {
	ret := _m.Called(ctx, postID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 common.CursorPaginatedResult[comment.Comment, int64]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) (common.CursorPaginatedResult[comment.Comment, int64], error)); ok {
		return rf(ctx, postID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) common.CursorPaginatedResult[comment.Comment, int64]); ok {
		r0 = rf(ctx, postID, params)
	} else {
		r0 = ret.Get(0).(common.CursorPaginatedResult[comment.Comment, int64])
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, comment.GetCursorParams) error); ok {
		r1 = rf(ctx, postID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockUseCase_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - params comment.GetCursorParams
func (_e *MockUseCase_Expecter) GetComments(ctx interface{}, postID interface{}, params interface{}) *MockUseCase_GetComments_Call {
	return &MockUseCase_GetComments_Call{Call: _e.mock.On("GetComments", ctx, postID, params)}
}

func (_c *MockUseCase_GetComments_Call) Run(run func(ctx context.Context, postID int64, params comment.GetCursorParams)) *MockUseCase_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(comment.GetCursorParams))
	})
	return _c
}

func (_c *MockUseCase_GetComments_Call) Return(_a0 common.CursorPaginatedResult[comment.Comment, int64], _a1 error) *MockUseCase_GetComments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetComments_Call) RunAndReturn(run func(context.Context, int64, comment.GetCursorParams) (common.CursorPaginatedResult[comment.Comment, int64], error)) *MockUseCase_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplies provides a mock function with given fields: ctx, parentID, params
func (_m *MockUseCase) GetReplies(ctx context.Context, parentID int64, params comment.GetCursorParams) (common.CursorPaginatedResult[comment.Comment, int64], error) {
	ret := _m.Called(ctx, parentID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetReplies")
	}

	var r0 common.CursorPaginatedResult[comment.Comment, int64]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) (common.CursorPaginatedResult[comment.Comment, int64], error)); ok {
		return rf(ctx, parentID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, comment.GetCursorParams) common.CursorPaginatedResult[comment.Comment, int64]); ok {
		r0 = rf(ctx, parentID, params)
	} else {
		r0 = ret.Get(0).(common.CursorPaginatedResult[comment.Comment, int64])
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, comment.GetCursorParams) error); ok {
		r1 = rf(ctx, parentID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GetReplies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplies'
type MockUseCase_GetReplies_Call struct {
	*mock.Call
}

// GetReplies is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID int64
//   - params comment.GetCursorParams
func (_e *MockUseCase_Expecter) GetReplies(ctx interface{}, parentID interface{}, params interface{}) *MockUseCase_GetReplies_Call {
	return &MockUseCase_GetReplies_Call{Call: _e.mock.On("GetReplies", ctx, parentID, params)}
}

func (_c *MockUseCase_GetReplies_Call) Run(run func(ctx context.Context, parentID int64, params comment.GetCursorParams)) *MockUseCase_GetReplies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(comment.GetCursorParams))
	})
	return _c
}

func (_c *MockUseCase_GetReplies_Call) Return(_a0 common.CursorPaginatedResult[comment.Comment, int64], _a1 error) *MockUseCase_GetReplies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GetReplies_Call) RunAndReturn(run func(context.Context, int64, comment.GetCursorParams) (common.CursorPaginatedResult[comment.Comment, int64], error)) *MockUseCase_GetReplies_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function with given fields: ctx, params
func (_m *MockUseCase) UpdateComment(ctx context.Context, params comment.UpdateParams) (*comment.Comment, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 *comment.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, comment.UpdateParams) (*comment.Comment, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, comment.UpdateParams) *comment.Comment); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*comment.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, comment.UpdateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockUseCase_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - params comment.UpdateParams
func (_e *MockUseCase_Expecter) UpdateComment(ctx interface{}, params interface{}) *MockUseCase_UpdateComment_Call {
	return &MockUseCase_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, params)}
}

func (_c *MockUseCase_UpdateComment_Call) Run(run func(ctx context.Context, params comment.UpdateParams)) *MockUseCase_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(comment.UpdateParams))
	})
	return _c
}

func (_c *MockUseCase_UpdateComment_Call) Return(_a0 *comment.Comment, _a1 error) *MockUseCase_UpdateComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_UpdateComment_Call) RunAndReturn(run func(context.Context, comment.UpdateParams) (*comment.Comment, error)) *MockUseCase_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
