# .mockery.yaml
structname: "{{.InterfaceName}}"
pkgname: "mocks"
filename: "{{.InterfaceName | snakecase}}.go"

dir: "internal/mocks"
formatter: goimports
inpackage: false
force-file-write: true

packages:
  air-social/internal/domain:
    config:
      recursive: true
      all: true
  
  air-social/internal/service:
    config:
      recursive: true
      all: true