inpackage: false
force-file-write: true
formatter: goimports

packages:
  air-social/internal:
    config:
      recursive: true
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      filename: "{{.InterfaceName | snakecase}}_mock.go"
      structname: "Mock{{.InterfaceName}}"
      pkgname: "mocks"
