services:
  app:
    profiles: ["disable_for_debug"]

  nginx:
    ports:
      - "80:80"
    environment:
      - NGINX_TIMEOUT=3600s
      - SERVER_READ_TIMEOUT=3600s  
      - SERVER_WRITE_TIMEOUT=3600s
    extra_hosts:
      - "app:host-gateway"

  db:
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq:
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  minio:
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
