// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	chat "air-social/internal/domain/chat"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConversationRepository is an autogenerated mock type for the ConversationRepository type
type MockConversationRepository struct {
	mock.Mock
}

type MockConversationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationRepository) EXPECT() *MockConversationRepository_Expecter {
	return &MockConversationRepository_Expecter{mock: &_m.Mock}
}

// AddParticipant provides a mock function with given fields: ctx, convID, p
func (_m *MockConversationRepository) AddParticipant(ctx context.Context, convID string, p chat.Participant) error {
	ret := _m.Called(ctx, convID, p)

	if len(ret) == 0 {
		panic("no return value specified for AddParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, chat.Participant) error); ok {
		r0 = rf(ctx, convID, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_AddParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddParticipant'
type MockConversationRepository_AddParticipant_Call struct {
	*mock.Call
}

// AddParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - p chat.Participant
func (_e *MockConversationRepository_Expecter) AddParticipant(ctx interface{}, convID interface{}, p interface{}) *MockConversationRepository_AddParticipant_Call {
	return &MockConversationRepository_AddParticipant_Call{Call: _e.mock.On("AddParticipant", ctx, convID, p)}
}

func (_c *MockConversationRepository_AddParticipant_Call) Run(run func(ctx context.Context, convID string, p chat.Participant)) *MockConversationRepository_AddParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(chat.Participant))
	})
	return _c
}

func (_c *MockConversationRepository_AddParticipant_Call) Return(_a0 error) *MockConversationRepository_AddParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_AddParticipant_Call) RunAndReturn(run func(context.Context, string, chat.Participant) error) *MockConversationRepository_AddParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, conv
func (_m *MockConversationRepository) Create(ctx context.Context, conv *chat.Conversation) error {
	ret := _m.Called(ctx, conv)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.Conversation) error); ok {
		r0 = rf(ctx, conv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConversationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - conv *chat.Conversation
func (_e *MockConversationRepository_Expecter) Create(ctx interface{}, conv interface{}) *MockConversationRepository_Create_Call {
	return &MockConversationRepository_Create_Call{Call: _e.mock.On("Create", ctx, conv)}
}

func (_c *MockConversationRepository_Create_Call) Run(run func(ctx context.Context, conv *chat.Conversation)) *MockConversationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*chat.Conversation))
	})
	return _c
}

func (_c *MockConversationRepository_Create_Call) Return(_a0 error) *MockConversationRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_Create_Call) RunAndReturn(run func(context.Context, *chat.Conversation) error) *MockConversationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByClientConvID provides a mock function with given fields: ctx, clientConvID
func (_m *MockConversationRepository) GetByClientConvID(ctx context.Context, clientConvID string) (*chat.Conversation, error) {
	ret := _m.Called(ctx, clientConvID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientConvID")
	}

	var r0 *chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*chat.Conversation, error)); ok {
		return rf(ctx, clientConvID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *chat.Conversation); ok {
		r0 = rf(ctx, clientConvID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clientConvID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_GetByClientConvID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClientConvID'
type MockConversationRepository_GetByClientConvID_Call struct {
	*mock.Call
}

// GetByClientConvID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientConvID string
func (_e *MockConversationRepository_Expecter) GetByClientConvID(ctx interface{}, clientConvID interface{}) *MockConversationRepository_GetByClientConvID_Call {
	return &MockConversationRepository_GetByClientConvID_Call{Call: _e.mock.On("GetByClientConvID", ctx, clientConvID)}
}

func (_c *MockConversationRepository_GetByClientConvID_Call) Run(run func(ctx context.Context, clientConvID string)) *MockConversationRepository_GetByClientConvID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConversationRepository_GetByClientConvID_Call) Return(_a0 *chat.Conversation, _a1 error) *MockConversationRepository_GetByClientConvID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_GetByClientConvID_Call) RunAndReturn(run func(context.Context, string) (*chat.Conversation, error)) *MockConversationRepository_GetByClientConvID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockConversationRepository) GetByID(ctx context.Context, id string) (*chat.Conversation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*chat.Conversation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *chat.Conversation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockConversationRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockConversationRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockConversationRepository_GetByID_Call {
	return &MockConversationRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockConversationRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockConversationRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockConversationRepository_GetByID_Call) Return(_a0 *chat.Conversation, _a1 error) *MockConversationRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*chat.Conversation, error)) *MockConversationRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDirect provides a mock function with given fields: ctx, userAID, userBID
func (_m *MockConversationRepository) GetDirect(ctx context.Context, userAID int64, userBID int64) (*chat.Conversation, error) {
	ret := _m.Called(ctx, userAID, userBID)

	if len(ret) == 0 {
		panic("no return value specified for GetDirect")
	}

	var r0 *chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*chat.Conversation, error)); ok {
		return rf(ctx, userAID, userBID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *chat.Conversation); ok {
		r0 = rf(ctx, userAID, userBID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userAID, userBID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_GetDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDirect'
type MockConversationRepository_GetDirect_Call struct {
	*mock.Call
}

// GetDirect is a helper method to define mock.On call
//   - ctx context.Context
//   - userAID int64
//   - userBID int64
func (_e *MockConversationRepository_Expecter) GetDirect(ctx interface{}, userAID interface{}, userBID interface{}) *MockConversationRepository_GetDirect_Call {
	return &MockConversationRepository_GetDirect_Call{Call: _e.mock.On("GetDirect", ctx, userAID, userBID)}
}

func (_c *MockConversationRepository_GetDirect_Call) Run(run func(ctx context.Context, userAID int64, userBID int64)) *MockConversationRepository_GetDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockConversationRepository_GetDirect_Call) Return(_a0 *chat.Conversation, _a1 error) *MockConversationRepository_GetDirect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_GetDirect_Call) RunAndReturn(run func(context.Context, int64, int64) (*chat.Conversation, error)) *MockConversationRepository_GetDirect_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx, params
func (_m *MockConversationRepository) GetList(ctx context.Context, params chat.GetConversationsParams) ([]chat.Conversation, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []chat.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.GetConversationsParams) ([]chat.Conversation, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.GetConversationsParams) []chat.Conversation); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chat.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.GetConversationsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConversationRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockConversationRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - params chat.GetConversationsParams
func (_e *MockConversationRepository_Expecter) GetList(ctx interface{}, params interface{}) *MockConversationRepository_GetList_Call {
	return &MockConversationRepository_GetList_Call{Call: _e.mock.On("GetList", ctx, params)}
}

func (_c *MockConversationRepository_GetList_Call) Run(run func(ctx context.Context, params chat.GetConversationsParams)) *MockConversationRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(chat.GetConversationsParams))
	})
	return _c
}

func (_c *MockConversationRepository_GetList_Call) Return(_a0 []chat.Conversation, _a1 error) *MockConversationRepository_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConversationRepository_GetList_Call) RunAndReturn(run func(context.Context, chat.GetConversationsParams) ([]chat.Conversation, error)) *MockConversationRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParticipant provides a mock function with given fields: ctx, convID, userID
func (_m *MockConversationRepository) RemoveParticipant(ctx context.Context, convID string, userID int64) error {
	ret := _m.Called(ctx, convID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveParticipant")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, convID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_RemoveParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParticipant'
type MockConversationRepository_RemoveParticipant_Call struct {
	*mock.Call
}

// RemoveParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - userID int64
func (_e *MockConversationRepository_Expecter) RemoveParticipant(ctx interface{}, convID interface{}, userID interface{}) *MockConversationRepository_RemoveParticipant_Call {
	return &MockConversationRepository_RemoveParticipant_Call{Call: _e.mock.On("RemoveParticipant", ctx, convID, userID)}
}

func (_c *MockConversationRepository_RemoveParticipant_Call) Run(run func(ctx context.Context, convID string, userID int64)) *MockConversationRepository_RemoveParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *MockConversationRepository_RemoveParticipant_Call) Return(_a0 error) *MockConversationRepository_RemoveParticipant_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_RemoveParticipant_Call) RunAndReturn(run func(context.Context, string, int64) error) *MockConversationRepository_RemoveParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function with given fields: ctx, convID, lastMsgID
func (_m *MockConversationRepository) Touch(ctx context.Context, convID string, lastMsgID string) error {
	ret := _m.Called(ctx, convID, lastMsgID)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, convID, lastMsgID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type MockConversationRepository_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - lastMsgID string
func (_e *MockConversationRepository_Expecter) Touch(ctx interface{}, convID interface{}, lastMsgID interface{}) *MockConversationRepository_Touch_Call {
	return &MockConversationRepository_Touch_Call{Call: _e.mock.On("Touch", ctx, convID, lastMsgID)}
}

func (_c *MockConversationRepository_Touch_Call) Run(run func(ctx context.Context, convID string, lastMsgID string)) *MockConversationRepository_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockConversationRepository_Touch_Call) Return(_a0 error) *MockConversationRepository_Touch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_Touch_Call) RunAndReturn(run func(context.Context, string, string) error) *MockConversationRepository_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroupInfo provides a mock function with given fields: ctx, convID, name, avatarKey
func (_m *MockConversationRepository) UpdateGroupInfo(ctx context.Context, convID string, name *string, avatarKey *string) error {
	ret := _m.Called(ctx, convID, name, avatarKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroupInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *string, *string) error); ok {
		r0 = rf(ctx, convID, name, avatarKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_UpdateGroupInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroupInfo'
type MockConversationRepository_UpdateGroupInfo_Call struct {
	*mock.Call
}

// UpdateGroupInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - name *string
//   - avatarKey *string
func (_e *MockConversationRepository_Expecter) UpdateGroupInfo(ctx interface{}, convID interface{}, name interface{}, avatarKey interface{}) *MockConversationRepository_UpdateGroupInfo_Call {
	return &MockConversationRepository_UpdateGroupInfo_Call{Call: _e.mock.On("UpdateGroupInfo", ctx, convID, name, avatarKey)}
}

func (_c *MockConversationRepository_UpdateGroupInfo_Call) Run(run func(ctx context.Context, convID string, name *string, avatarKey *string)) *MockConversationRepository_UpdateGroupInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*string), args[3].(*string))
	})
	return _c
}

func (_c *MockConversationRepository_UpdateGroupInfo_Call) Return(_a0 error) *MockConversationRepository_UpdateGroupInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_UpdateGroupInfo_Call) RunAndReturn(run func(context.Context, string, *string, *string) error) *MockConversationRepository_UpdateGroupInfo_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLastRead provides a mock function with given fields: ctx, convID, userID, messageID
func (_m *MockConversationRepository) UpdateLastRead(ctx context.Context, convID string, userID int64, messageID string) error {
	ret := _m.Called(ctx, convID, userID, messageID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLastRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, string) error); ok {
		r0 = rf(ctx, convID, userID, messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_UpdateLastRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLastRead'
type MockConversationRepository_UpdateLastRead_Call struct {
	*mock.Call
}

// UpdateLastRead is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - userID int64
//   - messageID string
func (_e *MockConversationRepository_Expecter) UpdateLastRead(ctx interface{}, convID interface{}, userID interface{}, messageID interface{}) *MockConversationRepository_UpdateLastRead_Call {
	return &MockConversationRepository_UpdateLastRead_Call{Call: _e.mock.On("UpdateLastRead", ctx, convID, userID, messageID)}
}

func (_c *MockConversationRepository_UpdateLastRead_Call) Run(run func(ctx context.Context, convID string, userID int64, messageID string)) *MockConversationRepository_UpdateLastRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(string))
	})
	return _c
}

func (_c *MockConversationRepository_UpdateLastRead_Call) Return(_a0 error) *MockConversationRepository_UpdateLastRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_UpdateLastRead_Call) RunAndReturn(run func(context.Context, string, int64, string) error) *MockConversationRepository_UpdateLastRead_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParticipantRole provides a mock function with given fields: ctx, convID, userID, role
func (_m *MockConversationRepository) UpdateParticipantRole(ctx context.Context, convID string, userID int64, role chat.ParticipantRole) error {
	ret := _m.Called(ctx, convID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParticipantRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, chat.ParticipantRole) error); ok {
		r0 = rf(ctx, convID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_UpdateParticipantRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParticipantRole'
type MockConversationRepository_UpdateParticipantRole_Call struct {
	*mock.Call
}

// UpdateParticipantRole is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - userID int64
//   - role chat.ParticipantRole
func (_e *MockConversationRepository_Expecter) UpdateParticipantRole(ctx interface{}, convID interface{}, userID interface{}, role interface{}) *MockConversationRepository_UpdateParticipantRole_Call {
	return &MockConversationRepository_UpdateParticipantRole_Call{Call: _e.mock.On("UpdateParticipantRole", ctx, convID, userID, role)}
}

func (_c *MockConversationRepository_UpdateParticipantRole_Call) Run(run func(ctx context.Context, convID string, userID int64, role chat.ParticipantRole)) *MockConversationRepository_UpdateParticipantRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(chat.ParticipantRole))
	})
	return _c
}

func (_c *MockConversationRepository_UpdateParticipantRole_Call) Return(_a0 error) *MockConversationRepository_UpdateParticipantRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_UpdateParticipantRole_Call) RunAndReturn(run func(context.Context, string, int64, chat.ParticipantRole) error) *MockConversationRepository_UpdateParticipantRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParticipantState provides a mock function with given fields: ctx, convID, userID, state
func (_m *MockConversationRepository) UpdateParticipantState(ctx context.Context, convID string, userID int64, state chat.ParticipantState) error {
	ret := _m.Called(ctx, convID, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParticipantState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, chat.ParticipantState) error); ok {
		r0 = rf(ctx, convID, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConversationRepository_UpdateParticipantState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParticipantState'
type MockConversationRepository_UpdateParticipantState_Call struct {
	*mock.Call
}

// UpdateParticipantState is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - userID int64
//   - state chat.ParticipantState
func (_e *MockConversationRepository_Expecter) UpdateParticipantState(ctx interface{}, convID interface{}, userID interface{}, state interface{}) *MockConversationRepository_UpdateParticipantState_Call {
	return &MockConversationRepository_UpdateParticipantState_Call{Call: _e.mock.On("UpdateParticipantState", ctx, convID, userID, state)}
}

func (_c *MockConversationRepository_UpdateParticipantState_Call) Run(run func(ctx context.Context, convID string, userID int64, state chat.ParticipantState)) *MockConversationRepository_UpdateParticipantState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(chat.ParticipantState))
	})
	return _c
}

func (_c *MockConversationRepository_UpdateParticipantState_Call) Return(_a0 error) *MockConversationRepository_UpdateParticipantState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConversationRepository_UpdateParticipantState_Call) RunAndReturn(run func(context.Context, string, int64, chat.ParticipantState) error) *MockConversationRepository_UpdateParticipantState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConversationRepository creates a new instance of MockConversationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationRepository {
	mock := &MockConversationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
