// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/chat"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockConversationWriter creates a new instance of MockConversationWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversationWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversationWriter {
	mock := &MockConversationWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConversationWriter is an autogenerated mock type for the ConversationWriter type
type MockConversationWriter struct {
	mock.Mock
}

type MockConversationWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversationWriter) EXPECT() *MockConversationWriter_Expecter {
	return &MockConversationWriter_Expecter{mock: &_m.Mock}
}

// CreateGroup provides a mock function for the type MockConversationWriter
func (_mock *MockConversationWriter) CreateGroup(ctx context.Context, params chat.CreateGroupParams) (*chat.Conversation, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 *chat.Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.CreateGroupParams) (*chat.Conversation, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.CreateGroupParams) *chat.Conversation); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, chat.CreateGroupParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationWriter_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockConversationWriter_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - params chat.CreateGroupParams
func (_e *MockConversationWriter_Expecter) CreateGroup(ctx interface{}, params interface{}) *MockConversationWriter_CreateGroup_Call {
	return &MockConversationWriter_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, params)}
}

func (_c *MockConversationWriter_CreateGroup_Call) Run(run func(ctx context.Context, params chat.CreateGroupParams)) *MockConversationWriter_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chat.CreateGroupParams
		if args[1] != nil {
			arg1 = args[1].(chat.CreateGroupParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationWriter_CreateGroup_Call) Return(conversation *chat.Conversation, err error) *MockConversationWriter_CreateGroup_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockConversationWriter_CreateGroup_Call) RunAndReturn(run func(ctx context.Context, params chat.CreateGroupParams) (*chat.Conversation, error)) *MockConversationWriter_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrGetDirect provides a mock function for the type MockConversationWriter
func (_mock *MockConversationWriter) CreateOrGetDirect(ctx context.Context, senderID int64, recipientID int64) (*chat.Conversation, error) {
	ret := _mock.Called(ctx, senderID, recipientID)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrGetDirect")
	}

	var r0 *chat.Conversation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*chat.Conversation, error)); ok {
		return returnFunc(ctx, senderID, recipientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *chat.Conversation); ok {
		r0 = returnFunc(ctx, senderID, recipientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Conversation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, senderID, recipientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversationWriter_CreateOrGetDirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrGetDirect'
type MockConversationWriter_CreateOrGetDirect_Call struct {
	*mock.Call
}

// CreateOrGetDirect is a helper method to define mock.On call
//   - ctx context.Context
//   - senderID int64
//   - recipientID int64
func (_e *MockConversationWriter_Expecter) CreateOrGetDirect(ctx interface{}, senderID interface{}, recipientID interface{}) *MockConversationWriter_CreateOrGetDirect_Call {
	return &MockConversationWriter_CreateOrGetDirect_Call{Call: _e.mock.On("CreateOrGetDirect", ctx, senderID, recipientID)}
}

func (_c *MockConversationWriter_CreateOrGetDirect_Call) Run(run func(ctx context.Context, senderID int64, recipientID int64)) *MockConversationWriter_CreateOrGetDirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConversationWriter_CreateOrGetDirect_Call) Return(conversation *chat.Conversation, err error) *MockConversationWriter_CreateOrGetDirect_Call {
	_c.Call.Return(conversation, err)
	return _c
}

func (_c *MockConversationWriter_CreateOrGetDirect_Call) RunAndReturn(run func(ctx context.Context, senderID int64, recipientID int64) (*chat.Conversation, error)) *MockConversationWriter_CreateOrGetDirect_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroup provides a mock function for the type MockConversationWriter
func (_mock *MockConversationWriter) UpdateGroup(ctx context.Context, params chat.UpdateGroupParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.UpdateGroupParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConversationWriter_UpdateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroup'
type MockConversationWriter_UpdateGroup_Call struct {
	*mock.Call
}

// UpdateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - params chat.UpdateGroupParams
func (_e *MockConversationWriter_Expecter) UpdateGroup(ctx interface{}, params interface{}) *MockConversationWriter_UpdateGroup_Call {
	return &MockConversationWriter_UpdateGroup_Call{Call: _e.mock.On("UpdateGroup", ctx, params)}
}

func (_c *MockConversationWriter_UpdateGroup_Call) Run(run func(ctx context.Context, params chat.UpdateGroupParams)) *MockConversationWriter_UpdateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chat.UpdateGroupParams
		if args[1] != nil {
			arg1 = args[1].(chat.UpdateGroupParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversationWriter_UpdateGroup_Call) Return(err error) *MockConversationWriter_UpdateGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConversationWriter_UpdateGroup_Call) RunAndReturn(run func(ctx context.Context, params chat.UpdateGroupParams) error) *MockConversationWriter_UpdateGroup_Call {
	_c.Call.Return(run)
	return _c
}
