// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/chat"
	"air-social/internal/domain/common"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessenger creates a new instance of MockMessenger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessenger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessenger {
	mock := &MockMessenger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessenger is an autogenerated mock type for the Messenger type
type MockMessenger struct {
	mock.Mock
}

type MockMessenger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessenger) EXPECT() *MockMessenger_Expecter {
	return &MockMessenger_Expecter{mock: &_m.Mock}
}

// AddReaction provides a mock function for the type MockMessenger
func (_mock *MockMessenger) AddReaction(ctx context.Context, msgID string, userID int64, reaction chat.ReactionType) error {
	ret := _mock.Called(ctx, msgID, userID, reaction)

	if len(ret) == 0 {
		panic("no return value specified for AddReaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, chat.ReactionType) error); ok {
		r0 = returnFunc(ctx, msgID, userID, reaction)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_AddReaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddReaction'
type MockMessenger_AddReaction_Call struct {
	*mock.Call
}

// AddReaction is a helper method to define mock.On call
//   - ctx context.Context
//   - msgID string
//   - userID int64
//   - reaction chat.ReactionType
func (_e *MockMessenger_Expecter) AddReaction(ctx interface{}, msgID interface{}, userID interface{}, reaction interface{}) *MockMessenger_AddReaction_Call {
	return &MockMessenger_AddReaction_Call{Call: _e.mock.On("AddReaction", ctx, msgID, userID, reaction)}
}

func (_c *MockMessenger_AddReaction_Call) Run(run func(ctx context.Context, msgID string, userID int64, reaction chat.ReactionType)) *MockMessenger_AddReaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 chat.ReactionType
		if args[3] != nil {
			arg3 = args[3].(chat.ReactionType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMessenger_AddReaction_Call) Return(err error) *MockMessenger_AddReaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_AddReaction_Call) RunAndReturn(run func(ctx context.Context, msgID string, userID int64, reaction chat.ReactionType) error) *MockMessenger_AddReaction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type MockMessenger
func (_mock *MockMessenger) DeleteMessage(ctx context.Context, msgID string, userID int64) error {
	ret := _mock.Called(ctx, msgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, msgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockMessenger_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msgID string
//   - userID int64
func (_e *MockMessenger_Expecter) DeleteMessage(ctx interface{}, msgID interface{}, userID interface{}) *MockMessenger_DeleteMessage_Call {
	return &MockMessenger_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, msgID, userID)}
}

func (_c *MockMessenger_DeleteMessage_Call) Run(run func(ctx context.Context, msgID string, userID int64)) *MockMessenger_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessenger_DeleteMessage_Call) Return(err error) *MockMessenger_DeleteMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, msgID string, userID int64) error) *MockMessenger_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessage provides a mock function for the type MockMessenger
func (_mock *MockMessenger) EditMessage(ctx context.Context, params chat.EditMessageParams) (*chat.Message, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for EditMessage")
	}

	var r0 *chat.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.EditMessageParams) (*chat.Message, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.EditMessageParams) *chat.Message); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, chat.EditMessageParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessenger_EditMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessage'
type MockMessenger_EditMessage_Call struct {
	*mock.Call
}

// EditMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params chat.EditMessageParams
func (_e *MockMessenger_Expecter) EditMessage(ctx interface{}, params interface{}) *MockMessenger_EditMessage_Call {
	return &MockMessenger_EditMessage_Call{Call: _e.mock.On("EditMessage", ctx, params)}
}

func (_c *MockMessenger_EditMessage_Call) Run(run func(ctx context.Context, params chat.EditMessageParams)) *MockMessenger_EditMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chat.EditMessageParams
		if args[1] != nil {
			arg1 = args[1].(chat.EditMessageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessenger_EditMessage_Call) Return(message *chat.Message, err error) *MockMessenger_EditMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessenger_EditMessage_Call) RunAndReturn(run func(ctx context.Context, params chat.EditMessageParams) (*chat.Message, error)) *MockMessenger_EditMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function for the type MockMessenger
func (_mock *MockMessenger) GetMessages(ctx context.Context, params chat.GetMessagesParams) (common.CursorPaginatedResult[chat.Message, string], error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 common.CursorPaginatedResult[chat.Message, string]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.GetMessagesParams) (common.CursorPaginatedResult[chat.Message, string], error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.GetMessagesParams) common.CursorPaginatedResult[chat.Message, string]); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(common.CursorPaginatedResult[chat.Message, string])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, chat.GetMessagesParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessenger_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockMessenger_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - params chat.GetMessagesParams
func (_e *MockMessenger_Expecter) GetMessages(ctx interface{}, params interface{}) *MockMessenger_GetMessages_Call {
	return &MockMessenger_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, params)}
}

func (_c *MockMessenger_GetMessages_Call) Run(run func(ctx context.Context, params chat.GetMessagesParams)) *MockMessenger_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chat.GetMessagesParams
		if args[1] != nil {
			arg1 = args[1].(chat.GetMessagesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessenger_GetMessages_Call) Return(cursorPaginatedResult common.CursorPaginatedResult[chat.Message, string], err error) *MockMessenger_GetMessages_Call {
	_c.Call.Return(cursorPaginatedResult, err)
	return _c
}

func (_c *MockMessenger_GetMessages_Call) RunAndReturn(run func(ctx context.Context, params chat.GetMessagesParams) (common.CursorPaginatedResult[chat.Message, string], error)) *MockMessenger_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockMessenger
func (_mock *MockMessenger) MarkRead(ctx context.Context, convID string, userID int64, lastReadMsgID string) error {
	ret := _mock.Called(ctx, convID, userID, lastReadMsgID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, string) error); ok {
		r0 = returnFunc(ctx, convID, userID, lastReadMsgID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockMessenger_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - convID string
//   - userID int64
//   - lastReadMsgID string
func (_e *MockMessenger_Expecter) MarkRead(ctx interface{}, convID interface{}, userID interface{}, lastReadMsgID interface{}) *MockMessenger_MarkRead_Call {
	return &MockMessenger_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, convID, userID, lastReadMsgID)}
}

func (_c *MockMessenger_MarkRead_Call) Run(run func(ctx context.Context, convID string, userID int64, lastReadMsgID string)) *MockMessenger_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMessenger_MarkRead_Call) Return(err error) *MockMessenger_MarkRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_MarkRead_Call) RunAndReturn(run func(ctx context.Context, convID string, userID int64, lastReadMsgID string) error) *MockMessenger_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveReaction provides a mock function for the type MockMessenger
func (_mock *MockMessenger) RemoveReaction(ctx context.Context, msgID string, userID int64) error {
	ret := _mock.Called(ctx, msgID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveReaction")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = returnFunc(ctx, msgID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessenger_RemoveReaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveReaction'
type MockMessenger_RemoveReaction_Call struct {
	*mock.Call
}

// RemoveReaction is a helper method to define mock.On call
//   - ctx context.Context
//   - msgID string
//   - userID int64
func (_e *MockMessenger_Expecter) RemoveReaction(ctx interface{}, msgID interface{}, userID interface{}) *MockMessenger_RemoveReaction_Call {
	return &MockMessenger_RemoveReaction_Call{Call: _e.mock.On("RemoveReaction", ctx, msgID, userID)}
}

func (_c *MockMessenger_RemoveReaction_Call) Run(run func(ctx context.Context, msgID string, userID int64)) *MockMessenger_RemoveReaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessenger_RemoveReaction_Call) Return(err error) *MockMessenger_RemoveReaction_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessenger_RemoveReaction_Call) RunAndReturn(run func(ctx context.Context, msgID string, userID int64) error) *MockMessenger_RemoveReaction_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type MockMessenger
func (_mock *MockMessenger) SendMessage(ctx context.Context, params chat.SendMessageParams) (*chat.Message, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *chat.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams) (*chat.Message, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, chat.SendMessageParams) *chat.Message); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, chat.SendMessageParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessenger_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessenger_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - params chat.SendMessageParams
func (_e *MockMessenger_Expecter) SendMessage(ctx interface{}, params interface{}) *MockMessenger_SendMessage_Call {
	return &MockMessenger_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, params)}
}

func (_c *MockMessenger_SendMessage_Call) Run(run func(ctx context.Context, params chat.SendMessageParams)) *MockMessenger_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chat.SendMessageParams
		if args[1] != nil {
			arg1 = args[1].(chat.SendMessageParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessenger_SendMessage_Call) Return(message *chat.Message, err error) *MockMessenger_SendMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessenger_SendMessage_Call) RunAndReturn(run func(ctx context.Context, params chat.SendMessageParams) (*chat.Message, error)) *MockMessenger_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}
