// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUnreadStore creates a new instance of MockUnreadStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnreadStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnreadStore {
	mock := &MockUnreadStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnreadStore is an autogenerated mock type for the UnreadStore type
type MockUnreadStore struct {
	mock.Mock
}

type MockUnreadStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnreadStore) EXPECT() *MockUnreadStore_Expecter {
	return &MockUnreadStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockUnreadStore
func (_mock *MockUnreadStore) Get(ctx context.Context, userID int64, convID string) (int64, error) {
	ret := _mock.Called(ctx, userID, convID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) (int64, error)); ok {
		return returnFunc(ctx, userID, convID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) int64); ok {
		r0 = returnFunc(ctx, userID, convID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = returnFunc(ctx, userID, convID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUnreadStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUnreadStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - convID string
func (_e *MockUnreadStore_Expecter) Get(ctx interface{}, userID interface{}, convID interface{}) *MockUnreadStore_Get_Call {
	return &MockUnreadStore_Get_Call{Call: _e.mock.On("Get", ctx, userID, convID)}
}

func (_c *MockUnreadStore_Get_Call) Run(run func(ctx context.Context, userID int64, convID string)) *MockUnreadStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUnreadStore_Get_Call) Return(n int64, err error) *MockUnreadStore_Get_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUnreadStore_Get_Call) RunAndReturn(run func(ctx context.Context, userID int64, convID string) (int64, error)) *MockUnreadStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockUnreadStore
func (_mock *MockUnreadStore) GetAll(ctx context.Context, userID int64) (map[string]int64, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (map[string]int64, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) map[string]int64); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUnreadStore_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockUnreadStore_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockUnreadStore_Expecter) GetAll(ctx interface{}, userID interface{}) *MockUnreadStore_GetAll_Call {
	return &MockUnreadStore_GetAll_Call{Call: _e.mock.On("GetAll", ctx, userID)}
}

func (_c *MockUnreadStore_GetAll_Call) Run(run func(ctx context.Context, userID int64)) *MockUnreadStore_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUnreadStore_GetAll_Call) Return(stringToInt64 map[string]int64, err error) *MockUnreadStore_GetAll_Call {
	_c.Call.Return(stringToInt64, err)
	return _c
}

func (_c *MockUnreadStore_GetAll_Call) RunAndReturn(run func(ctx context.Context, userID int64) (map[string]int64, error)) *MockUnreadStore_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type MockUnreadStore
func (_mock *MockUnreadStore) Increment(ctx context.Context, userID int64, convID string) error {
	ret := _mock.Called(ctx, userID, convID)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, userID, convID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnreadStore_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockUnreadStore_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - convID string
func (_e *MockUnreadStore_Expecter) Increment(ctx interface{}, userID interface{}, convID interface{}) *MockUnreadStore_Increment_Call {
	return &MockUnreadStore_Increment_Call{Call: _e.mock.On("Increment", ctx, userID, convID)}
}

func (_c *MockUnreadStore_Increment_Call) Run(run func(ctx context.Context, userID int64, convID string)) *MockUnreadStore_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUnreadStore_Increment_Call) Return(err error) *MockUnreadStore_Increment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnreadStore_Increment_Call) RunAndReturn(run func(ctx context.Context, userID int64, convID string) error) *MockUnreadStore_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockUnreadStore
func (_mock *MockUnreadStore) Reset(ctx context.Context, userID int64, convID string) error {
	ret := _mock.Called(ctx, userID, convID)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, userID, convID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnreadStore_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockUnreadStore_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - convID string
func (_e *MockUnreadStore_Expecter) Reset(ctx interface{}, userID interface{}, convID interface{}) *MockUnreadStore_Reset_Call {
	return &MockUnreadStore_Reset_Call{Call: _e.mock.On("Reset", ctx, userID, convID)}
}

func (_c *MockUnreadStore_Reset_Call) Run(run func(ctx context.Context, userID int64, convID string)) *MockUnreadStore_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUnreadStore_Reset_Call) Return(err error) *MockUnreadStore_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnreadStore_Reset_Call) RunAndReturn(run func(ctx context.Context, userID int64, convID string) error) *MockUnreadStore_Reset_Call {
	_c.Call.Return(run)
	return _c
}
