// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// GetFeedPostIDs provides a mock function with given fields: ctx, userID, cursor, limit
func (_m *MockCache) GetFeedPostIDs(ctx context.Context, userID int64, cursor int64, limit int) ([]int64, error) {
	ret := _m.Called(ctx, userID, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetFeedPostIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) ([]int64, error)); ok {
		return rf(ctx, userID, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int) []int64); ok {
		r0 = rf(ctx, userID, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int) error); ok {
		r1 = rf(ctx, userID, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCache_GetFeedPostIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeedPostIDs'
type MockCache_GetFeedPostIDs_Call struct {
	*mock.Call
}

// GetFeedPostIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - cursor int64
//   - limit int
func (_e *MockCache_Expecter) GetFeedPostIDs(ctx interface{}, userID interface{}, cursor interface{}, limit interface{}) *MockCache_GetFeedPostIDs_Call {
	return &MockCache_GetFeedPostIDs_Call{Call: _e.mock.On("GetFeedPostIDs", ctx, userID, cursor, limit)}
}

func (_c *MockCache_GetFeedPostIDs_Call) Run(run func(ctx context.Context, userID int64, cursor int64, limit int)) *MockCache_GetFeedPostIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *MockCache_GetFeedPostIDs_Call) Return(_a0 []int64, _a1 error) *MockCache_GetFeedPostIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCache_GetFeedPostIDs_Call) RunAndReturn(run func(context.Context, int64, int64, int) ([]int64, error)) *MockCache_GetFeedPostIDs_Call {
	_c.Call.Return(run)
	return _c
}

// PushPostToFeeds provides a mock function with given fields: ctx, followerIDs, postID, score
func (_m *MockCache) PushPostToFeeds(ctx context.Context, followerIDs []int64, postID int64, score float64) error {
	ret := _m.Called(ctx, followerIDs, postID, score)

	if len(ret) == 0 {
		panic("no return value specified for PushPostToFeeds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, int64, float64) error); ok {
		r0 = rf(ctx, followerIDs, postID, score)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_PushPostToFeeds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PushPostToFeeds'
type MockCache_PushPostToFeeds_Call struct {
	*mock.Call
}

// PushPostToFeeds is a helper method to define mock.On call
//   - ctx context.Context
//   - followerIDs []int64
//   - postID int64
//   - score float64
func (_e *MockCache_Expecter) PushPostToFeeds(ctx interface{}, followerIDs interface{}, postID interface{}, score interface{}) *MockCache_PushPostToFeeds_Call {
	return &MockCache_PushPostToFeeds_Call{Call: _e.mock.On("PushPostToFeeds", ctx, followerIDs, postID, score)}
}

func (_c *MockCache_PushPostToFeeds_Call) Run(run func(ctx context.Context, followerIDs []int64, postID int64, score float64)) *MockCache_PushPostToFeeds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64), args[2].(int64), args[3].(float64))
	})
	return _c
}

func (_c *MockCache_PushPostToFeeds_Call) Return(_a0 error) *MockCache_PushPostToFeeds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_PushPostToFeeds_Call) RunAndReturn(run func(context.Context, []int64, int64, float64) error) *MockCache_PushPostToFeeds_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePostFromFeeds provides a mock function with given fields: ctx, followerIDs, postID
func (_m *MockCache) RemovePostFromFeeds(ctx context.Context, followerIDs []int64, postID int64) error {
	ret := _m.Called(ctx, followerIDs, postID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePostFromFeeds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64, int64) error); ok {
		r0 = rf(ctx, followerIDs, postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_RemovePostFromFeeds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePostFromFeeds'
type MockCache_RemovePostFromFeeds_Call struct {
	*mock.Call
}

// RemovePostFromFeeds is a helper method to define mock.On call
//   - ctx context.Context
//   - followerIDs []int64
//   - postID int64
func (_e *MockCache_Expecter) RemovePostFromFeeds(ctx interface{}, followerIDs interface{}, postID interface{}) *MockCache_RemovePostFromFeeds_Call {
	return &MockCache_RemovePostFromFeeds_Call{Call: _e.mock.On("RemovePostFromFeeds", ctx, followerIDs, postID)}
}

func (_c *MockCache_RemovePostFromFeeds_Call) Run(run func(ctx context.Context, followerIDs []int64, postID int64)) *MockCache_RemovePostFromFeeds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64), args[2].(int64))
	})
	return _c
}

func (_c *MockCache_RemovePostFromFeeds_Call) Return(_a0 error) *MockCache_RemovePostFromFeeds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_RemovePostFromFeeds_Call) RunAndReturn(run func(context.Context, []int64, int64) error) *MockCache_RemovePostFromFeeds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
