// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/common"
	"air-social/internal/domain/post"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQueryUseCase creates a new instance of MockQueryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueryUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueryUseCase {
	mock := &MockQueryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueryUseCase is an autogenerated mock type for the QueryUseCase type
type MockQueryUseCase struct {
	mock.Mock
}

type MockQueryUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueryUseCase) EXPECT() *MockQueryUseCase_Expecter {
	return &MockQueryUseCase_Expecter{mock: &_m.Mock}
}

// GetNewsfeed provides a mock function for the type MockQueryUseCase
func (_mock *MockQueryUseCase) GetNewsfeed(ctx context.Context, viewerID int64, params common.CursorQueryParams[int64]) (common.CursorPaginatedResult[*post.Post, int64], error) {
	ret := _mock.Called(ctx, viewerID, params)

	if len(ret) == 0 {
		panic("no return value specified for GetNewsfeed")
	}

	var r0 common.CursorPaginatedResult[*post.Post, int64]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, common.CursorQueryParams[int64]) (common.CursorPaginatedResult[*post.Post, int64], error)); ok {
		return returnFunc(ctx, viewerID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, common.CursorQueryParams[int64]) common.CursorPaginatedResult[*post.Post, int64]); ok {
		r0 = returnFunc(ctx, viewerID, params)
	} else {
		r0 = ret.Get(0).(common.CursorPaginatedResult[*post.Post, int64])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, common.CursorQueryParams[int64]) error); ok {
		r1 = returnFunc(ctx, viewerID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueryUseCase_GetNewsfeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewsfeed'
type MockQueryUseCase_GetNewsfeed_Call struct {
	*mock.Call
}

// GetNewsfeed is a helper method to define mock.On call
//   - ctx context.Context
//   - viewerID int64
//   - params common.CursorQueryParams[int64]
func (_e *MockQueryUseCase_Expecter) GetNewsfeed(ctx interface{}, viewerID interface{}, params interface{}) *MockQueryUseCase_GetNewsfeed_Call {
	return &MockQueryUseCase_GetNewsfeed_Call{Call: _e.mock.On("GetNewsfeed", ctx, viewerID, params)}
}

func (_c *MockQueryUseCase_GetNewsfeed_Call) Run(run func(ctx context.Context, viewerID int64, params common.CursorQueryParams[int64])) *MockQueryUseCase_GetNewsfeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 common.CursorQueryParams[int64]
		if args[2] != nil {
			arg2 = args[2].(common.CursorQueryParams[int64])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueryUseCase_GetNewsfeed_Call) Return(cursorPaginatedResult common.CursorPaginatedResult[*post.Post, int64], err error) *MockQueryUseCase_GetNewsfeed_Call {
	_c.Call.Return(cursorPaginatedResult, err)
	return _c
}

func (_c *MockQueryUseCase_GetNewsfeed_Call) RunAndReturn(run func(ctx context.Context, viewerID int64, params common.CursorQueryParams[int64]) (common.CursorPaginatedResult[*post.Post, int64], error)) *MockQueryUseCase_GetNewsfeed_Call {
	_c.Call.Return(run)
	return _c
}
