// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMediaVerifier creates a new instance of MockMediaVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaVerifier {
	mock := &MockMediaVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaVerifier is an autogenerated mock type for the MediaVerifier type
type MockMediaVerifier struct {
	mock.Mock
}

type MockMediaVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaVerifier) EXPECT() *MockMediaVerifier_Expecter {
	return &MockMediaVerifier_Expecter{mock: &_m.Mock}
}

// VerifyMedia provides a mock function for the type MockMediaVerifier
func (_mock *MockMediaVerifier) VerifyMedia(ctx context.Context, keys []string) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaVerifier_VerifyMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMedia'
type MockMediaVerifier_VerifyMedia_Call struct {
	*mock.Call
}

// VerifyMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockMediaVerifier_Expecter) VerifyMedia(ctx interface{}, keys interface{}) *MockMediaVerifier_VerifyMedia_Call {
	return &MockMediaVerifier_VerifyMedia_Call{Call: _e.mock.On("VerifyMedia", ctx, keys)}
}

func (_c *MockMediaVerifier_VerifyMedia_Call) Run(run func(ctx context.Context, keys []string)) *MockMediaVerifier_VerifyMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaVerifier_VerifyMedia_Call) Return(err error) *MockMediaVerifier_VerifyMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaVerifier_VerifyMedia_Call) RunAndReturn(run func(ctx context.Context, keys []string) error) *MockMediaVerifier_VerifyMedia_Call {
	_c.Call.Return(run)
	return _c
}
