// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserChecker is an autogenerated mock type for the UserChecker type
type MockUserChecker struct {
	mock.Mock
}

type MockUserChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserChecker) EXPECT() *MockUserChecker_Expecter {
	return &MockUserChecker_Expecter{mock: &_m.Mock}
}

// FilterNonExistent provides a mock function with given fields: ctx, ids
func (_m *MockUserChecker) FilterNonExistent(ctx context.Context, ids []int64) ([]int64, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for FilterNonExistent")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]int64, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []int64); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserChecker_FilterNonExistent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilterNonExistent'
type MockUserChecker_FilterNonExistent_Call struct {
	*mock.Call
}

// FilterNonExistent is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockUserChecker_Expecter) FilterNonExistent(ctx interface{}, ids interface{}) *MockUserChecker_FilterNonExistent_Call {
	return &MockUserChecker_FilterNonExistent_Call{Call: _e.mock.On("FilterNonExistent", ctx, ids)}
}

func (_c *MockUserChecker_FilterNonExistent_Call) Run(run func(ctx context.Context, ids []int64)) *MockUserChecker_FilterNonExistent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockUserChecker_FilterNonExistent_Call) Return(missing []int64, err error) *MockUserChecker_FilterNonExistent_Call {
	_c.Call.Return(missing, err)
	return _c
}

func (_c *MockUserChecker_FilterNonExistent_Call) RunAndReturn(run func(context.Context, []int64) ([]int64, error)) *MockUserChecker_FilterNonExistent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserChecker creates a new instance of MockUserChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserChecker {
	mock := &MockUserChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
