// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAtomicCache creates a new instance of MockAtomicCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAtomicCache[V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAtomicCache[V] {
	mock := &MockAtomicCache[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAtomicCache is an autogenerated mock type for the AtomicCache type
type MockAtomicCache[V any] struct {
	mock.Mock
}

type MockAtomicCache_Expecter[V any] struct {
	mock *mock.Mock
}

func (_m *MockAtomicCache[V]) EXPECT() *MockAtomicCache_Expecter[V] {
	return &MockAtomicCache_Expecter[V]{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockAtomicCache
func (_mock *MockAtomicCache[V]) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAtomicCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAtomicCache_Delete_Call[V any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAtomicCache_Expecter[V]) Delete(ctx interface{}, key interface{}) *MockAtomicCache_Delete_Call[V] {
	return &MockAtomicCache_Delete_Call[V]{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockAtomicCache_Delete_Call[V]) Run(run func(ctx context.Context, key string)) *MockAtomicCache_Delete_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAtomicCache_Delete_Call[V]) Return(err error) *MockAtomicCache_Delete_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAtomicCache_Delete_Call[V]) RunAndReturn(run func(ctx context.Context, key string) error) *MockAtomicCache_Delete_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockAtomicCache
func (_mock *MockAtomicCache[V]) Exists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAtomicCache_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockAtomicCache_Exists_Call[V any] struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAtomicCache_Expecter[V]) Exists(ctx interface{}, key interface{}) *MockAtomicCache_Exists_Call[V] {
	return &MockAtomicCache_Exists_Call[V]{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *MockAtomicCache_Exists_Call[V]) Run(run func(ctx context.Context, key string)) *MockAtomicCache_Exists_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAtomicCache_Exists_Call[V]) Return(b bool, err error) *MockAtomicCache_Exists_Call[V] {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAtomicCache_Exists_Call[V]) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *MockAtomicCache_Exists_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockAtomicCache
func (_mock *MockAtomicCache[V]) Get(ctx context.Context, key string) (V, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (V, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) V); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAtomicCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAtomicCache_Get_Call[V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockAtomicCache_Expecter[V]) Get(ctx interface{}, key interface{}) *MockAtomicCache_Get_Call[V] {
	return &MockAtomicCache_Get_Call[V]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockAtomicCache_Get_Call[V]) Run(run func(ctx context.Context, key string)) *MockAtomicCache_Get_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAtomicCache_Get_Call[V]) Return(v V, err error) *MockAtomicCache_Get_Call[V] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAtomicCache_Get_Call[V]) RunAndReturn(run func(ctx context.Context, key string) (V, error)) *MockAtomicCache_Get_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockAtomicCache
func (_mock *MockAtomicCache[V]) Set(ctx context.Context, key string, val V, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, V, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAtomicCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockAtomicCache_Set_Call[V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val V
//   - ttl time.Duration
func (_e *MockAtomicCache_Expecter[V]) Set(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockAtomicCache_Set_Call[V] {
	return &MockAtomicCache_Set_Call[V]{Call: _e.mock.On("Set", ctx, key, val, ttl)}
}

func (_c *MockAtomicCache_Set_Call[V]) Run(run func(ctx context.Context, key string, val V, ttl time.Duration)) *MockAtomicCache_Set_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 V
		if args[2] != nil {
			arg2 = args[2].(V)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAtomicCache_Set_Call[V]) Return(err error) *MockAtomicCache_Set_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAtomicCache_Set_Call[V]) RunAndReturn(run func(ctx context.Context, key string, val V, ttl time.Duration) error) *MockAtomicCache_Set_Call[V] {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function for the type MockAtomicCache
func (_mock *MockAtomicCache[V]) SetNX(ctx context.Context, key string, val V, ttl time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, V, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, val, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, V, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, V, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, val, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAtomicCache_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type MockAtomicCache_SetNX_Call[V any] struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val V
//   - ttl time.Duration
func (_e *MockAtomicCache_Expecter[V]) SetNX(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockAtomicCache_SetNX_Call[V] {
	return &MockAtomicCache_SetNX_Call[V]{Call: _e.mock.On("SetNX", ctx, key, val, ttl)}
}

func (_c *MockAtomicCache_SetNX_Call[V]) Run(run func(ctx context.Context, key string, val V, ttl time.Duration)) *MockAtomicCache_SetNX_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 V
		if args[2] != nil {
			arg2 = args[2].(V)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAtomicCache_SetNX_Call[V]) Return(b bool, err error) *MockAtomicCache_SetNX_Call[V] {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAtomicCache_SetNX_Call[V]) RunAndReturn(run func(ctx context.Context, key string, val V, ttl time.Duration) (bool, error)) *MockAtomicCache_SetNX_Call[V] {
	_c.Call.Return(run)
	return _c
}
