// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache[V any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache[V] {
	mock := &MockCache[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache[V any] struct {
	mock.Mock
}

type MockCache_Expecter[V any] struct {
	mock *mock.Mock
}

func (_m *MockCache[V]) EXPECT() *MockCache_Expecter[V] {
	return &MockCache_Expecter[V]{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockCache
func (_mock *MockCache[V]) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCache_Delete_Call[V any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter[V]) Delete(ctx interface{}, key interface{}) *MockCache_Delete_Call[V] {
	return &MockCache_Delete_Call[V]{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCache_Delete_Call[V]) Run(run func(ctx context.Context, key string)) *MockCache_Delete_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Delete_Call[V]) Return(err error) *MockCache_Delete_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Delete_Call[V]) RunAndReturn(run func(ctx context.Context, key string) error) *MockCache_Delete_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache[V]) Get(ctx context.Context, key string) (V, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (V, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) V); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call[V any] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter[V]) Get(ctx interface{}, key interface{}) *MockCache_Get_Call[V] {
	return &MockCache_Get_Call[V]{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockCache_Get_Call[V]) Run(run func(ctx context.Context, key string)) *MockCache_Get_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call[V]) Return(v V, err error) *MockCache_Get_Call[V] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCache_Get_Call[V]) RunAndReturn(run func(ctx context.Context, key string) (V, error)) *MockCache_Get_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockCache
func (_mock *MockCache[V]) Set(ctx context.Context, key string, val V, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, val, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, V, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, val, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockCache_Set_Call[V any] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val V
//   - ttl time.Duration
func (_e *MockCache_Expecter[V]) Set(ctx interface{}, key interface{}, val interface{}, ttl interface{}) *MockCache_Set_Call[V] {
	return &MockCache_Set_Call[V]{Call: _e.mock.On("Set", ctx, key, val, ttl)}
}

func (_c *MockCache_Set_Call[V]) Run(run func(ctx context.Context, key string, val V, ttl time.Duration)) *MockCache_Set_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 V
		if args[2] != nil {
			arg2 = args[2].(V)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCache_Set_Call[V]) Return(err error) *MockCache_Set_Call[V] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Set_Call[V]) RunAndReturn(run func(ctx context.Context, key string, val V, ttl time.Duration) error) *MockCache_Set_Call[V] {
	_c.Call.Return(run)
	return _c
}
