// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHashStore creates a new instance of MockHashStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashStore {
	mock := &MockHashStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHashStore is an autogenerated mock type for the HashStore type
type MockHashStore struct {
	mock.Mock
}

type MockHashStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashStore) EXPECT() *MockHashStore_Expecter {
	return &MockHashStore_Expecter{mock: &_m.Mock}
}

// Eval provides a mock function for the type MockHashStore
func (_mock *MockHashStore) Eval(ctx context.Context, script string, keys []string, args ...any) (any, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, script, keys, args)
	} else {
		tmpRet = _mock.Called(ctx, script, keys)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, ...any) (any, error)); ok {
		return returnFunc(ctx, script, keys, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, ...any) any); ok {
		r0 = returnFunc(ctx, script, keys, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, ...any) error); ok {
		r1 = returnFunc(ctx, script, keys, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHashStore_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type MockHashStore_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - ctx context.Context
//   - script string
//   - keys []string
//   - args ...any
func (_e *MockHashStore_Expecter) Eval(ctx interface{}, script interface{}, keys interface{}, args ...interface{}) *MockHashStore_Eval_Call {
	return &MockHashStore_Eval_Call{Call: _e.mock.On("Eval",
		append([]interface{}{ctx, script, keys}, args...)...)}
}

func (_c *MockHashStore_Eval_Call) Run(run func(ctx context.Context, script string, keys []string, args ...any)) *MockHashStore_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockHashStore_Eval_Call) Return(v any, err error) *MockHashStore_Eval_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockHashStore_Eval_Call) RunAndReturn(run func(ctx context.Context, script string, keys []string, args ...any) (any, error)) *MockHashStore_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// HDel provides a mock function for the type MockHashStore
func (_mock *MockHashStore) HDel(ctx context.Context, key string, fields ...string) error {
	var tmpRet mock.Arguments
	if len(fields) > 0 {
		tmpRet = _mock.Called(ctx, key, fields)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HDel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = returnFunc(ctx, key, fields...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHashStore_HDel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HDel'
type MockHashStore_HDel_Call struct {
	*mock.Call
}

// HDel is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - fields ...string
func (_e *MockHashStore_Expecter) HDel(ctx interface{}, key interface{}, fields ...interface{}) *MockHashStore_HDel_Call {
	return &MockHashStore_HDel_Call{Call: _e.mock.On("HDel",
		append([]interface{}{ctx, key}, fields...)...)}
}

func (_c *MockHashStore_HDel_Call) Run(run func(ctx context.Context, key string, fields ...string)) *MockHashStore_HDel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHashStore_HDel_Call) Return(err error) *MockHashStore_HDel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHashStore_HDel_Call) RunAndReturn(run func(ctx context.Context, key string, fields ...string) error) *MockHashStore_HDel_Call {
	_c.Call.Return(run)
	return _c
}

// HGetAll provides a mock function for the type MockHashStore
func (_mock *MockHashStore) HGetAll(ctx context.Context, key string) (map[string]string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for HGetAll")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHashStore_HGetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HGetAll'
type MockHashStore_HGetAll_Call struct {
	*mock.Call
}

// HGetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockHashStore_Expecter) HGetAll(ctx interface{}, key interface{}) *MockHashStore_HGetAll_Call {
	return &MockHashStore_HGetAll_Call{Call: _e.mock.On("HGetAll", ctx, key)}
}

func (_c *MockHashStore_HGetAll_Call) Run(run func(ctx context.Context, key string)) *MockHashStore_HGetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHashStore_HGetAll_Call) Return(stringToString map[string]string, err error) *MockHashStore_HGetAll_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockHashStore_HGetAll_Call) RunAndReturn(run func(ctx context.Context, key string) (map[string]string, error)) *MockHashStore_HGetAll_Call {
	_c.Call.Return(run)
	return _c
}

// HIncrBy provides a mock function for the type MockHashStore
func (_mock *MockHashStore) HIncrBy(ctx context.Context, key string, field string, incr int64) (int64, error) {
	ret := _mock.Called(ctx, key, field, incr)

	if len(ret) == 0 {
		panic("no return value specified for HIncrBy")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) (int64, error)); ok {
		return returnFunc(ctx, key, field, incr)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) int64); ok {
		r0 = returnFunc(ctx, key, field, incr)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = returnFunc(ctx, key, field, incr)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHashStore_HIncrBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HIncrBy'
type MockHashStore_HIncrBy_Call struct {
	*mock.Call
}

// HIncrBy is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - field string
//   - incr int64
func (_e *MockHashStore_Expecter) HIncrBy(ctx interface{}, key interface{}, field interface{}, incr interface{}) *MockHashStore_HIncrBy_Call {
	return &MockHashStore_HIncrBy_Call{Call: _e.mock.On("HIncrBy", ctx, key, field, incr)}
}

func (_c *MockHashStore_HIncrBy_Call) Run(run func(ctx context.Context, key string, field string, incr int64)) *MockHashStore_HIncrBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockHashStore_HIncrBy_Call) Return(n int64, err error) *MockHashStore_HIncrBy_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHashStore_HIncrBy_Call) RunAndReturn(run func(ctx context.Context, key string, field string, incr int64) (int64, error)) *MockHashStore_HIncrBy_Call {
	_c.Call.Return(run)
	return _c
}

// HMGet provides a mock function for the type MockHashStore
func (_mock *MockHashStore) HMGet(ctx context.Context, key string, fields ...string) ([]string, error) {
	var tmpRet mock.Arguments
	if len(fields) > 0 {
		tmpRet = _mock.Called(ctx, key, fields)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HMGet")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) ([]string, error)); ok {
		return returnFunc(ctx, key, fields...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) []string); ok {
		r0 = returnFunc(ctx, key, fields...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, key, fields...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHashStore_HMGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HMGet'
type MockHashStore_HMGet_Call struct {
	*mock.Call
}

// HMGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - fields ...string
func (_e *MockHashStore_Expecter) HMGet(ctx interface{}, key interface{}, fields ...interface{}) *MockHashStore_HMGet_Call {
	return &MockHashStore_HMGet_Call{Call: _e.mock.On("HMGet",
		append([]interface{}{ctx, key}, fields...)...)}
}

func (_c *MockHashStore_HMGet_Call) Run(run func(ctx context.Context, key string, fields ...string)) *MockHashStore_HMGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockHashStore_HMGet_Call) Return(strings []string, err error) *MockHashStore_HMGet_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockHashStore_HMGet_Call) RunAndReturn(run func(ctx context.Context, key string, fields ...string) ([]string, error)) *MockHashStore_HMGet_Call {
	_c.Call.Return(run)
	return _c
}
