// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHashStore is an autogenerated mock type for the HashStore type
type MockHashStore struct {
	mock.Mock
}

type MockHashStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashStore) EXPECT() *MockHashStore_Expecter {
	return &MockHashStore_Expecter{mock: &_m.Mock}
}

// Eval provides a mock function with given fields: ctx, script, keys, args
func (_m *MockHashStore) Eval(ctx context.Context, script string, keys []string, args ...interface{}) (interface{}, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, script, keys)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Eval")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) (interface{}, error)); ok {
		return rf(ctx, script, keys, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string, ...interface{}) interface{}); ok {
		r0 = rf(ctx, script, keys, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string, ...interface{}) error); ok {
		r1 = rf(ctx, script, keys, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashStore_Eval_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Eval'
type MockHashStore_Eval_Call struct {
	*mock.Call
}

// Eval is a helper method to define mock.On call
//   - ctx context.Context
//   - script string
//   - keys []string
//   - args ...interface{}
func (_e *MockHashStore_Expecter) Eval(ctx interface{}, script interface{}, keys interface{}, args ...interface{}) *MockHashStore_Eval_Call {
	return &MockHashStore_Eval_Call{Call: _e.mock.On("Eval",
		append([]interface{}{ctx, script, keys}, args...)...)}
}

func (_c *MockHashStore_Eval_Call) Run(run func(ctx context.Context, script string, keys []string, args ...interface{})) *MockHashStore_Eval_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].([]string), variadicArgs...)
	})
	return _c
}

func (_c *MockHashStore_Eval_Call) Return(_a0 interface{}, _a1 error) *MockHashStore_Eval_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashStore_Eval_Call) RunAndReturn(run func(context.Context, string, []string, ...interface{}) (interface{}, error)) *MockHashStore_Eval_Call {
	_c.Call.Return(run)
	return _c
}

// HDel provides a mock function with given fields: ctx, key, fields
func (_m *MockHashStore) HDel(ctx context.Context, key string, fields ...string) error {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HDel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) error); ok {
		r0 = rf(ctx, key, fields...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHashStore_HDel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HDel'
type MockHashStore_HDel_Call struct {
	*mock.Call
}

// HDel is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - fields ...string
func (_e *MockHashStore_Expecter) HDel(ctx interface{}, key interface{}, fields ...interface{}) *MockHashStore_HDel_Call {
	return &MockHashStore_HDel_Call{Call: _e.mock.On("HDel",
		append([]interface{}{ctx, key}, fields...)...)}
}

func (_c *MockHashStore_HDel_Call) Run(run func(ctx context.Context, key string, fields ...string)) *MockHashStore_HDel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHashStore_HDel_Call) Return(_a0 error) *MockHashStore_HDel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHashStore_HDel_Call) RunAndReturn(run func(context.Context, string, ...string) error) *MockHashStore_HDel_Call {
	_c.Call.Return(run)
	return _c
}

// HGetAll provides a mock function with given fields: ctx, key
func (_m *MockHashStore) HGetAll(ctx context.Context, key string) (map[string]string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for HGetAll")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashStore_HGetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HGetAll'
type MockHashStore_HGetAll_Call struct {
	*mock.Call
}

// HGetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockHashStore_Expecter) HGetAll(ctx interface{}, key interface{}) *MockHashStore_HGetAll_Call {
	return &MockHashStore_HGetAll_Call{Call: _e.mock.On("HGetAll", ctx, key)}
}

func (_c *MockHashStore_HGetAll_Call) Run(run func(ctx context.Context, key string)) *MockHashStore_HGetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockHashStore_HGetAll_Call) Return(_a0 map[string]string, _a1 error) *MockHashStore_HGetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashStore_HGetAll_Call) RunAndReturn(run func(context.Context, string) (map[string]string, error)) *MockHashStore_HGetAll_Call {
	_c.Call.Return(run)
	return _c
}

// HIncrBy provides a mock function with given fields: ctx, key, field, incr
func (_m *MockHashStore) HIncrBy(ctx context.Context, key string, field string, incr int64) (int64, error) {
	ret := _m.Called(ctx, key, field, incr)

	if len(ret) == 0 {
		panic("no return value specified for HIncrBy")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (int64, error)); ok {
		return rf(ctx, key, field, incr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) int64); ok {
		r0 = rf(ctx, key, field, incr)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, key, field, incr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashStore_HIncrBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HIncrBy'
type MockHashStore_HIncrBy_Call struct {
	*mock.Call
}

// HIncrBy is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - field string
//   - incr int64
func (_e *MockHashStore_Expecter) HIncrBy(ctx interface{}, key interface{}, field interface{}, incr interface{}) *MockHashStore_HIncrBy_Call {
	return &MockHashStore_HIncrBy_Call{Call: _e.mock.On("HIncrBy", ctx, key, field, incr)}
}

func (_c *MockHashStore_HIncrBy_Call) Run(run func(ctx context.Context, key string, field string, incr int64)) *MockHashStore_HIncrBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *MockHashStore_HIncrBy_Call) Return(_a0 int64, _a1 error) *MockHashStore_HIncrBy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashStore_HIncrBy_Call) RunAndReturn(run func(context.Context, string, string, int64) (int64, error)) *MockHashStore_HIncrBy_Call {
	_c.Call.Return(run)
	return _c
}

// HMGet provides a mock function with given fields: ctx, key, fields
func (_m *MockHashStore) HMGet(ctx context.Context, key string, fields ...string) ([]string, error) {
	_va := make([]interface{}, len(fields))
	for _i := range fields {
		_va[_i] = fields[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HMGet")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) ([]string, error)); ok {
		return rf(ctx, key, fields...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) []string); ok {
		r0 = rf(ctx, key, fields...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, key, fields...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashStore_HMGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HMGet'
type MockHashStore_HMGet_Call struct {
	*mock.Call
}

// HMGet is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - fields ...string
func (_e *MockHashStore_Expecter) HMGet(ctx interface{}, key interface{}, fields ...interface{}) *MockHashStore_HMGet_Call {
	return &MockHashStore_HMGet_Call{Call: _e.mock.On("HMGet",
		append([]interface{}{ctx, key}, fields...)...)}
}

func (_c *MockHashStore_HMGet_Call) Run(run func(ctx context.Context, key string, fields ...string)) *MockHashStore_HMGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockHashStore_HMGet_Call) Return(_a0 []string, _a1 error) *MockHashStore_HMGet_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashStore_HMGet_Call) RunAndReturn(run func(context.Context, string, ...string) ([]string, error)) *MockHashStore_HMGet_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHashStore creates a new instance of MockHashStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashStore {
	mock := &MockHashStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
