// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/cache"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSortedSetStore creates a new instance of MockSortedSetStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSortedSetStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSortedSetStore {
	mock := &MockSortedSetStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSortedSetStore is an autogenerated mock type for the SortedSetStore type
type MockSortedSetStore struct {
	mock.Mock
}

type MockSortedSetStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSortedSetStore) EXPECT() *MockSortedSetStore_Expecter {
	return &MockSortedSetStore_Expecter{mock: &_m.Mock}
}

// Pipeline provides a mock function for the type MockSortedSetStore
func (_mock *MockSortedSetStore) Pipeline() cache.Batch {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pipeline")
	}

	var r0 cache.Batch
	if returnFunc, ok := ret.Get(0).(func() cache.Batch); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.Batch)
		}
	}
	return r0
}

// MockSortedSetStore_Pipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipeline'
type MockSortedSetStore_Pipeline_Call struct {
	*mock.Call
}

// Pipeline is a helper method to define mock.On call
func (_e *MockSortedSetStore_Expecter) Pipeline() *MockSortedSetStore_Pipeline_Call {
	return &MockSortedSetStore_Pipeline_Call{Call: _e.mock.On("Pipeline")}
}

func (_c *MockSortedSetStore_Pipeline_Call) Run(run func()) *MockSortedSetStore_Pipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSortedSetStore_Pipeline_Call) Return(batch cache.Batch) *MockSortedSetStore_Pipeline_Call {
	_c.Call.Return(batch)
	return _c
}

func (_c *MockSortedSetStore_Pipeline_Call) RunAndReturn(run func() cache.Batch) *MockSortedSetStore_Pipeline_Call {
	_c.Call.Return(run)
	return _c
}

// ZAdd provides a mock function for the type MockSortedSetStore
func (_mock *MockSortedSetStore) ZAdd(ctx context.Context, key string, score float64, member any) error {
	ret := _mock.Called(ctx, key, score, member)

	if len(ret) == 0 {
		panic("no return value specified for ZAdd")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64, any) error); ok {
		r0 = returnFunc(ctx, key, score, member)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSortedSetStore_ZAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZAdd'
type MockSortedSetStore_ZAdd_Call struct {
	*mock.Call
}

// ZAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - score float64
//   - member any
func (_e *MockSortedSetStore_Expecter) ZAdd(ctx interface{}, key interface{}, score interface{}, member interface{}) *MockSortedSetStore_ZAdd_Call {
	return &MockSortedSetStore_ZAdd_Call{Call: _e.mock.On("ZAdd", ctx, key, score, member)}
}

func (_c *MockSortedSetStore_ZAdd_Call) Run(run func(ctx context.Context, key string, score float64, member any)) *MockSortedSetStore_ZAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSortedSetStore_ZAdd_Call) Return(err error) *MockSortedSetStore_ZAdd_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSortedSetStore_ZAdd_Call) RunAndReturn(run func(ctx context.Context, key string, score float64, member any) error) *MockSortedSetStore_ZAdd_Call {
	_c.Call.Return(run)
	return _c
}

// ZRem provides a mock function for the type MockSortedSetStore
func (_mock *MockSortedSetStore) ZRem(ctx context.Context, key string, members ...any) error {
	var tmpRet mock.Arguments
	if len(members) > 0 {
		tmpRet = _mock.Called(ctx, key, members)
	} else {
		tmpRet = _mock.Called(ctx, key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ZRem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = returnFunc(ctx, key, members...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSortedSetStore_ZRem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRem'
type MockSortedSetStore_ZRem_Call struct {
	*mock.Call
}

// ZRem is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - members ...any
func (_e *MockSortedSetStore_Expecter) ZRem(ctx interface{}, key interface{}, members ...interface{}) *MockSortedSetStore_ZRem_Call {
	return &MockSortedSetStore_ZRem_Call{Call: _e.mock.On("ZRem",
		append([]interface{}{ctx, key}, members...)...)}
}

func (_c *MockSortedSetStore_ZRem_Call) Run(run func(ctx context.Context, key string, members ...any)) *MockSortedSetStore_ZRem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSortedSetStore_ZRem_Call) Return(err error) *MockSortedSetStore_ZRem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSortedSetStore_ZRem_Call) RunAndReturn(run func(ctx context.Context, key string, members ...any) error) *MockSortedSetStore_ZRem_Call {
	_c.Call.Return(run)
	return _c
}

// ZRemRangeByRank provides a mock function for the type MockSortedSetStore
func (_mock *MockSortedSetStore) ZRemRangeByRank(ctx context.Context, key string, start int64, stop int64) error {
	ret := _mock.Called(ctx, key, start, stop)

	if len(ret) == 0 {
		panic("no return value specified for ZRemRangeByRank")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) error); ok {
		r0 = returnFunc(ctx, key, start, stop)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSortedSetStore_ZRemRangeByRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRemRangeByRank'
type MockSortedSetStore_ZRemRangeByRank_Call struct {
	*mock.Call
}

// ZRemRangeByRank is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start int64
//   - stop int64
func (_e *MockSortedSetStore_Expecter) ZRemRangeByRank(ctx interface{}, key interface{}, start interface{}, stop interface{}) *MockSortedSetStore_ZRemRangeByRank_Call {
	return &MockSortedSetStore_ZRemRangeByRank_Call{Call: _e.mock.On("ZRemRangeByRank", ctx, key, start, stop)}
}

func (_c *MockSortedSetStore_ZRemRangeByRank_Call) Run(run func(ctx context.Context, key string, start int64, stop int64)) *MockSortedSetStore_ZRemRangeByRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSortedSetStore_ZRemRangeByRank_Call) Return(err error) *MockSortedSetStore_ZRemRangeByRank_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSortedSetStore_ZRemRangeByRank_Call) RunAndReturn(run func(ctx context.Context, key string, start int64, stop int64) error) *MockSortedSetStore_ZRemRangeByRank_Call {
	_c.Call.Return(run)
	return _c
}

// ZRevRange provides a mock function for the type MockSortedSetStore
func (_mock *MockSortedSetStore) ZRevRange(ctx context.Context, key string, start int64, stop int64) ([]string, error) {
	ret := _mock.Called(ctx, key, start, stop)

	if len(ret) == 0 {
		panic("no return value specified for ZRevRange")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]string, error)); ok {
		return returnFunc(ctx, key, start, stop)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) []string); ok {
		r0 = returnFunc(ctx, key, start, stop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, key, start, stop)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSortedSetStore_ZRevRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRevRange'
type MockSortedSetStore_ZRevRange_Call struct {
	*mock.Call
}

// ZRevRange is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start int64
//   - stop int64
func (_e *MockSortedSetStore_Expecter) ZRevRange(ctx interface{}, key interface{}, start interface{}, stop interface{}) *MockSortedSetStore_ZRevRange_Call {
	return &MockSortedSetStore_ZRevRange_Call{Call: _e.mock.On("ZRevRange", ctx, key, start, stop)}
}

func (_c *MockSortedSetStore_ZRevRange_Call) Run(run func(ctx context.Context, key string, start int64, stop int64)) *MockSortedSetStore_ZRevRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSortedSetStore_ZRevRange_Call) Return(strings []string, err error) *MockSortedSetStore_ZRevRange_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSortedSetStore_ZRevRange_Call) RunAndReturn(run func(ctx context.Context, key string, start int64, stop int64) ([]string, error)) *MockSortedSetStore_ZRevRange_Call {
	_c.Call.Return(run)
	return _c
}

// ZRevRangeByScore provides a mock function for the type MockSortedSetStore
func (_mock *MockSortedSetStore) ZRevRangeByScore(ctx context.Context, key string, min string, max string, offset int64, count int64) ([]string, error) {
	ret := _mock.Called(ctx, key, min, max, offset, count)

	if len(ret) == 0 {
		panic("no return value specified for ZRevRangeByScore")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64) ([]string, error)); ok {
		return returnFunc(ctx, key, min, max, offset, count)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64) []string); ok {
		r0 = returnFunc(ctx, key, min, max, offset, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, int64, int64) error); ok {
		r1 = returnFunc(ctx, key, min, max, offset, count)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSortedSetStore_ZRevRangeByScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRevRangeByScore'
type MockSortedSetStore_ZRevRangeByScore_Call struct {
	*mock.Call
}

// ZRevRangeByScore is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - min string
//   - max string
//   - offset int64
//   - count int64
func (_e *MockSortedSetStore_Expecter) ZRevRangeByScore(ctx interface{}, key interface{}, min interface{}, max interface{}, offset interface{}, count interface{}) *MockSortedSetStore_ZRevRangeByScore_Call {
	return &MockSortedSetStore_ZRevRangeByScore_Call{Call: _e.mock.On("ZRevRangeByScore", ctx, key, min, max, offset, count)}
}

func (_c *MockSortedSetStore_ZRevRangeByScore_Call) Run(run func(ctx context.Context, key string, min string, max string, offset int64, count int64)) *MockSortedSetStore_ZRevRangeByScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 int64
		if args[4] != nil {
			arg4 = args[4].(int64)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockSortedSetStore_ZRevRangeByScore_Call) Return(strings []string, err error) *MockSortedSetStore_ZRevRangeByScore_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSortedSetStore_ZRevRangeByScore_Call) RunAndReturn(run func(ctx context.Context, key string, min string, max string, offset int64, count int64) ([]string, error)) *MockSortedSetStore_ZRevRangeByScore_Call {
	_c.Call.Return(run)
	return _c
}
