// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	cache "air-social/internal/cache"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSortedSetStore is an autogenerated mock type for the SortedSetStore type
type MockSortedSetStore struct {
	mock.Mock
}

type MockSortedSetStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSortedSetStore) EXPECT() *MockSortedSetStore_Expecter {
	return &MockSortedSetStore_Expecter{mock: &_m.Mock}
}

// Pipeline provides a mock function with no fields
func (_m *MockSortedSetStore) Pipeline() cache.Batch {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Pipeline")
	}

	var r0 cache.Batch
	if rf, ok := ret.Get(0).(func() cache.Batch); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.Batch)
		}
	}

	return r0
}

// MockSortedSetStore_Pipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipeline'
type MockSortedSetStore_Pipeline_Call struct {
	*mock.Call
}

// Pipeline is a helper method to define mock.On call
func (_e *MockSortedSetStore_Expecter) Pipeline() *MockSortedSetStore_Pipeline_Call {
	return &MockSortedSetStore_Pipeline_Call{Call: _e.mock.On("Pipeline")}
}

func (_c *MockSortedSetStore_Pipeline_Call) Run(run func()) *MockSortedSetStore_Pipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSortedSetStore_Pipeline_Call) Return(_a0 cache.Batch) *MockSortedSetStore_Pipeline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSortedSetStore_Pipeline_Call) RunAndReturn(run func() cache.Batch) *MockSortedSetStore_Pipeline_Call {
	_c.Call.Return(run)
	return _c
}

// ZAdd provides a mock function with given fields: ctx, key, score, member
func (_m *MockSortedSetStore) ZAdd(ctx context.Context, key string, score float64, member interface{}) error {
	ret := _m.Called(ctx, key, score, member)

	if len(ret) == 0 {
		panic("no return value specified for ZAdd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, interface{}) error); ok {
		r0 = rf(ctx, key, score, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSortedSetStore_ZAdd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZAdd'
type MockSortedSetStore_ZAdd_Call struct {
	*mock.Call
}

// ZAdd is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - score float64
//   - member interface{}
func (_e *MockSortedSetStore_Expecter) ZAdd(ctx interface{}, key interface{}, score interface{}, member interface{}) *MockSortedSetStore_ZAdd_Call {
	return &MockSortedSetStore_ZAdd_Call{Call: _e.mock.On("ZAdd", ctx, key, score, member)}
}

func (_c *MockSortedSetStore_ZAdd_Call) Run(run func(ctx context.Context, key string, score float64, member interface{})) *MockSortedSetStore_ZAdd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(interface{}))
	})
	return _c
}

func (_c *MockSortedSetStore_ZAdd_Call) Return(_a0 error) *MockSortedSetStore_ZAdd_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSortedSetStore_ZAdd_Call) RunAndReturn(run func(context.Context, string, float64, interface{}) error) *MockSortedSetStore_ZAdd_Call {
	_c.Call.Return(run)
	return _c
}

// ZRem provides a mock function with given fields: ctx, key, members
func (_m *MockSortedSetStore) ZRem(ctx context.Context, key string, members ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, key)
	_ca = append(_ca, members...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ZRem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) error); ok {
		r0 = rf(ctx, key, members...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSortedSetStore_ZRem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRem'
type MockSortedSetStore_ZRem_Call struct {
	*mock.Call
}

// ZRem is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - members ...interface{}
func (_e *MockSortedSetStore_Expecter) ZRem(ctx interface{}, key interface{}, members ...interface{}) *MockSortedSetStore_ZRem_Call {
	return &MockSortedSetStore_ZRem_Call{Call: _e.mock.On("ZRem",
		append([]interface{}{ctx, key}, members...)...)}
}

func (_c *MockSortedSetStore_ZRem_Call) Run(run func(ctx context.Context, key string, members ...interface{})) *MockSortedSetStore_ZRem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSortedSetStore_ZRem_Call) Return(_a0 error) *MockSortedSetStore_ZRem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSortedSetStore_ZRem_Call) RunAndReturn(run func(context.Context, string, ...interface{}) error) *MockSortedSetStore_ZRem_Call {
	_c.Call.Return(run)
	return _c
}

// ZRemRangeByRank provides a mock function with given fields: ctx, key, start, stop
func (_m *MockSortedSetStore) ZRemRangeByRank(ctx context.Context, key string, start int64, stop int64) error {
	ret := _m.Called(ctx, key, start, stop)

	if len(ret) == 0 {
		panic("no return value specified for ZRemRangeByRank")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) error); ok {
		r0 = rf(ctx, key, start, stop)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSortedSetStore_ZRemRangeByRank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRemRangeByRank'
type MockSortedSetStore_ZRemRangeByRank_Call struct {
	*mock.Call
}

// ZRemRangeByRank is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start int64
//   - stop int64
func (_e *MockSortedSetStore_Expecter) ZRemRangeByRank(ctx interface{}, key interface{}, start interface{}, stop interface{}) *MockSortedSetStore_ZRemRangeByRank_Call {
	return &MockSortedSetStore_ZRemRangeByRank_Call{Call: _e.mock.On("ZRemRangeByRank", ctx, key, start, stop)}
}

func (_c *MockSortedSetStore_ZRemRangeByRank_Call) Run(run func(ctx context.Context, key string, start int64, stop int64)) *MockSortedSetStore_ZRemRangeByRank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockSortedSetStore_ZRemRangeByRank_Call) Return(_a0 error) *MockSortedSetStore_ZRemRangeByRank_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSortedSetStore_ZRemRangeByRank_Call) RunAndReturn(run func(context.Context, string, int64, int64) error) *MockSortedSetStore_ZRemRangeByRank_Call {
	_c.Call.Return(run)
	return _c
}

// ZRevRange provides a mock function with given fields: ctx, key, start, stop
func (_m *MockSortedSetStore) ZRevRange(ctx context.Context, key string, start int64, stop int64) ([]string, error) {
	ret := _m.Called(ctx, key, start, stop)

	if len(ret) == 0 {
		panic("no return value specified for ZRevRange")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]string, error)); ok {
		return rf(ctx, key, start, stop)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []string); ok {
		r0 = rf(ctx, key, start, stop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, key, start, stop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSortedSetStore_ZRevRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRevRange'
type MockSortedSetStore_ZRevRange_Call struct {
	*mock.Call
}

// ZRevRange is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - start int64
//   - stop int64
func (_e *MockSortedSetStore_Expecter) ZRevRange(ctx interface{}, key interface{}, start interface{}, stop interface{}) *MockSortedSetStore_ZRevRange_Call {
	return &MockSortedSetStore_ZRevRange_Call{Call: _e.mock.On("ZRevRange", ctx, key, start, stop)}
}

func (_c *MockSortedSetStore_ZRevRange_Call) Run(run func(ctx context.Context, key string, start int64, stop int64)) *MockSortedSetStore_ZRevRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *MockSortedSetStore_ZRevRange_Call) Return(_a0 []string, _a1 error) *MockSortedSetStore_ZRevRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSortedSetStore_ZRevRange_Call) RunAndReturn(run func(context.Context, string, int64, int64) ([]string, error)) *MockSortedSetStore_ZRevRange_Call {
	_c.Call.Return(run)
	return _c
}

// ZRevRangeByScore provides a mock function with given fields: ctx, key, min, max, offset, count
func (_m *MockSortedSetStore) ZRevRangeByScore(ctx context.Context, key string, min string, max string, offset int64, count int64) ([]string, error) {
	ret := _m.Called(ctx, key, min, max, offset, count)

	if len(ret) == 0 {
		panic("no return value specified for ZRevRangeByScore")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64) ([]string, error)); ok {
		return rf(ctx, key, min, max, offset, count)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64, int64) []string); ok {
		r0 = rf(ctx, key, min, max, offset, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64, int64) error); ok {
		r1 = rf(ctx, key, min, max, offset, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSortedSetStore_ZRevRangeByScore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ZRevRangeByScore'
type MockSortedSetStore_ZRevRangeByScore_Call struct {
	*mock.Call
}

// ZRevRangeByScore is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - min string
//   - max string
//   - offset int64
//   - count int64
func (_e *MockSortedSetStore_Expecter) ZRevRangeByScore(ctx interface{}, key interface{}, min interface{}, max interface{}, offset interface{}, count interface{}) *MockSortedSetStore_ZRevRangeByScore_Call {
	return &MockSortedSetStore_ZRevRangeByScore_Call{Call: _e.mock.On("ZRevRangeByScore", ctx, key, min, max, offset, count)}
}

func (_c *MockSortedSetStore_ZRevRangeByScore_Call) Run(run func(ctx context.Context, key string, min string, max string, offset int64, count int64)) *MockSortedSetStore_ZRevRangeByScore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int64), args[5].(int64))
	})
	return _c
}

func (_c *MockSortedSetStore_ZRevRangeByScore_Call) Return(_a0 []string, _a1 error) *MockSortedSetStore_ZRevRangeByScore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSortedSetStore_ZRevRangeByScore_Call) RunAndReturn(run func(context.Context, string, string, string, int64, int64) ([]string, error)) *MockSortedSetStore_ZRevRangeByScore_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSortedSetStore creates a new instance of MockSortedSetStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSortedSetStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSortedSetStore {
	mock := &MockSortedSetStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
