// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTieredStore is an autogenerated mock type for the TieredStore type
type MockTieredStore[V interface{}] struct {
	mock.Mock
}

type MockTieredStore_Expecter[V interface{}] struct {
	mock *mock.Mock
}

func (_m *MockTieredStore[V]) EXPECT() *MockTieredStore_Expecter[V] {
	return &MockTieredStore_Expecter[V]{mock: &_m.Mock}
}

// GetOrLoad provides a mock function with given fields: ctx, key, loader
func (_m *MockTieredStore[V]) GetOrLoad(ctx context.Context, key string, loader func(context.Context) (V, error)) (V, error) {
	ret := _m.Called(ctx, key, loader)

	if len(ret) == 0 {
		panic("no return value specified for GetOrLoad")
	}

	var r0 V
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) (V, error)) (V, error)); ok {
		return rf(ctx, key, loader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, func(context.Context) (V, error)) V); ok {
		r0 = rf(ctx, key, loader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(V)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, func(context.Context) (V, error)) error); ok {
		r1 = rf(ctx, key, loader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTieredStore_GetOrLoad_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrLoad'
type MockTieredStore_GetOrLoad_Call[V interface{}] struct {
	*mock.Call
}

// GetOrLoad is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - loader func(context.Context)(V , error)
func (_e *MockTieredStore_Expecter[V]) GetOrLoad(ctx interface{}, key interface{}, loader interface{}) *MockTieredStore_GetOrLoad_Call[V] {
	return &MockTieredStore_GetOrLoad_Call[V]{Call: _e.mock.On("GetOrLoad", ctx, key, loader)}
}

func (_c *MockTieredStore_GetOrLoad_Call[V]) Run(run func(ctx context.Context, key string, loader func(context.Context) (V, error))) *MockTieredStore_GetOrLoad_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(func(context.Context) (V, error)))
	})
	return _c
}

func (_c *MockTieredStore_GetOrLoad_Call[V]) Return(_a0 V, _a1 error) *MockTieredStore_GetOrLoad_Call[V] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTieredStore_GetOrLoad_Call[V]) RunAndReturn(run func(context.Context, string, func(context.Context) (V, error)) (V, error)) *MockTieredStore_GetOrLoad_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: ctx, key
func (_m *MockTieredStore[V]) Invalidate(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTieredStore_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockTieredStore_Invalidate_Call[V interface{}] struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockTieredStore_Expecter[V]) Invalidate(ctx interface{}, key interface{}) *MockTieredStore_Invalidate_Call[V] {
	return &MockTieredStore_Invalidate_Call[V]{Call: _e.mock.On("Invalidate", ctx, key)}
}

func (_c *MockTieredStore_Invalidate_Call[V]) Run(run func(ctx context.Context, key string)) *MockTieredStore_Invalidate_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTieredStore_Invalidate_Call[V]) Return(_a0 error) *MockTieredStore_Invalidate_Call[V] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTieredStore_Invalidate_Call[V]) RunAndReturn(run func(context.Context, string) error) *MockTieredStore_Invalidate_Call[V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, val
func (_m *MockTieredStore[V]) Set(ctx context.Context, key string, val V) error {
	ret := _m.Called(ctx, key, val)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, V) error); ok {
		r0 = rf(ctx, key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTieredStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockTieredStore_Set_Call[V interface{}] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - val V
func (_e *MockTieredStore_Expecter[V]) Set(ctx interface{}, key interface{}, val interface{}) *MockTieredStore_Set_Call[V] {
	return &MockTieredStore_Set_Call[V]{Call: _e.mock.On("Set", ctx, key, val)}
}

func (_c *MockTieredStore_Set_Call[V]) Run(run func(ctx context.Context, key string, val V)) *MockTieredStore_Set_Call[V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(V))
	})
	return _c
}

func (_c *MockTieredStore_Set_Call[V]) Return(_a0 error) *MockTieredStore_Set_Call[V] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTieredStore_Set_Call[V]) RunAndReturn(run func(context.Context, string, V) error) *MockTieredStore_Set_Call[V] {
	_c.Call.Return(run)
	return _c
}

// NewMockTieredStore creates a new instance of MockTieredStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTieredStore[V interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTieredStore[V] {
	mock := &MockTieredStore[V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
