// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/post"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockCache
func (_mock *MockCache) Get(ctx context.Context, id int64, loader func(context.Context) (*post.Post, error)) (*post.Post, error) {
	ret := _mock.Called(ctx, id, loader)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *post.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(context.Context) (*post.Post, error)) (*post.Post, error)); ok {
		return returnFunc(ctx, id, loader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(context.Context) (*post.Post, error)) *post.Post); ok {
		r0 = returnFunc(ctx, id, loader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(context.Context) (*post.Post, error)) error); ok {
		r1 = returnFunc(ctx, id, loader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - loader func(context.Context) (*post.Post, error)
func (_e *MockCache_Expecter) Get(ctx interface{}, id interface{}, loader interface{}) *MockCache_Get_Call {
	return &MockCache_Get_Call{Call: _e.mock.On("Get", ctx, id, loader)}
}

func (_c *MockCache_Get_Call) Run(run func(ctx context.Context, id int64, loader func(context.Context) (*post.Post, error))) *MockCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(context.Context) (*post.Post, error)
		if args[2] != nil {
			arg2 = args[2].(func(context.Context) (*post.Post, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_Get_Call) Return(post1 *post.Post, err error) *MockCache_Get_Call {
	_c.Call.Return(post1, err)
	return _c
}

func (_c *MockCache_Get_Call) RunAndReturn(run func(ctx context.Context, id int64, loader func(context.Context) (*post.Post, error)) (*post.Post, error)) *MockCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBatch provides a mock function for the type MockCache
func (_mock *MockCache) GetBatch(ctx context.Context, ids []int64, batchLoader func(context.Context, []int64) ([]*post.Post, error)) ([]*post.Post, error) {
	ret := _mock.Called(ctx, ids, batchLoader)

	if len(ret) == 0 {
		panic("no return value specified for GetBatch")
	}

	var r0 []*post.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64, func(context.Context, []int64) ([]*post.Post, error)) ([]*post.Post, error)); ok {
		return returnFunc(ctx, ids, batchLoader)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int64, func(context.Context, []int64) ([]*post.Post, error)) []*post.Post); ok {
		r0 = returnFunc(ctx, ids, batchLoader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*post.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int64, func(context.Context, []int64) ([]*post.Post, error)) error); ok {
		r1 = returnFunc(ctx, ids, batchLoader)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBatch'
type MockCache_GetBatch_Call struct {
	*mock.Call
}

// GetBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
//   - batchLoader func(context.Context, []int64) ([]*post.Post, error)
func (_e *MockCache_Expecter) GetBatch(ctx interface{}, ids interface{}, batchLoader interface{}) *MockCache_GetBatch_Call {
	return &MockCache_GetBatch_Call{Call: _e.mock.On("GetBatch", ctx, ids, batchLoader)}
}

func (_c *MockCache_GetBatch_Call) Run(run func(ctx context.Context, ids []int64, batchLoader func(context.Context, []int64) ([]*post.Post, error))) *MockCache_GetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int64
		if args[1] != nil {
			arg1 = args[1].([]int64)
		}
		var arg2 func(context.Context, []int64) ([]*post.Post, error)
		if args[2] != nil {
			arg2 = args[2].(func(context.Context, []int64) ([]*post.Post, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_GetBatch_Call) Return(posts []*post.Post, err error) *MockCache_GetBatch_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockCache_GetBatch_Call) RunAndReturn(run func(ctx context.Context, ids []int64, batchLoader func(context.Context, []int64) ([]*post.Post, error)) ([]*post.Post, error)) *MockCache_GetBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function for the type MockCache
func (_mock *MockCache) Invalidate(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockCache_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCache_Expecter) Invalidate(ctx interface{}, id interface{}) *MockCache_Invalidate_Call {
	return &MockCache_Invalidate_Call{Call: _e.mock.On("Invalidate", ctx, id)}
}

func (_c *MockCache_Invalidate_Call) Run(run func(ctx context.Context, id int64)) *MockCache_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_Invalidate_Call) Return(err error) *MockCache_Invalidate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Invalidate_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockCache_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}
