// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	post "air-social/internal/domain/post"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Create(ctx context.Context, _a1 *post.Post) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *post.Post) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *post.Post
func (_e *MockRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, _a1 *post.Post)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*post.Post))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *post.Post) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, postID
func (_m *MockRepository) GetByID(ctx context.Context, postID int64) (*post.Post, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*post.Post, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *post.Post); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockRepository_Expecter) GetByID(ctx interface{}, postID interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, postID)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(ctx context.Context, postID int64)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *post.Post, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*post.Post, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIDs provides a mock function with given fields: ctx, ids
func (_m *MockRepository) GetByIDs(ctx context.Context, ids []int64) ([]*post.Post, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetByIDs")
	}

	var r0 []*post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]*post.Post, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []*post.Post); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDs'
type MockRepository_GetByIDs_Call struct {
	*mock.Call
}

// GetByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int64
func (_e *MockRepository_Expecter) GetByIDs(ctx interface{}, ids interface{}) *MockRepository_GetByIDs_Call {
	return &MockRepository_GetByIDs_Call{Call: _e.mock.On("GetByIDs", ctx, ids)}
}

func (_c *MockRepository_GetByIDs_Call) Run(run func(ctx context.Context, ids []int64)) *MockRepository_GetByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockRepository_GetByIDs_Call) Return(_a0 []*post.Post, _a1 error) *MockRepository_GetByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByIDs_Call) RunAndReturn(run func(context.Context, []int64) ([]*post.Post, error)) *MockRepository_GetByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetDetail provides a mock function with given fields: ctx, postID
func (_m *MockRepository) GetDetail(ctx context.Context, postID int64) (*post.Post, error) {
	ret := _m.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for GetDetail")
	}

	var r0 *post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*post.Post, error)); ok {
		return rf(ctx, postID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *post.Post); ok {
		r0 = rf(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDetail'
type MockRepository_GetDetail_Call struct {
	*mock.Call
}

// GetDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
func (_e *MockRepository_Expecter) GetDetail(ctx interface{}, postID interface{}) *MockRepository_GetDetail_Call {
	return &MockRepository_GetDetail_Call{Call: _e.mock.On("GetDetail", ctx, postID)}
}

func (_c *MockRepository_GetDetail_Call) Run(run func(ctx context.Context, postID int64)) *MockRepository_GetDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_GetDetail_Call) Return(_a0 *post.Post, _a1 error) *MockRepository_GetDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetDetail_Call) RunAndReturn(run func(context.Context, int64) (*post.Post, error)) *MockRepository_GetDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostSharers provides a mock function with given fields: ctx, params
func (_m *MockRepository) GetPostSharers(ctx context.Context, params post.GetSharersParams) ([]post.Sharer, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPostSharers")
	}

	var r0 []post.Sharer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, post.GetSharersParams) ([]post.Sharer, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, post.GetSharersParams) []post.Sharer); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]post.Sharer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, post.GetSharersParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetPostSharers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostSharers'
type MockRepository_GetPostSharers_Call struct {
	*mock.Call
}

// GetPostSharers is a helper method to define mock.On call
//   - ctx context.Context
//   - params post.GetSharersParams
func (_e *MockRepository_Expecter) GetPostSharers(ctx interface{}, params interface{}) *MockRepository_GetPostSharers_Call {
	return &MockRepository_GetPostSharers_Call{Call: _e.mock.On("GetPostSharers", ctx, params)}
}

func (_c *MockRepository_GetPostSharers_Call) Run(run func(ctx context.Context, params post.GetSharersParams)) *MockRepository_GetPostSharers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(post.GetSharersParams))
	})
	return _c
}

func (_c *MockRepository_GetPostSharers_Call) Return(_a0 []post.Sharer, _a1 error) *MockRepository_GetPostSharers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetPostSharers_Call) RunAndReturn(run func(context.Context, post.GetSharersParams) ([]post.Sharer, error)) *MockRepository_GetPostSharers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPosts provides a mock function with given fields: ctx, params
func (_m *MockRepository) GetUserPosts(ctx context.Context, params post.GetCursorParams) ([]post.Post, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPosts")
	}

	var r0 []post.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, post.GetCursorParams) ([]post.Post, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, post.GetCursorParams) []post.Post); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]post.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, post.GetCursorParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUserPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPosts'
type MockRepository_GetUserPosts_Call struct {
	*mock.Call
}

// GetUserPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - params post.GetCursorParams
func (_e *MockRepository_Expecter) GetUserPosts(ctx interface{}, params interface{}) *MockRepository_GetUserPosts_Call {
	return &MockRepository_GetUserPosts_Call{Call: _e.mock.On("GetUserPosts", ctx, params)}
}

func (_c *MockRepository_GetUserPosts_Call) Run(run func(ctx context.Context, params post.GetCursorParams)) *MockRepository_GetUserPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(post.GetCursorParams))
	})
	return _c
}

func (_c *MockRepository_GetUserPosts_Call) Return(_a0 []post.Post, _a1 error) *MockRepository_GetUserPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUserPosts_Call) RunAndReturn(run func(context.Context, post.GetCursorParams) ([]post.Post, error)) *MockRepository_GetUserPosts_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) Update(ctx context.Context, _a1 *post.Post) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *post.Post) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *post.Post
func (_e *MockRepository_Expecter) Update(ctx interface{}, _a1 interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockRepository_Update_Call) Run(run func(ctx context.Context, _a1 *post.Post)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*post.Post))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(context.Context, *post.Post) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
