// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	stats "air-social/internal/domain/stats"
)

// MockStatsFetcher is an autogenerated mock type for the StatsFetcher type
type MockStatsFetcher struct {
	mock.Mock
}

type MockStatsFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatsFetcher) EXPECT() *MockStatsFetcher_Expecter {
	return &MockStatsFetcher_Expecter{mock: &_m.Mock}
}

// GetPostsStats provides a mock function with given fields: ctx, postIDs
func (_m *MockStatsFetcher) GetPostsStats(ctx context.Context, postIDs []int64) (map[int64]stats.PostStats, error) {
	ret := _m.Called(ctx, postIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetPostsStats")
	}

	var r0 map[int64]stats.PostStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (map[int64]stats.PostStats, error)); ok {
		return rf(ctx, postIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) map[int64]stats.PostStats); ok {
		r0 = rf(ctx, postIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]stats.PostStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, postIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStatsFetcher_GetPostsStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostsStats'
type MockStatsFetcher_GetPostsStats_Call struct {
	*mock.Call
}

// GetPostsStats is a helper method to define mock.On call
//   - ctx context.Context
//   - postIDs []int64
func (_e *MockStatsFetcher_Expecter) GetPostsStats(ctx interface{}, postIDs interface{}) *MockStatsFetcher_GetPostsStats_Call {
	return &MockStatsFetcher_GetPostsStats_Call{Call: _e.mock.On("GetPostsStats", ctx, postIDs)}
}

func (_c *MockStatsFetcher_GetPostsStats_Call) Run(run func(ctx context.Context, postIDs []int64)) *MockStatsFetcher_GetPostsStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockStatsFetcher_GetPostsStats_Call) Return(_a0 map[int64]stats.PostStats, _a1 error) *MockStatsFetcher_GetPostsStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStatsFetcher_GetPostsStats_Call) RunAndReturn(run func(context.Context, []int64) (map[int64]stats.PostStats, error)) *MockStatsFetcher_GetPostsStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStatsFetcher creates a new instance of MockStatsFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatsFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatsFetcher {
	mock := &MockStatsFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
