// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/common"
	"air-social/internal/domain/post"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CreatePost provides a mock function for the type MockUseCase
func (_mock *MockUseCase) CreatePost(ctx context.Context, params post.CreateParams) (*post.Post, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePost")
	}

	var r0 *post.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, post.CreateParams) (*post.Post, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, post.CreateParams) *post.Post); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, post.CreateParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_CreatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePost'
type MockUseCase_CreatePost_Call struct {
	*mock.Call
}

// CreatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - params post.CreateParams
func (_e *MockUseCase_Expecter) CreatePost(ctx interface{}, params interface{}) *MockUseCase_CreatePost_Call {
	return &MockUseCase_CreatePost_Call{Call: _e.mock.On("CreatePost", ctx, params)}
}

func (_c *MockUseCase_CreatePost_Call) Run(run func(ctx context.Context, params post.CreateParams)) *MockUseCase_CreatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 post.CreateParams
		if args[1] != nil {
			arg1 = args[1].(post.CreateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_CreatePost_Call) Return(post1 *post.Post, err error) *MockUseCase_CreatePost_Call {
	_c.Call.Return(post1, err)
	return _c
}

func (_c *MockUseCase_CreatePost_Call) RunAndReturn(run func(ctx context.Context, params post.CreateParams) (*post.Post, error)) *MockUseCase_CreatePost_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePost provides a mock function for the type MockUseCase
func (_mock *MockUseCase) DeletePost(ctx context.Context, postID int64, userID int64) error {
	ret := _mock.Called(ctx, postID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePost")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, postID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type MockUseCase_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - userID int64
func (_e *MockUseCase_Expecter) DeletePost(ctx interface{}, postID interface{}, userID interface{}) *MockUseCase_DeletePost_Call {
	return &MockUseCase_DeletePost_Call{Call: _e.mock.On("DeletePost", ctx, postID, userID)}
}

func (_c *MockUseCase_DeletePost_Call) Run(run func(ctx context.Context, postID int64, userID int64)) *MockUseCase_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_DeletePost_Call) Return(err error) *MockUseCase_DeletePost_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_DeletePost_Call) RunAndReturn(run func(ctx context.Context, postID int64, userID int64) error) *MockUseCase_DeletePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostDetail provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetPostDetail(ctx context.Context, postID int64, viewerID int64) (*post.Post, error) {
	ret := _mock.Called(ctx, postID, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPostDetail")
	}

	var r0 *post.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*post.Post, error)); ok {
		return returnFunc(ctx, postID, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *post.Post); ok {
		r0 = returnFunc(ctx, postID, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, postID, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetPostDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostDetail'
type MockUseCase_GetPostDetail_Call struct {
	*mock.Call
}

// GetPostDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - postID int64
//   - viewerID int64
func (_e *MockUseCase_Expecter) GetPostDetail(ctx interface{}, postID interface{}, viewerID interface{}) *MockUseCase_GetPostDetail_Call {
	return &MockUseCase_GetPostDetail_Call{Call: _e.mock.On("GetPostDetail", ctx, postID, viewerID)}
}

func (_c *MockUseCase_GetPostDetail_Call) Run(run func(ctx context.Context, postID int64, viewerID int64)) *MockUseCase_GetPostDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_GetPostDetail_Call) Return(post1 *post.Post, err error) *MockUseCase_GetPostDetail_Call {
	_c.Call.Return(post1, err)
	return _c
}

func (_c *MockUseCase_GetPostDetail_Call) RunAndReturn(run func(ctx context.Context, postID int64, viewerID int64) (*post.Post, error)) *MockUseCase_GetPostDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPosts provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetUserPosts(ctx context.Context, params post.GetCursorParams) (common.CursorPaginatedResult[post.Post, int64], error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPosts")
	}

	var r0 common.CursorPaginatedResult[post.Post, int64]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, post.GetCursorParams) (common.CursorPaginatedResult[post.Post, int64], error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, post.GetCursorParams) common.CursorPaginatedResult[post.Post, int64]); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(common.CursorPaginatedResult[post.Post, int64])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, post.GetCursorParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetUserPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPosts'
type MockUseCase_GetUserPosts_Call struct {
	*mock.Call
}

// GetUserPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - params post.GetCursorParams
func (_e *MockUseCase_Expecter) GetUserPosts(ctx interface{}, params interface{}) *MockUseCase_GetUserPosts_Call {
	return &MockUseCase_GetUserPosts_Call{Call: _e.mock.On("GetUserPosts", ctx, params)}
}

func (_c *MockUseCase_GetUserPosts_Call) Run(run func(ctx context.Context, params post.GetCursorParams)) *MockUseCase_GetUserPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 post.GetCursorParams
		if args[1] != nil {
			arg1 = args[1].(post.GetCursorParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetUserPosts_Call) Return(cursorPaginatedResult common.CursorPaginatedResult[post.Post, int64], err error) *MockUseCase_GetUserPosts_Call {
	_c.Call.Return(cursorPaginatedResult, err)
	return _c
}

func (_c *MockUseCase_GetUserPosts_Call) RunAndReturn(run func(ctx context.Context, params post.GetCursorParams) (common.CursorPaginatedResult[post.Post, int64], error)) *MockUseCase_GetUserPosts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePost provides a mock function for the type MockUseCase
func (_mock *MockUseCase) UpdatePost(ctx context.Context, params post.UpdateParams) (*post.Post, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePost")
	}

	var r0 *post.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, post.UpdateParams) (*post.Post, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, post.UpdateParams) *post.Post); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*post.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, post.UpdateParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_UpdatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePost'
type MockUseCase_UpdatePost_Call struct {
	*mock.Call
}

// UpdatePost is a helper method to define mock.On call
//   - ctx context.Context
//   - params post.UpdateParams
func (_e *MockUseCase_Expecter) UpdatePost(ctx interface{}, params interface{}) *MockUseCase_UpdatePost_Call {
	return &MockUseCase_UpdatePost_Call{Call: _e.mock.On("UpdatePost", ctx, params)}
}

func (_c *MockUseCase_UpdatePost_Call) Run(run func(ctx context.Context, params post.UpdateParams)) *MockUseCase_UpdatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 post.UpdateParams
		if args[1] != nil {
			arg1 = args[1].(post.UpdateParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_UpdatePost_Call) Return(post1 *post.Post, err error) *MockUseCase_UpdatePost_Call {
	_c.Call.Return(post1, err)
	return _c
}

func (_c *MockUseCase_UpdatePost_Call) RunAndReturn(run func(ctx context.Context, params post.UpdateParams) (*post.Post, error)) *MockUseCase_UpdatePost_Call {
	_c.Call.Return(run)
	return _c
}
