// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	user "air-social/internal/domain/user"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountUseCase is an autogenerated mock type for the AccountUseCase type
type MockAccountUseCase struct {
	mock.Mock
}

type MockAccountUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountUseCase) EXPECT() *MockAccountUseCase_Expecter {
	return &MockAccountUseCase_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: ctx, params
func (_m *MockAccountUseCase) Authenticate(ctx context.Context, params user.AuthenticateParams) (*user.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.AuthenticateParams) (*user.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.AuthenticateParams) *user.User); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.AuthenticateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUseCase_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockAccountUseCase_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.AuthenticateParams
func (_e *MockAccountUseCase_Expecter) Authenticate(ctx interface{}, params interface{}) *MockAccountUseCase_Authenticate_Call {
	return &MockAccountUseCase_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, params)}
}

func (_c *MockAccountUseCase_Authenticate_Call) Run(run func(ctx context.Context, params user.AuthenticateParams)) *MockAccountUseCase_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.AuthenticateParams))
	})
	return _c
}

func (_c *MockAccountUseCase_Authenticate_Call) Return(_a0 *user.User, _a1 error) *MockAccountUseCase_Authenticate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUseCase_Authenticate_Call) RunAndReturn(run func(context.Context, user.AuthenticateParams) (*user.User, error)) *MockAccountUseCase_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// ChangePassword provides a mock function with given fields: ctx, params
func (_m *MockAccountUseCase) ChangePassword(ctx context.Context, params user.ChangePasswordParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ChangePasswordParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUseCase_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAccountUseCase_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.ChangePasswordParams
func (_e *MockAccountUseCase_Expecter) ChangePassword(ctx interface{}, params interface{}) *MockAccountUseCase_ChangePassword_Call {
	return &MockAccountUseCase_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, params)}
}

func (_c *MockAccountUseCase_ChangePassword_Call) Run(run func(ctx context.Context, params user.ChangePasswordParams)) *MockAccountUseCase_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.ChangePasswordParams))
	})
	return _c
}

func (_c *MockAccountUseCase_ChangePassword_Call) Return(_a0 error) *MockAccountUseCase_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUseCase_ChangePassword_Call) RunAndReturn(run func(context.Context, user.ChangePasswordParams) error) *MockAccountUseCase_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, params
func (_m *MockAccountUseCase) CreateUser(ctx context.Context, params user.CreateParams) (*user.User, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.CreateParams) (*user.User, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.CreateParams) *user.User); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.CreateParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountUseCase_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAccountUseCase_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.CreateParams
func (_e *MockAccountUseCase_Expecter) CreateUser(ctx interface{}, params interface{}) *MockAccountUseCase_CreateUser_Call {
	return &MockAccountUseCase_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockAccountUseCase_CreateUser_Call) Run(run func(ctx context.Context, params user.CreateParams)) *MockAccountUseCase_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.CreateParams))
	})
	return _c
}

func (_c *MockAccountUseCase_CreateUser_Call) Return(_a0 *user.User, _a1 error) *MockAccountUseCase_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountUseCase_CreateUser_Call) RunAndReturn(run func(context.Context, user.CreateParams) (*user.User, error)) *MockAccountUseCase_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: ctx, params
func (_m *MockAccountUseCase) ResetPassword(ctx context.Context, params user.ResetPasswordParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.ResetPasswordParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUseCase_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAccountUseCase_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.ResetPasswordParams
func (_e *MockAccountUseCase_Expecter) ResetPassword(ctx interface{}, params interface{}) *MockAccountUseCase_ResetPassword_Call {
	return &MockAccountUseCase_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, params)}
}

func (_c *MockAccountUseCase_ResetPassword_Call) Run(run func(ctx context.Context, params user.ResetPasswordParams)) *MockAccountUseCase_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.ResetPasswordParams))
	})
	return _c
}

func (_c *MockAccountUseCase_ResetPassword_Call) Return(_a0 error) *MockAccountUseCase_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUseCase_ResetPassword_Call) RunAndReturn(run func(context.Context, user.ResetPasswordParams) error) *MockAccountUseCase_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function with given fields: ctx, email
func (_m *MockAccountUseCase) VerifyEmail(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountUseCase_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type MockAccountUseCase_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAccountUseCase_Expecter) VerifyEmail(ctx interface{}, email interface{}) *MockAccountUseCase_VerifyEmail_Call {
	return &MockAccountUseCase_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, email)}
}

func (_c *MockAccountUseCase_VerifyEmail_Call) Run(run func(ctx context.Context, email string)) *MockAccountUseCase_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountUseCase_VerifyEmail_Call) Return(_a0 error) *MockAccountUseCase_VerifyEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountUseCase_VerifyEmail_Call) RunAndReturn(run func(context.Context, string) error) *MockAccountUseCase_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountUseCase creates a new instance of MockAccountUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountUseCase {
	mock := &MockAccountUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
