// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheInvalidator creates a new instance of MockCacheInvalidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheInvalidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheInvalidator {
	mock := &MockCacheInvalidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheInvalidator is an autogenerated mock type for the CacheInvalidator type
type MockCacheInvalidator struct {
	mock.Mock
}

type MockCacheInvalidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheInvalidator) EXPECT() *MockCacheInvalidator_Expecter {
	return &MockCacheInvalidator_Expecter{mock: &_m.Mock}
}

// Invalidate provides a mock function for the type MockCacheInvalidator
func (_mock *MockCacheInvalidator) Invalidate(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheInvalidator_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockCacheInvalidator_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacheInvalidator_Expecter) Invalidate(ctx interface{}, key interface{}) *MockCacheInvalidator_Invalidate_Call {
	return &MockCacheInvalidator_Invalidate_Call{Call: _e.mock.On("Invalidate", ctx, key)}
}

func (_c *MockCacheInvalidator_Invalidate_Call) Run(run func(ctx context.Context, key string)) *MockCacheInvalidator_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheInvalidator_Invalidate_Call) Return(err error) *MockCacheInvalidator_Invalidate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheInvalidator_Invalidate_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCacheInvalidator_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}
