// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	follow "air-social/internal/domain/follow"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountFollowers provides a mock function with given fields: ctx, userID
func (_m *MockRepository) CountFollowers(ctx context.Context, userID int64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountFollowers")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountFollowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountFollowers'
type MockRepository_CountFollowers_Call struct {
	*mock.Call
}

// CountFollowers is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRepository_Expecter) CountFollowers(ctx interface{}, userID interface{}) *MockRepository_CountFollowers_Call {
	return &MockRepository_CountFollowers_Call{Call: _e.mock.On("CountFollowers", ctx, userID)}
}

func (_c *MockRepository_CountFollowers_Call) Run(run func(ctx context.Context, userID int64)) *MockRepository_CountFollowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_CountFollowers_Call) Return(_a0 int64, _a1 error) *MockRepository_CountFollowers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountFollowers_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockRepository_CountFollowers_Call {
	_c.Call.Return(run)
	return _c
}

// CountFollowings provides a mock function with given fields: ctx, userID
func (_m *MockRepository) CountFollowings(ctx context.Context, userID int64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountFollowings")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CountFollowings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountFollowings'
type MockRepository_CountFollowings_Call struct {
	*mock.Call
}

// CountFollowings is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRepository_Expecter) CountFollowings(ctx interface{}, userID interface{}) *MockRepository_CountFollowings_Call {
	return &MockRepository_CountFollowings_Call{Call: _e.mock.On("CountFollowings", ctx, userID)}
}

func (_c *MockRepository_CountFollowings_Call) Run(run func(ctx context.Context, userID int64)) *MockRepository_CountFollowings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_CountFollowings_Call) Return(_a0 int64, _a1 error) *MockRepository_CountFollowings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CountFollowings_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockRepository_CountFollowings_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, followerID, followeeID
func (_m *MockRepository) Create(ctx context.Context, followerID int64, followeeID int64) error {
	ret := _m.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID int64
//   - followeeID int64
func (_e *MockRepository_Expecter) Create(ctx interface{}, followerID interface{}, followeeID interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, followerID, followeeID)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, followerID int64, followeeID int64)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, followerID, followeeID
func (_m *MockRepository) Delete(ctx context.Context, followerID int64, followeeID int64) error {
	ret := _m.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID int64
//   - followeeID int64
func (_e *MockRepository_Expecter) Delete(ctx interface{}, followerID interface{}, followeeID interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, followerID, followeeID)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, followerID int64, followeeID int64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowerIDs provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetFollowerIDs(ctx context.Context, userID int64) ([]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowerIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetFollowerIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowerIDs'
type MockRepository_GetFollowerIDs_Call struct {
	*mock.Call
}

// GetFollowerIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRepository_Expecter) GetFollowerIDs(ctx interface{}, userID interface{}) *MockRepository_GetFollowerIDs_Call {
	return &MockRepository_GetFollowerIDs_Call{Call: _e.mock.On("GetFollowerIDs", ctx, userID)}
}

func (_c *MockRepository_GetFollowerIDs_Call) Run(run func(ctx context.Context, userID int64)) *MockRepository_GetFollowerIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_GetFollowerIDs_Call) Return(_a0 []int64, _a1 error) *MockRepository_GetFollowerIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetFollowerIDs_Call) RunAndReturn(run func(context.Context, int64) ([]int64, error)) *MockRepository_GetFollowerIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowers provides a mock function with given fields: ctx, params
func (_m *MockRepository) GetFollowers(ctx context.Context, params follow.GetFollowsParams) ([]follow.FollowUser, int64, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowers")
	}

	var r0 []follow.FollowUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) ([]follow.FollowUser, int64, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) []follow.FollowUser); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]follow.FollowUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, follow.GetFollowsParams) int64); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, follow.GetFollowsParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_GetFollowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowers'
type MockRepository_GetFollowers_Call struct {
	*mock.Call
}

// GetFollowers is a helper method to define mock.On call
//   - ctx context.Context
//   - params follow.GetFollowsParams
func (_e *MockRepository_Expecter) GetFollowers(ctx interface{}, params interface{}) *MockRepository_GetFollowers_Call {
	return &MockRepository_GetFollowers_Call{Call: _e.mock.On("GetFollowers", ctx, params)}
}

func (_c *MockRepository_GetFollowers_Call) Run(run func(ctx context.Context, params follow.GetFollowsParams)) *MockRepository_GetFollowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(follow.GetFollowsParams))
	})
	return _c
}

func (_c *MockRepository_GetFollowers_Call) Return(_a0 []follow.FollowUser, _a1 int64, _a2 error) *MockRepository_GetFollowers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_GetFollowers_Call) RunAndReturn(run func(context.Context, follow.GetFollowsParams) ([]follow.FollowUser, int64, error)) *MockRepository_GetFollowers_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowings provides a mock function with given fields: ctx, params
func (_m *MockRepository) GetFollowings(ctx context.Context, params follow.GetFollowsParams) ([]follow.FollowUser, int64, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowings")
	}

	var r0 []follow.FollowUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) ([]follow.FollowUser, int64, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) []follow.FollowUser); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]follow.FollowUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, follow.GetFollowsParams) int64); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, follow.GetFollowsParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRepository_GetFollowings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowings'
type MockRepository_GetFollowings_Call struct {
	*mock.Call
}

// GetFollowings is a helper method to define mock.On call
//   - ctx context.Context
//   - params follow.GetFollowsParams
func (_e *MockRepository_Expecter) GetFollowings(ctx interface{}, params interface{}) *MockRepository_GetFollowings_Call {
	return &MockRepository_GetFollowings_Call{Call: _e.mock.On("GetFollowings", ctx, params)}
}

func (_c *MockRepository_GetFollowings_Call) Run(run func(ctx context.Context, params follow.GetFollowsParams)) *MockRepository_GetFollowings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(follow.GetFollowsParams))
	})
	return _c
}

func (_c *MockRepository_GetFollowings_Call) Return(_a0 []follow.FollowUser, _a1 int64, _a2 error) *MockRepository_GetFollowings_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRepository_GetFollowings_Call) RunAndReturn(run func(context.Context, follow.GetFollowsParams) ([]follow.FollowUser, int64, error)) *MockRepository_GetFollowings_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationship provides a mock function with given fields: ctx, userID, targetID
func (_m *MockRepository) GetRelationship(ctx context.Context, userID int64, targetID int64) (follow.Relationship, error) {
	ret := _m.Called(ctx, userID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationship")
	}

	var r0 follow.Relationship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (follow.Relationship, error)); ok {
		return rf(ctx, userID, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) follow.Relationship); ok {
		r0 = rf(ctx, userID, targetID)
	} else {
		r0 = ret.Get(0).(follow.Relationship)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetRelationship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationship'
type MockRepository_GetRelationship_Call struct {
	*mock.Call
}

// GetRelationship is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - targetID int64
func (_e *MockRepository_Expecter) GetRelationship(ctx interface{}, userID interface{}, targetID interface{}) *MockRepository_GetRelationship_Call {
	return &MockRepository_GetRelationship_Call{Call: _e.mock.On("GetRelationship", ctx, userID, targetID)}
}

func (_c *MockRepository_GetRelationship_Call) Run(run func(ctx context.Context, userID int64, targetID int64)) *MockRepository_GetRelationship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRepository_GetRelationship_Call) Return(_a0 follow.Relationship, _a1 error) *MockRepository_GetRelationship_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetRelationship_Call) RunAndReturn(run func(context.Context, int64, int64) (follow.Relationship, error)) *MockRepository_GetRelationship_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationships provides a mock function with given fields: ctx, userID, targetIDs
func (_m *MockRepository) GetRelationships(ctx context.Context, userID int64, targetIDs []int64) (map[int64]follow.Relationship, error) {
	ret := _m.Called(ctx, userID, targetIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationships")
	}

	var r0 map[int64]follow.Relationship
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) (map[int64]follow.Relationship, error)); ok {
		return rf(ctx, userID, targetIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) map[int64]follow.Relationship); ok {
		r0 = rf(ctx, userID, targetIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]follow.Relationship)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, []int64) error); ok {
		r1 = rf(ctx, userID, targetIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetRelationships_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationships'
type MockRepository_GetRelationships_Call struct {
	*mock.Call
}

// GetRelationships is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - targetIDs []int64
func (_e *MockRepository_Expecter) GetRelationships(ctx interface{}, userID interface{}, targetIDs interface{}) *MockRepository_GetRelationships_Call {
	return &MockRepository_GetRelationships_Call{Call: _e.mock.On("GetRelationships", ctx, userID, targetIDs)}
}

func (_c *MockRepository_GetRelationships_Call) Run(run func(ctx context.Context, userID int64, targetIDs []int64)) *MockRepository_GetRelationships_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64))
	})
	return _c
}

func (_c *MockRepository_GetRelationships_Call) Return(_a0 map[int64]follow.Relationship, _a1 error) *MockRepository_GetRelationships_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetRelationships_Call) RunAndReturn(run func(context.Context, int64, []int64) (map[int64]follow.Relationship, error)) *MockRepository_GetRelationships_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
