// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/common"
	"air-social/internal/domain/follow"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// Follow provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Follow(ctx context.Context, followerID int64, followeeID int64) error {
	ret := _mock.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type MockUseCase_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID int64
//   - followeeID int64
func (_e *MockUseCase_Expecter) Follow(ctx interface{}, followerID interface{}, followeeID interface{}) *MockUseCase_Follow_Call {
	return &MockUseCase_Follow_Call{Call: _e.mock.On("Follow", ctx, followerID, followeeID)}
}

func (_c *MockUseCase_Follow_Call) Run(run func(ctx context.Context, followerID int64, followeeID int64)) *MockUseCase_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_Follow_Call) Return(err error) *MockUseCase_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_Follow_Call) RunAndReturn(run func(ctx context.Context, followerID int64, followeeID int64) error) *MockUseCase_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowers provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetFollowers(ctx context.Context, params follow.GetFollowsParams) (common.OffsetPaginatedResult[follow.FollowUser], error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowers")
	}

	var r0 common.OffsetPaginatedResult[follow.FollowUser]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) (common.OffsetPaginatedResult[follow.FollowUser], error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) common.OffsetPaginatedResult[follow.FollowUser]); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(common.OffsetPaginatedResult[follow.FollowUser])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, follow.GetFollowsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetFollowers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowers'
type MockUseCase_GetFollowers_Call struct {
	*mock.Call
}

// GetFollowers is a helper method to define mock.On call
//   - ctx context.Context
//   - params follow.GetFollowsParams
func (_e *MockUseCase_Expecter) GetFollowers(ctx interface{}, params interface{}) *MockUseCase_GetFollowers_Call {
	return &MockUseCase_GetFollowers_Call{Call: _e.mock.On("GetFollowers", ctx, params)}
}

func (_c *MockUseCase_GetFollowers_Call) Run(run func(ctx context.Context, params follow.GetFollowsParams)) *MockUseCase_GetFollowers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 follow.GetFollowsParams
		if args[1] != nil {
			arg1 = args[1].(follow.GetFollowsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetFollowers_Call) Return(offsetPaginatedResult common.OffsetPaginatedResult[follow.FollowUser], err error) *MockUseCase_GetFollowers_Call {
	_c.Call.Return(offsetPaginatedResult, err)
	return _c
}

func (_c *MockUseCase_GetFollowers_Call) RunAndReturn(run func(ctx context.Context, params follow.GetFollowsParams) (common.OffsetPaginatedResult[follow.FollowUser], error)) *MockUseCase_GetFollowers_Call {
	_c.Call.Return(run)
	return _c
}

// GetFollowings provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetFollowings(ctx context.Context, params follow.GetFollowsParams) (common.OffsetPaginatedResult[follow.FollowUser], error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetFollowings")
	}

	var r0 common.OffsetPaginatedResult[follow.FollowUser]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) (common.OffsetPaginatedResult[follow.FollowUser], error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, follow.GetFollowsParams) common.OffsetPaginatedResult[follow.FollowUser]); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(common.OffsetPaginatedResult[follow.FollowUser])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, follow.GetFollowsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetFollowings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFollowings'
type MockUseCase_GetFollowings_Call struct {
	*mock.Call
}

// GetFollowings is a helper method to define mock.On call
//   - ctx context.Context
//   - params follow.GetFollowsParams
func (_e *MockUseCase_Expecter) GetFollowings(ctx interface{}, params interface{}) *MockUseCase_GetFollowings_Call {
	return &MockUseCase_GetFollowings_Call{Call: _e.mock.On("GetFollowings", ctx, params)}
}

func (_c *MockUseCase_GetFollowings_Call) Run(run func(ctx context.Context, params follow.GetFollowsParams)) *MockUseCase_GetFollowings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 follow.GetFollowsParams
		if args[1] != nil {
			arg1 = args[1].(follow.GetFollowsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetFollowings_Call) Return(offsetPaginatedResult common.OffsetPaginatedResult[follow.FollowUser], err error) *MockUseCase_GetFollowings_Call {
	_c.Call.Return(offsetPaginatedResult, err)
	return _c
}

func (_c *MockUseCase_GetFollowings_Call) RunAndReturn(run func(ctx context.Context, params follow.GetFollowsParams) (common.OffsetPaginatedResult[follow.FollowUser], error)) *MockUseCase_GetFollowings_Call {
	_c.Call.Return(run)
	return _c
}

// GetRelationship provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetRelationship(ctx context.Context, userID int64, targetID int64) (follow.Relationship, error) {
	ret := _mock.Called(ctx, userID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for GetRelationship")
	}

	var r0 follow.Relationship
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (follow.Relationship, error)); ok {
		return returnFunc(ctx, userID, targetID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) follow.Relationship); ok {
		r0 = returnFunc(ctx, userID, targetID)
	} else {
		r0 = ret.Get(0).(follow.Relationship)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, userID, targetID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetRelationship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelationship'
type MockUseCase_GetRelationship_Call struct {
	*mock.Call
}

// GetRelationship is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - targetID int64
func (_e *MockUseCase_Expecter) GetRelationship(ctx interface{}, userID interface{}, targetID interface{}) *MockUseCase_GetRelationship_Call {
	return &MockUseCase_GetRelationship_Call{Call: _e.mock.On("GetRelationship", ctx, userID, targetID)}
}

func (_c *MockUseCase_GetRelationship_Call) Run(run func(ctx context.Context, userID int64, targetID int64)) *MockUseCase_GetRelationship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_GetRelationship_Call) Return(relationship follow.Relationship, err error) *MockUseCase_GetRelationship_Call {
	_c.Call.Return(relationship, err)
	return _c
}

func (_c *MockUseCase_GetRelationship_Call) RunAndReturn(run func(ctx context.Context, userID int64, targetID int64) (follow.Relationship, error)) *MockUseCase_GetRelationship_Call {
	_c.Call.Return(run)
	return _c
}

// Unfollow provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Unfollow(ctx context.Context, followerID int64, followeeID int64) error {
	ret := _mock.Called(ctx, followerID, followeeID)

	if len(ret) == 0 {
		panic("no return value specified for Unfollow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = returnFunc(ctx, followerID, followeeID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_Unfollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfollow'
type MockUseCase_Unfollow_Call struct {
	*mock.Call
}

// Unfollow is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID int64
//   - followeeID int64
func (_e *MockUseCase_Expecter) Unfollow(ctx interface{}, followerID interface{}, followeeID interface{}) *MockUseCase_Unfollow_Call {
	return &MockUseCase_Unfollow_Call{Call: _e.mock.On("Unfollow", ctx, followerID, followeeID)}
}

func (_c *MockUseCase_Unfollow_Call) Run(run func(ctx context.Context, followerID int64, followeeID int64)) *MockUseCase_Unfollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUseCase_Unfollow_Call) Return(err error) *MockUseCase_Unfollow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_Unfollow_Call) RunAndReturn(run func(ctx context.Context, followerID int64, followeeID int64) error) *MockUseCase_Unfollow_Call {
	_c.Call.Return(run)
	return _c
}
