// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	user "air-social/internal/domain/user"
)

// MockUserFetcher is an autogenerated mock type for the UserFetcher type
type MockUserFetcher struct {
	mock.Mock
}

type MockUserFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserFetcher) EXPECT() *MockUserFetcher_Expecter {
	return &MockUserFetcher_Expecter{mock: &_m.Mock}
}

// GetSummary provides a mock function with given fields: ctx, id
func (_m *MockUserFetcher) GetSummary(ctx context.Context, id int64) (*user.UserSummary, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *user.UserSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*user.UserSummary, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *user.UserSummary); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserFetcher_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type MockUserFetcher_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserFetcher_Expecter) GetSummary(ctx interface{}, id interface{}) *MockUserFetcher_GetSummary_Call {
	return &MockUserFetcher_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, id)}
}

func (_c *MockUserFetcher_GetSummary_Call) Run(run func(ctx context.Context, id int64)) *MockUserFetcher_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockUserFetcher_GetSummary_Call) Return(_a0 *user.UserSummary, _a1 error) *MockUserFetcher_GetSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserFetcher_GetSummary_Call) RunAndReturn(run func(context.Context, int64) (*user.UserSummary, error)) *MockUserFetcher_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserFetcher creates a new instance of MockUserFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserFetcher {
	mock := &MockUserFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
