// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// ClearSyncedFields provides a mock function for the type MockCache
func (_mock *MockCache) ClearSyncedFields(ctx context.Context, state string, syncData map[int64]int64) error {
	ret := _mock.Called(ctx, state, syncData)

	if len(ret) == 0 {
		panic("no return value specified for ClearSyncedFields")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[int64]int64) error); ok {
		r0 = returnFunc(ctx, state, syncData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_ClearSyncedFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSyncedFields'
type MockCache_ClearSyncedFields_Call struct {
	*mock.Call
}

// ClearSyncedFields is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - syncData map[int64]int64
func (_e *MockCache_Expecter) ClearSyncedFields(ctx interface{}, state interface{}, syncData interface{}) *MockCache_ClearSyncedFields_Call {
	return &MockCache_ClearSyncedFields_Call{Call: _e.mock.On("ClearSyncedFields", ctx, state, syncData)}
}

func (_c *MockCache_ClearSyncedFields_Call) Run(run func(ctx context.Context, state string, syncData map[int64]int64)) *MockCache_ClearSyncedFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[int64]int64
		if args[2] != nil {
			arg2 = args[2].(map[int64]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_ClearSyncedFields_Call) Return(err error) *MockCache_ClearSyncedFields_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_ClearSyncedFields_Call) RunAndReturn(run func(ctx context.Context, state string, syncData map[int64]int64) error) *MockCache_ClearSyncedFields_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatsHash provides a mock function for the type MockCache
func (_mock *MockCache) GetStatsHash(ctx context.Context, state string) (map[int64]int64, error) {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsHash")
	}

	var r0 map[int64]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (map[int64]int64, error)); ok {
		return returnFunc(ctx, state)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) map[int64]int64); ok {
		r0 = returnFunc(ctx, state)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetStatsHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsHash'
type MockCache_GetStatsHash_Call struct {
	*mock.Call
}

// GetStatsHash is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *MockCache_Expecter) GetStatsHash(ctx interface{}, state interface{}) *MockCache_GetStatsHash_Call {
	return &MockCache_GetStatsHash_Call{Call: _e.mock.On("GetStatsHash", ctx, state)}
}

func (_c *MockCache_GetStatsHash_Call) Run(run func(ctx context.Context, state string)) *MockCache_GetStatsHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_GetStatsHash_Call) Return(int64ToInt64 map[int64]int64, err error) *MockCache_GetStatsHash_Call {
	_c.Call.Return(int64ToInt64, err)
	return _c
}

func (_c *MockCache_GetStatsHash_Call) RunAndReturn(run func(ctx context.Context, state string) (map[int64]int64, error)) *MockCache_GetStatsHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatsOffsets provides a mock function for the type MockCache
func (_mock *MockCache) GetStatsOffsets(ctx context.Context, state string, ids []int64) (map[int64]int64, error) {
	ret := _mock.Called(ctx, state, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetStatsOffsets")
	}

	var r0 map[int64]int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int64) (map[int64]int64, error)); ok {
		return returnFunc(ctx, state, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []int64) map[int64]int64); ok {
		r0 = returnFunc(ctx, state, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int64]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []int64) error); ok {
		r1 = returnFunc(ctx, state, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetStatsOffsets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatsOffsets'
type MockCache_GetStatsOffsets_Call struct {
	*mock.Call
}

// GetStatsOffsets is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - ids []int64
func (_e *MockCache_Expecter) GetStatsOffsets(ctx interface{}, state interface{}, ids interface{}) *MockCache_GetStatsOffsets_Call {
	return &MockCache_GetStatsOffsets_Call{Call: _e.mock.On("GetStatsOffsets", ctx, state, ids)}
}

func (_c *MockCache_GetStatsOffsets_Call) Run(run func(ctx context.Context, state string, ids []int64)) *MockCache_GetStatsOffsets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []int64
		if args[2] != nil {
			arg2 = args[2].([]int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCache_GetStatsOffsets_Call) Return(int64ToInt64 map[int64]int64, err error) *MockCache_GetStatsOffsets_Call {
	_c.Call.Return(int64ToInt64, err)
	return _c
}

func (_c *MockCache_GetStatsOffsets_Call) RunAndReturn(run func(ctx context.Context, state string, ids []int64) (map[int64]int64, error)) *MockCache_GetStatsOffsets_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatsHash provides a mock function for the type MockCache
func (_mock *MockCache) UpdateStatsHash(ctx context.Context, state string, id int64, incr int64) error {
	ret := _mock.Called(ctx, state, id, incr)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatsHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, int64) error); ok {
		r0 = returnFunc(ctx, state, id, incr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_UpdateStatsHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatsHash'
type MockCache_UpdateStatsHash_Call struct {
	*mock.Call
}

// UpdateStatsHash is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - id int64
//   - incr int64
func (_e *MockCache_Expecter) UpdateStatsHash(ctx interface{}, state interface{}, id interface{}, incr interface{}) *MockCache_UpdateStatsHash_Call {
	return &MockCache_UpdateStatsHash_Call{Call: _e.mock.On("UpdateStatsHash", ctx, state, id, incr)}
}

func (_c *MockCache_UpdateStatsHash_Call) Run(run func(ctx context.Context, state string, id int64, incr int64)) *MockCache_UpdateStatsHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCache_UpdateStatsHash_Call) Return(err error) *MockCache_UpdateStatsHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_UpdateStatsHash_Call) RunAndReturn(run func(ctx context.Context, state string, id int64, incr int64) error) *MockCache_UpdateStatsHash_Call {
	_c.Call.Return(run)
	return _c
}
