// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/search"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// SearchPosts provides a mock function for the type MockRepository
func (_mock *MockRepository) SearchPosts(ctx context.Context, params search.PostsParams) ([]search.Post, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchPosts")
	}

	var r0 []search.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.PostsParams) ([]search.Post, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.PostsParams) []search.Post); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]search.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, search.PostsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SearchPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPosts'
type MockRepository_SearchPosts_Call struct {
	*mock.Call
}

// SearchPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - params search.PostsParams
func (_e *MockRepository_Expecter) SearchPosts(ctx interface{}, params interface{}) *MockRepository_SearchPosts_Call {
	return &MockRepository_SearchPosts_Call{Call: _e.mock.On("SearchPosts", ctx, params)}
}

func (_c *MockRepository_SearchPosts_Call) Run(run func(ctx context.Context, params search.PostsParams)) *MockRepository_SearchPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 search.PostsParams
		if args[1] != nil {
			arg1 = args[1].(search.PostsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SearchPosts_Call) Return(posts []search.Post, err error) *MockRepository_SearchPosts_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockRepository_SearchPosts_Call) RunAndReturn(run func(ctx context.Context, params search.PostsParams) ([]search.Post, error)) *MockRepository_SearchPosts_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function for the type MockRepository
func (_mock *MockRepository) SearchUsers(ctx context.Context, params search.UsersParams) ([]search.User, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []search.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.UsersParams) ([]search.User, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, search.UsersParams) []search.User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]search.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, search.UsersParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockRepository_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - params search.UsersParams
func (_e *MockRepository_Expecter) SearchUsers(ctx interface{}, params interface{}) *MockRepository_SearchUsers_Call {
	return &MockRepository_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, params)}
}

func (_c *MockRepository_SearchUsers_Call) Run(run func(ctx context.Context, params search.UsersParams)) *MockRepository_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 search.UsersParams
		if args[1] != nil {
			arg1 = args[1].(search.UsersParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SearchUsers_Call) Return(users []search.User, err error) *MockRepository_SearchUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_SearchUsers_Call) RunAndReturn(run func(ctx context.Context, params search.UsersParams) ([]search.User, error)) *MockRepository_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}
