// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	common "air-social/internal/domain/common"
	context "context"

	mock "github.com/stretchr/testify/mock"

	post "air-social/internal/domain/post"

	search "air-social/internal/domain/search"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// SearchPosts provides a mock function with given fields: ctx, params
func (_m *MockUseCase) SearchPosts(ctx context.Context, params search.PostsParams) (common.CursorPaginatedResult[*post.Post, int64], error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchPosts")
	}

	var r0 common.CursorPaginatedResult[*post.Post, int64]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, search.PostsParams) (common.CursorPaginatedResult[*post.Post, int64], error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, search.PostsParams) common.CursorPaginatedResult[*post.Post, int64]); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(common.CursorPaginatedResult[*post.Post, int64])
	}

	if rf, ok := ret.Get(1).(func(context.Context, search.PostsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_SearchPosts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPosts'
type MockUseCase_SearchPosts_Call struct {
	*mock.Call
}

// SearchPosts is a helper method to define mock.On call
//   - ctx context.Context
//   - params search.PostsParams
func (_e *MockUseCase_Expecter) SearchPosts(ctx interface{}, params interface{}) *MockUseCase_SearchPosts_Call {
	return &MockUseCase_SearchPosts_Call{Call: _e.mock.On("SearchPosts", ctx, params)}
}

func (_c *MockUseCase_SearchPosts_Call) Run(run func(ctx context.Context, params search.PostsParams)) *MockUseCase_SearchPosts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(search.PostsParams))
	})
	return _c
}

func (_c *MockUseCase_SearchPosts_Call) Return(_a0 common.CursorPaginatedResult[*post.Post, int64], _a1 error) *MockUseCase_SearchPosts_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_SearchPosts_Call) RunAndReturn(run func(context.Context, search.PostsParams) (common.CursorPaginatedResult[*post.Post, int64], error)) *MockUseCase_SearchPosts_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, params
func (_m *MockUseCase) SearchUsers(ctx context.Context, params search.UsersParams) (common.CursorPaginatedResult[search.User, int64], error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 common.CursorPaginatedResult[search.User, int64]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, search.UsersParams) (common.CursorPaginatedResult[search.User, int64], error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, search.UsersParams) common.CursorPaginatedResult[search.User, int64]); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(common.CursorPaginatedResult[search.User, int64])
	}

	if rf, ok := ret.Get(1).(func(context.Context, search.UsersParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUseCase_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - params search.UsersParams
func (_e *MockUseCase_Expecter) SearchUsers(ctx interface{}, params interface{}) *MockUseCase_SearchUsers_Call {
	return &MockUseCase_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, params)}
}

func (_c *MockUseCase_SearchUsers_Call) Run(run func(ctx context.Context, params search.UsersParams)) *MockUseCase_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(search.UsersParams))
	})
	return _c
}

func (_c *MockUseCase_SearchUsers_Call) Return(_a0 common.CursorPaginatedResult[search.User, int64], _a1 error) *MockUseCase_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_SearchUsers_Call) RunAndReturn(run func(context.Context, search.UsersParams) (common.CursorPaginatedResult[search.User, int64], error)) *MockUseCase_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
