// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSystemProvider is an autogenerated mock type for the SystemProvider type
type MockSystemProvider struct {
	mock.Mock
}

type MockSystemProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemProvider) EXPECT() *MockSystemProvider_Expecter {
	return &MockSystemProvider_Expecter{mock: &_m.Mock}
}

// MinioConsoleURL provides a mock function with no fields
func (_m *MockSystemProvider) MinioConsoleURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MinioConsoleURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSystemProvider_MinioConsoleURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MinioConsoleURL'
type MockSystemProvider_MinioConsoleURL_Call struct {
	*mock.Call
}

// MinioConsoleURL is a helper method to define mock.On call
func (_e *MockSystemProvider_Expecter) MinioConsoleURL() *MockSystemProvider_MinioConsoleURL_Call {
	return &MockSystemProvider_MinioConsoleURL_Call{Call: _e.mock.On("MinioConsoleURL")}
}

func (_c *MockSystemProvider_MinioConsoleURL_Call) Run(run func()) *MockSystemProvider_MinioConsoleURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemProvider_MinioConsoleURL_Call) Return(_a0 string) *MockSystemProvider_MinioConsoleURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemProvider_MinioConsoleURL_Call) RunAndReturn(run func() string) *MockSystemProvider_MinioConsoleURL_Call {
	_c.Call.Return(run)
	return _c
}

// RabbitMQDashboardURL provides a mock function with no fields
func (_m *MockSystemProvider) RabbitMQDashboardURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RabbitMQDashboardURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSystemProvider_RabbitMQDashboardURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RabbitMQDashboardURL'
type MockSystemProvider_RabbitMQDashboardURL_Call struct {
	*mock.Call
}

// RabbitMQDashboardURL is a helper method to define mock.On call
func (_e *MockSystemProvider_Expecter) RabbitMQDashboardURL() *MockSystemProvider_RabbitMQDashboardURL_Call {
	return &MockSystemProvider_RabbitMQDashboardURL_Call{Call: _e.mock.On("RabbitMQDashboardURL")}
}

func (_c *MockSystemProvider_RabbitMQDashboardURL_Call) Run(run func()) *MockSystemProvider_RabbitMQDashboardURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemProvider_RabbitMQDashboardURL_Call) Return(_a0 string) *MockSystemProvider_RabbitMQDashboardURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemProvider_RabbitMQDashboardURL_Call) RunAndReturn(run func() string) *MockSystemProvider_RabbitMQDashboardURL_Call {
	_c.Call.Return(run)
	return _c
}

// SwaggerURL provides a mock function with no fields
func (_m *MockSystemProvider) SwaggerURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SwaggerURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSystemProvider_SwaggerURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SwaggerURL'
type MockSystemProvider_SwaggerURL_Call struct {
	*mock.Call
}

// SwaggerURL is a helper method to define mock.On call
func (_e *MockSystemProvider_Expecter) SwaggerURL() *MockSystemProvider_SwaggerURL_Call {
	return &MockSystemProvider_SwaggerURL_Call{Call: _e.mock.On("SwaggerURL")}
}

func (_c *MockSystemProvider_SwaggerURL_Call) Run(run func()) *MockSystemProvider_SwaggerURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemProvider_SwaggerURL_Call) Return(_a0 string) *MockSystemProvider_SwaggerURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSystemProvider_SwaggerURL_Call) RunAndReturn(run func() string) *MockSystemProvider_SwaggerURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemProvider creates a new instance of MockSystemProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemProvider {
	mock := &MockSystemProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
