ALTER TABLE users
ADD COLUMN full_name VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN bio VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN avatar VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN cover_image VARCHAR(255) NOT NULL DEFAULT '',
ADD COLUMN location VARCHAR(100) NOT NULL DEFAULT '',
ADD COLUMN website VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE users
DROP COLUMN IF EXISTS profile;