ALTER TABLE users 
ADD COLUMN profile JSONB NOT NULL DEFAULT '{}'::JSONB;

ALTER TABLE users 
DROP COLUMN IF EXISTS full_name,
DROP COLUMN IF EXISTS bio,
DROP COLUMN IF EXISTS avatar,
DROP COLUMN IF EXISTS cover_image,
DROP COLUMN IF EXISTS location,
DROP COLUMN IF EXISTS website;