// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	notification "air-social/internal/domain/notification"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, userID, actorID, typ, targetID
func (_m *MockRepository) Delete(ctx context.Context, userID int64, actorID int64, typ notification.NotificationType, targetID *int64) error {
	ret := _m.Called(ctx, userID, actorID, typ, targetID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, notification.NotificationType, *int64) error); ok {
		r0 = rf(ctx, userID, actorID, typ, targetID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - actorID int64
//   - typ notification.NotificationType
//   - targetID *int64
func (_e *MockRepository_Expecter) Delete(ctx interface{}, userID interface{}, actorID interface{}, typ interface{}, targetID interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, actorID, typ, targetID)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, userID int64, actorID int64, typ notification.NotificationType, targetID *int64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(notification.NotificationType), args[4].(*int64))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(context.Context, int64, int64, notification.NotificationType, *int64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetList provides a mock function with given fields: ctx, params
func (_m *MockRepository) GetList(ctx context.Context, params notification.GetParams) ([]notification.Notification, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []notification.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, notification.GetParams) ([]notification.Notification, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, notification.GetParams) []notification.Notification); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notification.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, notification.GetParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetList'
type MockRepository_GetList_Call struct {
	*mock.Call
}

// GetList is a helper method to define mock.On call
//   - ctx context.Context
//   - params notification.GetParams
func (_e *MockRepository_Expecter) GetList(ctx interface{}, params interface{}) *MockRepository_GetList_Call {
	return &MockRepository_GetList_Call{Call: _e.mock.On("GetList", ctx, params)}
}

func (_c *MockRepository_GetList_Call) Run(run func(ctx context.Context, params notification.GetParams)) *MockRepository_GetList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(notification.GetParams))
	})
	return _c
}

func (_c *MockRepository_GetList_Call) Return(_a0 []notification.Notification, _a1 error) *MockRepository_GetList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetList_Call) RunAndReturn(run func(context.Context, notification.GetParams) ([]notification.Notification, error)) *MockRepository_GetList_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnreadCount provides a mock function with given fields: ctx, userID
func (_m *MockRepository) GetUnreadCount(ctx context.Context, userID int64) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetUnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnreadCount'
type MockRepository_GetUnreadCount_Call struct {
	*mock.Call
}

// GetUnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRepository_Expecter) GetUnreadCount(ctx interface{}, userID interface{}) *MockRepository_GetUnreadCount_Call {
	return &MockRepository_GetUnreadCount_Call{Call: _e.mock.On("GetUnreadCount", ctx, userID)}
}

func (_c *MockRepository_GetUnreadCount_Call) Run(run func(ctx context.Context, userID int64)) *MockRepository_GetUnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_GetUnreadCount_Call) Return(_a0 int64, _a1 error) *MockRepository_GetUnreadCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetUnreadCount_Call) RunAndReturn(run func(context.Context, int64) (int64, error)) *MockRepository_GetUnreadCount_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function with given fields: ctx, userID
func (_m *MockRepository) MarkAllRead(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockRepository_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockRepository_Expecter) MarkAllRead(ctx interface{}, userID interface{}) *MockRepository_MarkAllRead_Call {
	return &MockRepository_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead", ctx, userID)}
}

func (_c *MockRepository_MarkAllRead_Call) Run(run func(ctx context.Context, userID int64)) *MockRepository_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_MarkAllRead_Call) Return(_a0 error) *MockRepository_MarkAllRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkAllRead_Call) RunAndReturn(run func(context.Context, int64) error) *MockRepository_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, userID, id
func (_m *MockRepository) MarkRead(ctx context.Context, userID int64, id int64) error {
	ret := _m.Called(ctx, userID, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockRepository_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - id int64
func (_e *MockRepository_Expecter) MarkRead(ctx interface{}, userID interface{}, id interface{}) *MockRepository_MarkRead_Call {
	return &MockRepository_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, userID, id)}
}

func (_c *MockRepository_MarkRead_Call) Run(run func(ctx context.Context, userID int64, id int64)) *MockRepository_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockRepository_MarkRead_Call) Return(_a0 error) *MockRepository_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkRead_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockRepository_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function with given fields: ctx, n
func (_m *MockRepository) Upsert(ctx context.Context, n *notification.Notification) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *notification.Notification) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - n *notification.Notification
func (_e *MockRepository_Expecter) Upsert(ctx interface{}, n interface{}) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, n)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(ctx context.Context, n *notification.Notification)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*notification.Notification))
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(_a0 error) *MockRepository_Upsert_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(context.Context, *notification.Notification) error) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
