// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	media "air-social/internal/domain/media"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, location
func (_m *MockStorage) Delete(ctx context.Context, location media.Location) error {
	ret := _m.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, media.Location) error); ok {
		r0 = rf(ctx, location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - location media.Location
func (_e *MockStorage_Expecter) Delete(ctx interface{}, location interface{}) *MockStorage_Delete_Call {
	return &MockStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, location)}
}

func (_c *MockStorage_Delete_Call) Run(run func(ctx context.Context, location media.Location)) *MockStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(media.Location))
	})
	return _c
}

func (_c *MockStorage_Delete_Call) Return(_a0 error) *MockStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Delete_Call) RunAndReturn(run func(context.Context, media.Location) error) *MockStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, location
func (_m *MockStorage) Exists(ctx context.Context, location media.Location) (bool, error) {
	ret := _m.Called(ctx, location)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, media.Location) (bool, error)); ok {
		return rf(ctx, location)
	}
	if rf, ok := ret.Get(0).(func(context.Context, media.Location) bool); ok {
		r0 = rf(ctx, location)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, media.Location) error); ok {
		r1 = rf(ctx, location)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockStorage_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - location media.Location
func (_e *MockStorage_Expecter) Exists(ctx interface{}, location interface{}) *MockStorage_Exists_Call {
	return &MockStorage_Exists_Call{Call: _e.mock.On("Exists", ctx, location)}
}

func (_c *MockStorage_Exists_Call) Run(run func(ctx context.Context, location media.Location)) *MockStorage_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(media.Location))
	})
	return _c
}

func (_c *MockStorage_Exists_Call) Return(_a0 bool, _a1 error) *MockStorage_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Exists_Call) RunAndReturn(run func(context.Context, media.Location) (bool, error)) *MockStorage_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// PresignUpload provides a mock function with given fields: ctx, location, constraints
func (_m *MockStorage) PresignUpload(ctx context.Context, location media.Location, constraints media.Constraints) (media.UploadForm, error) {
	ret := _m.Called(ctx, location, constraints)

	if len(ret) == 0 {
		panic("no return value specified for PresignUpload")
	}

	var r0 media.UploadForm
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, media.Location, media.Constraints) (media.UploadForm, error)); ok {
		return rf(ctx, location, constraints)
	}
	if rf, ok := ret.Get(0).(func(context.Context, media.Location, media.Constraints) media.UploadForm); ok {
		r0 = rf(ctx, location, constraints)
	} else {
		r0 = ret.Get(0).(media.UploadForm)
	}

	if rf, ok := ret.Get(1).(func(context.Context, media.Location, media.Constraints) error); ok {
		r1 = rf(ctx, location, constraints)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_PresignUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignUpload'
type MockStorage_PresignUpload_Call struct {
	*mock.Call
}

// PresignUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - location media.Location
//   - constraints media.Constraints
func (_e *MockStorage_Expecter) PresignUpload(ctx interface{}, location interface{}, constraints interface{}) *MockStorage_PresignUpload_Call {
	return &MockStorage_PresignUpload_Call{Call: _e.mock.On("PresignUpload", ctx, location, constraints)}
}

func (_c *MockStorage_PresignUpload_Call) Run(run func(ctx context.Context, location media.Location, constraints media.Constraints)) *MockStorage_PresignUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(media.Location), args[2].(media.Constraints))
	})
	return _c
}

func (_c *MockStorage_PresignUpload_Call) Return(_a0 media.UploadForm, _a1 error) *MockStorage_PresignUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_PresignUpload_Call) RunAndReturn(run func(context.Context, media.Location, media.Constraints) (media.UploadForm, error)) *MockStorage_PresignUpload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
