// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/media"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// ConfirmUpload provides a mock function for the type MockUseCase
func (_mock *MockUseCase) ConfirmUpload(ctx context.Context, params []media.ConfirmParams) ([]string, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmUpload")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []media.ConfirmParams) ([]string, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []media.ConfirmParams) []string); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []media.ConfirmParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_ConfirmUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmUpload'
type MockUseCase_ConfirmUpload_Call struct {
	*mock.Call
}

// ConfirmUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - params []media.ConfirmParams
func (_e *MockUseCase_Expecter) ConfirmUpload(ctx interface{}, params interface{}) *MockUseCase_ConfirmUpload_Call {
	return &MockUseCase_ConfirmUpload_Call{Call: _e.mock.On("ConfirmUpload", ctx, params)}
}

func (_c *MockUseCase_ConfirmUpload_Call) Run(run func(ctx context.Context, params []media.ConfirmParams)) *MockUseCase_ConfirmUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []media.ConfirmParams
		if args[1] != nil {
			arg1 = args[1].([]media.ConfirmParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_ConfirmUpload_Call) Return(strings []string, err error) *MockUseCase_ConfirmUpload_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockUseCase_ConfirmUpload_Call) RunAndReturn(run func(ctx context.Context, params []media.ConfirmParams) ([]string, error)) *MockUseCase_ConfirmUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMedia provides a mock function for the type MockUseCase
func (_mock *MockUseCase) DeleteMedia(ctx context.Context, keys []string) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_DeleteMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMedia'
type MockUseCase_DeleteMedia_Call struct {
	*mock.Call
}

// DeleteMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockUseCase_Expecter) DeleteMedia(ctx interface{}, keys interface{}) *MockUseCase_DeleteMedia_Call {
	return &MockUseCase_DeleteMedia_Call{Call: _e.mock.On("DeleteMedia", ctx, keys)}
}

func (_c *MockUseCase_DeleteMedia_Call) Run(run func(ctx context.Context, keys []string)) *MockUseCase_DeleteMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_DeleteMedia_Call) Return(err error) *MockUseCase_DeleteMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_DeleteMedia_Call) RunAndReturn(run func(ctx context.Context, keys []string) error) *MockUseCase_DeleteMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateKey provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GenerateKey(params media.PresignParams) string {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(media.PresignParams) string); ok {
		r0 = returnFunc(params)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUseCase_GenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKey'
type MockUseCase_GenerateKey_Call struct {
	*mock.Call
}

// GenerateKey is a helper method to define mock.On call
//   - params media.PresignParams
func (_e *MockUseCase_Expecter) GenerateKey(params interface{}) *MockUseCase_GenerateKey_Call {
	return &MockUseCase_GenerateKey_Call{Call: _e.mock.On("GenerateKey", params)}
}

func (_c *MockUseCase_GenerateKey_Call) Run(run func(params media.PresignParams)) *MockUseCase_GenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 media.PresignParams
		if args[0] != nil {
			arg0 = args[0].(media.PresignParams)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUseCase_GenerateKey_Call) Return(s string) *MockUseCase_GenerateKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUseCase_GenerateKey_Call) RunAndReturn(run func(params media.PresignParams) string) *MockUseCase_GenerateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function for the type MockUseCase
func (_mock *MockUseCase) GetPresignedURL(ctx context.Context, params []media.PresignParams) ([]media.PresignedResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 []media.PresignedResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []media.PresignParams) ([]media.PresignedResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []media.PresignParams) []media.PresignedResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]media.PresignedResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []media.PresignParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUseCase_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type MockUseCase_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - ctx context.Context
//   - params []media.PresignParams
func (_e *MockUseCase_Expecter) GetPresignedURL(ctx interface{}, params interface{}) *MockUseCase_GetPresignedURL_Call {
	return &MockUseCase_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", ctx, params)}
}

func (_c *MockUseCase_GetPresignedURL_Call) Run(run func(ctx context.Context, params []media.PresignParams)) *MockUseCase_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []media.PresignParams
		if args[1] != nil {
			arg1 = args[1].([]media.PresignParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_GetPresignedURL_Call) Return(presignedResults []media.PresignedResult, err error) *MockUseCase_GetPresignedURL_Call {
	_c.Call.Return(presignedResults, err)
	return _c
}

func (_c *MockUseCase_GetPresignedURL_Call) RunAndReturn(run func(ctx context.Context, params []media.PresignParams) ([]media.PresignedResult, error)) *MockUseCase_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyMedia provides a mock function for the type MockUseCase
func (_mock *MockUseCase) VerifyMedia(ctx context.Context, keys []string) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUseCase_VerifyMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyMedia'
type MockUseCase_VerifyMedia_Call struct {
	*mock.Call
}

// VerifyMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []string
func (_e *MockUseCase_Expecter) VerifyMedia(ctx interface{}, keys interface{}) *MockUseCase_VerifyMedia_Call {
	return &MockUseCase_VerifyMedia_Call{Call: _e.mock.On("VerifyMedia", ctx, keys)}
}

func (_c *MockUseCase_VerifyMedia_Call) Run(run func(ctx context.Context, keys []string)) *MockUseCase_VerifyMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUseCase_VerifyMedia_Call) Return(err error) *MockUseCase_VerifyMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUseCase_VerifyMedia_Call) RunAndReturn(run func(ctx context.Context, keys []string) error) *MockUseCase_VerifyMedia_Call {
	_c.Call.Return(run)
	return _c
}
