// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/auth/token"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// AddToBlacklist provides a mock function for the type MockProvider
func (_mock *MockProvider) AddToBlacklist(ctx context.Context, accessToken string, expiresAt time.Time) {
	_mock.Called(ctx, accessToken, expiresAt)
	return
}

// MockProvider_AddToBlacklist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToBlacklist'
type MockProvider_AddToBlacklist_Call struct {
	*mock.Call
}

// AddToBlacklist is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
//   - expiresAt time.Time
func (_e *MockProvider_Expecter) AddToBlacklist(ctx interface{}, accessToken interface{}, expiresAt interface{}) *MockProvider_AddToBlacklist_Call {
	return &MockProvider_AddToBlacklist_Call{Call: _e.mock.On("AddToBlacklist", ctx, accessToken, expiresAt)}
}

func (_c *MockProvider_AddToBlacklist_Call) Run(run func(ctx context.Context, accessToken string, expiresAt time.Time)) *MockProvider_AddToBlacklist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProvider_AddToBlacklist_Call) Return() *MockProvider_AddToBlacklist_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProvider_AddToBlacklist_Call) RunAndReturn(run func(ctx context.Context, accessToken string, expiresAt time.Time)) *MockProvider_AddToBlacklist_Call {
	_c.Run(run)
	return _c
}

// GenerateAccessToken provides a mock function for the type MockProvider
func (_mock *MockProvider) GenerateAccessToken(userID int64, deviceID string) (token.AccessTokenResult, error) {
	ret := _mock.Called(userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 token.AccessTokenResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, string) (token.AccessTokenResult, error)); ok {
		return returnFunc(userID, deviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, string) token.AccessTokenResult); ok {
		r0 = returnFunc(userID, deviceID)
	} else {
		r0 = ret.Get(0).(token.AccessTokenResult)
	}
	if returnFunc, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = returnFunc(userID, deviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockProvider_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - userID int64
//   - deviceID string
func (_e *MockProvider_Expecter) GenerateAccessToken(userID interface{}, deviceID interface{}) *MockProvider_GenerateAccessToken_Call {
	return &MockProvider_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", userID, deviceID)}
}

func (_c *MockProvider_GenerateAccessToken_Call) Run(run func(userID int64, deviceID string)) *MockProvider_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_GenerateAccessToken_Call) Return(accessTokenResult token.AccessTokenResult, err error) *MockProvider_GenerateAccessToken_Call {
	_c.Call.Return(accessTokenResult, err)
	return _c
}

func (_c *MockProvider_GenerateAccessToken_Call) RunAndReturn(run func(userID int64, deviceID string) (token.AccessTokenResult, error)) *MockProvider_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockProvider
func (_mock *MockProvider) GenerateRefreshToken() token.RefreshTokenResult {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 token.RefreshTokenResult
	if returnFunc, ok := ret.Get(0).(func() token.RefreshTokenResult); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(token.RefreshTokenResult)
	}
	return r0
}

// MockProvider_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockProvider_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
func (_e *MockProvider_Expecter) GenerateRefreshToken() *MockProvider_GenerateRefreshToken_Call {
	return &MockProvider_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken")}
}

func (_c *MockProvider_GenerateRefreshToken_Call) Run(run func()) *MockProvider_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_GenerateRefreshToken_Call) Return(refreshTokenResult token.RefreshTokenResult) *MockProvider_GenerateRefreshToken_Call {
	_c.Call.Return(refreshTokenResult)
	return _c
}

func (_c *MockProvider_GenerateRefreshToken_Call) RunAndReturn(run func() token.RefreshTokenResult) *MockProvider_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function for the type MockProvider
func (_mock *MockProvider) HashToken(raw string) string {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockProvider_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - raw string
func (_e *MockProvider_Expecter) HashToken(raw interface{}) *MockProvider_HashToken_Call {
	return &MockProvider_HashToken_Call{Call: _e.mock.On("HashToken", raw)}
}

func (_c *MockProvider_HashToken_Call) Run(run func(raw string)) *MockProvider_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_HashToken_Call) Return(s string) *MockProvider_HashToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_HashToken_Call) RunAndReturn(run func(raw string) string) *MockProvider_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsBlacklisted provides a mock function for the type MockProvider
func (_mock *MockProvider) IsBlacklisted(ctx context.Context, accessToken string) bool {
	ret := _mock.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for IsBlacklisted")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, accessToken)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProvider_IsBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBlacklisted'
type MockProvider_IsBlacklisted_Call struct {
	*mock.Call
}

// IsBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockProvider_Expecter) IsBlacklisted(ctx interface{}, accessToken interface{}) *MockProvider_IsBlacklisted_Call {
	return &MockProvider_IsBlacklisted_Call{Call: _e.mock.On("IsBlacklisted", ctx, accessToken)}
}

func (_c *MockProvider_IsBlacklisted_Call) Run(run func(ctx context.Context, accessToken string)) *MockProvider_IsBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_IsBlacklisted_Call) Return(b bool) *MockProvider_IsBlacklisted_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProvider_IsBlacklisted_Call) RunAndReturn(run func(ctx context.Context, accessToken string) bool) *MockProvider_IsBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyAccessToken provides a mock function for the type MockProvider
func (_mock *MockProvider) VerifyAccessToken(token1 string) (token.TokenClaims, token.AccessTokenResult, error) {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for VerifyAccessToken")
	}

	var r0 token.TokenClaims
	var r1 token.AccessTokenResult
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (token.TokenClaims, token.AccessTokenResult, error)); ok {
		return returnFunc(token1)
	}
	if returnFunc, ok := ret.Get(0).(func(string) token.TokenClaims); ok {
		r0 = returnFunc(token1)
	} else {
		r0 = ret.Get(0).(token.TokenClaims)
	}
	if returnFunc, ok := ret.Get(1).(func(string) token.AccessTokenResult); ok {
		r1 = returnFunc(token1)
	} else {
		r1 = ret.Get(1).(token.AccessTokenResult)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(token1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProvider_VerifyAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyAccessToken'
type MockProvider_VerifyAccessToken_Call struct {
	*mock.Call
}

// VerifyAccessToken is a helper method to define mock.On call
//   - token1 string
func (_e *MockProvider_Expecter) VerifyAccessToken(token1 interface{}) *MockProvider_VerifyAccessToken_Call {
	return &MockProvider_VerifyAccessToken_Call{Call: _e.mock.On("VerifyAccessToken", token1)}
}

func (_c *MockProvider_VerifyAccessToken_Call) Run(run func(token1 string)) *MockProvider_VerifyAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_VerifyAccessToken_Call) Return(tokenClaims token.TokenClaims, accessTokenResult token.AccessTokenResult, err error) *MockProvider_VerifyAccessToken_Call {
	_c.Call.Return(tokenClaims, accessTokenResult, err)
	return _c
}

func (_c *MockProvider_VerifyAccessToken_Call) RunAndReturn(run func(token1 string) (token.TokenClaims, token.AccessTokenResult, error)) *MockProvider_VerifyAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyRefreshToken provides a mock function for the type MockProvider
func (_mock *MockProvider) VerifyRefreshToken(token1 token.RefreshToken) (bool, error) {
	ret := _mock.Called(token1)

	if len(ret) == 0 {
		panic("no return value specified for VerifyRefreshToken")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(token.RefreshToken) (bool, error)); ok {
		return returnFunc(token1)
	}
	if returnFunc, ok := ret.Get(0).(func(token.RefreshToken) bool); ok {
		r0 = returnFunc(token1)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(token.RefreshToken) error); ok {
		r1 = returnFunc(token1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_VerifyRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyRefreshToken'
type MockProvider_VerifyRefreshToken_Call struct {
	*mock.Call
}

// VerifyRefreshToken is a helper method to define mock.On call
//   - token1 token.RefreshToken
func (_e *MockProvider_Expecter) VerifyRefreshToken(token1 interface{}) *MockProvider_VerifyRefreshToken_Call {
	return &MockProvider_VerifyRefreshToken_Call{Call: _e.mock.On("VerifyRefreshToken", token1)}
}

func (_c *MockProvider_VerifyRefreshToken_Call) Run(run func(token1 token.RefreshToken)) *MockProvider_VerifyRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 token.RefreshToken
		if args[0] != nil {
			arg0 = args[0].(token.RefreshToken)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_VerifyRefreshToken_Call) Return(b bool, err error) *MockProvider_VerifyRefreshToken_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockProvider_VerifyRefreshToken_Call) RunAndReturn(run func(token1 token.RefreshToken) (bool, error)) *MockProvider_VerifyRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
