// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"air-social/internal/domain/health"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// CheckStatus provides a mock function for the type MockUseCase
func (_mock *MockUseCase) CheckStatus(ctx context.Context) (bool, map[string]string) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckStatus")
	}

	var r0 bool
	var r1 map[string]string
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, map[string]string)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) map[string]string); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}
	return r0, r1
}

// MockUseCase_CheckStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckStatus'
type MockUseCase_CheckStatus_Call struct {
	*mock.Call
}

// CheckStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUseCase_Expecter) CheckStatus(ctx interface{}) *MockUseCase_CheckStatus_Call {
	return &MockUseCase_CheckStatus_Call{Call: _e.mock.On("CheckStatus", ctx)}
}

func (_c *MockUseCase_CheckStatus_Call) Run(run func(ctx context.Context)) *MockUseCase_CheckStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUseCase_CheckStatus_Call) Return(b bool, stringToString map[string]string) *MockUseCase_CheckStatus_Call {
	_c.Call.Return(b, stringToString)
	return _c
}

func (_c *MockUseCase_CheckStatus_Call) RunAndReturn(run func(ctx context.Context) (bool, map[string]string)) *MockUseCase_CheckStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Overview provides a mock function for the type MockUseCase
func (_mock *MockUseCase) Overview(ctx context.Context) health.OverviewResponse {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Overview")
	}

	var r0 health.OverviewResponse
	if returnFunc, ok := ret.Get(0).(func(context.Context) health.OverviewResponse); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(health.OverviewResponse)
	}
	return r0
}

// MockUseCase_Overview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Overview'
type MockUseCase_Overview_Call struct {
	*mock.Call
}

// Overview is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUseCase_Expecter) Overview(ctx interface{}) *MockUseCase_Overview_Call {
	return &MockUseCase_Overview_Call{Call: _e.mock.On("Overview", ctx)}
}

func (_c *MockUseCase_Overview_Call) Run(run func(ctx context.Context)) *MockUseCase_Overview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUseCase_Overview_Call) Return(overviewResponse health.OverviewResponse) *MockUseCase_Overview_Call {
	_c.Call.Return(overviewResponse)
	return _c
}

func (_c *MockUseCase_Overview_Call) RunAndReturn(run func(ctx context.Context) health.OverviewResponse) *MockUseCase_Overview_Call {
	_c.Call.Return(run)
	return _c
}
